SELECT COUNT(*) QT_CERC_AP007 FROM AD.CERC_AP007;
SELECT COUNT(*) QT_CONTRACT_CUSTOMER FROM AD.CONTRACT_CUSTOMER;
SELECT COUNT(*) QT_CONTRACT_CUSTOMER_LEGACY FROM AD.CONTRACT_CUSTOMER_LEGACY;
SELECT COUNT(*) QT_CUSTOMER FROM AD.CUSTOMER;
SELECT COUNT(*) QT_CUSTOMER_ESCROW FROM AD.CUSTOMER_ESCROW;
SELECT COUNT(*) QT_CUSTOMER_PLAN FROM AD.CUSTOMER_PLAN;
SELECT COUNT(*) QT_CUSTOMER_REPLICATION FROM AD.CUSTOMER_REPLICATION;
SELECT COUNT(*) QT_PAYMENT_GROUP FROM AD.PAYMENT_GROUP;