SELECT   T.OWNER
        ,T.TABLE_NAME
        ,T.PARTITIONED TABLE_PARTITIONED   
        ,PKC.COLUMN_NAME COLUMN_PARTITION    
        ,C.INDEX_NAME
        ,I.PARTITIONED INDEX_PARTITIONED
        ,LISTAGG(C.COLUMN_NAME, ',') WITHIN GROUP (ORDER BY C.COLUMN_POSITION) INDEX_COLUMNS
        ,CASE WHEN T.PARTITIONED = 'YES' AND INSTR(PT.INTERVAL,'NUMTODSINTERVAL') >= 1 AND (I.PARTITIONED = 'NO' AND INSTR(LISTAGG(C.COLUMN_NAME, ','),PKC.COLUMN_NAME) >= 1) THEN 'NOK' 
              WHEN T.PARTITIONED = 'NO' AND I.PARTITIONED = 'YES' THEN 'NOK'
         ELSE 'OK'          
         END AS STATUS
          FROM   DBA_IND_COLUMNS C 
          INNER JOIN DBA_INDEXES I
          ON C.INDEX_OWNER = I.OWNER
          AND C.INDEX_NAME = I.INDEX_NAME
          AND C.TABLE_OWNER = I.TABLE_OWNER
          AND C.TABLE_NAME = I.TABLE_NAME
          INNER JOIN DBA_TABLES T 
          ON  I.TABLE_OWNER = T.OWNER
          AND I.TABLE_NAME = T.TABLE_NAME
          LEFT JOIN DBA_PART_TABLES PT 
          ON  T.OWNER = PT.OWNER
          AND T.TABLE_NAME = PT.TABLE_NAME
          LEFT JOIN DBA_PART_KEY_COLUMNS PKC
          ON T.OWNER = PKC.OWNER
          AND T.TABLE_NAME = PKC.NAME
          WHERE  C.INDEX_OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
            AND T.TABLE_NAME LIKE '%OUTBOX%'
          GROUP  BY T.OWNER
        ,T.TABLE_NAME
        ,T.PARTITIONED     
        ,PKC.COLUMN_NAME        
        ,C.INDEX_NAME
        ,I.PARTITIONED 
        ,PT.INTERVAL
ORDER BY 8        
        ;