CREATE TABLE RECEIVABLES_ADM.SETTLEMENT (
    IDT_SETTLEMENT      NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
    COD_SETTLEMENT      VARCHAR2(36 BYTE) NOT NULL,
    DAT_CREATION        TIMESTAMP NOT NULL,
    CONSTRAINT SETTLEMENT_PK PRIMARY KEY ( IDT_SETTLEMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
) INITRANS 32
TABLESPACE TSDRECEIVABLES01;

COMMENT ON TABLE RECEIVABLES_ADM.SETTLEMENT IS 'Tabela para controle do processo de liquidação';

COMMENT ON COLUMN RECEIVABLES_ADM.SETTLEMENT.IDT_SETTLEMENT IS '[NOT_SECURITY_APPLY] Identificador da entidade';

COMMENT ON COLUMN RECEIVABLES_ADM.SETTLEMENT.COD_SETTLEMENT IS '[NOT_SECURITY_APPLY] Código de identificação da SETTLEMENT';

COMMENT ON COLUMN RECEIVABLES_ADM.SETTLEMENT.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';

-- Unique
ALTER TABLE RECEIVABLES_ADM.SETTLEMENT ADD CONSTRAINT SETTLEMENT_UK01 UNIQUE ( COD_SETTLEMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;

-- Grants
GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.SETTLEMENT TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.SETTLEMENT TO MANUT_RECEIVABLES;