CREATE TABLE RECEIVABLES_ADM.RECEIVABLE_EXTERNAL (
    IDT_RECEIVABLE NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
    IDT_RECEIVABLE_UNIT NUMBER(20, 0) NOT NULL ,
    IDT_PAYMENT NUMBER(20, 0) NOT NULL ,
    COD_RECEIVABLE VARCHAR2(36 BYTE) NOT NULL ,
    COD_CUSTOMER_RECEIVER VARCHAR2(36 BYTE) NOT NULL ,
    DAT_CREATION TIMESTAMP(6) NOT NULL ,
    DAT_UPDATE TIMESTAMP(6) NOT NULL ,
    IND_STATUS VARCHAR2(50 BYTE) NOT NULL ,
    DAT_SETTLE DATE NOT NULL ,
    DAT_SETTLED TIMESTAMP(6) ,
    NUM_TOTAL_AMOUNT NUMBER(11, 0) NOT NULL ,
    NUM_SETTLE_AMOUNT NUMBER(11, 0) NOT NULL ,
    NUM_COMMITTED_AMOUNT NUMBER(11, 0) NOT NULL ,
    NUM_SETTLED_AMOUNT NUMBER(11, 0) ,
    NUM_ANTICIPATED_AMOUNT NUMBER(11, 0) NOT NULL ,
    NUM_SUSPENDED_AMOUNT NUMBER(11, 0) NOT NULL ,
    NUM_CANCELED_AMOUNT NUMBER(11, 0) NOT NULL ,
    NUM_INPERSON_AMOUNT NUMBER(11, 0) NOT NULL ,
    NUM_ONLINE_AMOUNT NUMBER(11, 0) NOT NULL ,
    JSN_SELLER_FEE VARCHAR2(4000 BYTE) NOT NULL ,
    JSN_BUYER_FEE VARCHAR2(4000 BYTE) ,
    NUM_VERSION NUMBER(10, 0) NOT NULL ,
    NUM_RECEIVER_DOCUMENT VARCHAR2(15 BYTE) NOT NULL ,
	CONSTRAINT RECEIVABLE_EXTERNAL_PK PRIMARY KEY ( IDT_RECEIVABLE ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48,
	CONSTRAINT JSN_SEL_FEE_REC_EXT_CK CHECK ( JSN_SELLER_FEE IS JSON ),
	CONSTRAINT JSN_BUY_FEE_REC_EXT_CK CHECK ( JSN_BUYER_FEE IS JSON )
)
PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_1 VALUES LESS THAN (TO_DATE('2020-10-10','YYYY-MM-DD'))
) TABLESPACE TSDRECEIVABLES01 INITRANS 64 PCTFREE 20
;

-- RECEIVABLE_EXTERNAL

COMMENT ON TABLE RECEIVABLES_ADM.RECEIVABLE_EXTERNAL IS 'Tabela que guardará dados dos recebíveis externos';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.IDT_RECEIVABLE IS '[NOT_SECURITY_APPLY] Identificador do recebível externo';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.IDT_RECEIVABLE_UNIT IS '[NOT_SECURITY_APPLY] Identificador da unidade de recebível externo';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.IDT_PAYMENT IS '[NOT_SECURITY_APPLY] Identificador do pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.COD_RECEIVABLE IS '[NOT_SECURITY_APPLY] Código do Recebível externo';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.COD_CUSTOMER_RECEIVER IS '[NOT_SECURITY_APPLY] Identificador do usuário vendedor do PagSeguro';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data de atualização';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.IND_STATUS IS '[NOT_SECURITY_APPLY] Indicador de Status. Tipos: SCHEDULED, SUSPENDED, CANCELED, PARTIALLY_COMPLETED, COMPLETED';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.DAT_SETTLE IS '[NOT_SECURITY_APPLY] Data a ser liquidada da unidade de recebivel';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.DAT_SETTLED IS '[NOT_SECURITY_APPLY] Valor total do recebível';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_TOTAL_AMOUNT IS '[NOT_SECURITY_APPLY] Valor total do recebível';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_SETTLE_AMOUNT IS '[NOT_SECURITY_APPLY] Valor a liquidar';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_COMMITTED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor reservado pelo contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_SETTLED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor liquidado';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_ANTICIPATED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor antecipado';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_SUSPENDED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor suspenso';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_CANCELED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor cancelado';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_INPERSON_AMOUNT IS '[NOT_SECURITY_APPLY] Valor que foi transacionado de forma presencial';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_ONLINE_AMOUNT IS '[NOT_SECURITY_APPLY] Valor que foi transacionado de forma online';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.JSN_SELLER_FEE IS '[NOT_SECURITY_APPLY] Valores  e tipos de taxas do vendedor';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.JSN_BUYER_FEE IS '[NOT_SECURITY_APPLY] Valores  e tipos de taxas do comprador';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_VERSION IS '[NOT_SECURITY_APPLY] Número da versão';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_RECEIVER_DOCUMENT IS '[PII] Numero do documento do recebedor';

CREATE INDEX RECEIVABLES_ADM.RECEIVABLE_EXTERNAL_IDX01 ON RECEIVABLES_ADM.RECEIVABLE_EXTERNAL ( IDT_PAYMENT ) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;	

CREATE INDEX RECEIVABLES_ADM.RECEIVABLE_EXTERNAL_IDX02 ON RECEIVABLES_ADM.RECEIVABLE_EXTERNAL ( IDT_RECEIVABLE_UNIT ) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;	

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_EXTERNAL ADD CONSTRAINT RECEIVABLE_EXTERNAL_UK01 UNIQUE ( COD_RECEIVABLE ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_EXTERNAL ADD CONSTRAINT REC_EXT_IDT_PAYMENT_FK FOREIGN KEY ( IDT_PAYMENT )
        REFERENCES RECEIVABLES_ADM.PAYMENT ( IDT_PAYMENT ) ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_EXTERNAL ADD CONSTRAINT REC_EXT_IDT_REC_UNIT_EXT_FK FOREIGN KEY ( IDT_RECEIVABLE_UNIT )
        REFERENCES RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL ( IDT_RECEIVABLE_UNIT ) ENABLE NOVALIDATE;

GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.RECEIVABLE_EXTERNAL TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.RECEIVABLE_EXTERNAL TO MANUT_RECEIVABLES;