CREATE TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION (
IDT_RECEIVABLE_UNIT_ASSOCIATION NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
IDT_RECEIVABLE_UNIT_EXTERNAL NUMBER(20) NOT NULL,
IDT_RECEIVABLE_UNIT_INTERNAL NUMBER(20) NOT NULL,
CONSTRAINT REC_UNIT_ASSOCIATION_PK PRIMARY KEY (IDT_RECEIVABLE_UNIT_ASSOCIATION ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
)
PARTITION BY RANGE(IDT_RECEIVABLE_UNIT_ASSOCIATION)
INTERVAL (1500000)
(PARTITION P_1 VALUES LESS THAN (1500000)
) INITRANS 32 TABLESPACE TSDRECEIVABLES01
;

COMMENT ON TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION IS 'Tabela de relacionamento entre a receivable unit internal e external';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION.IDT_RECEIVABLE_UNIT_ASSOCIATION IS '[NOT_SECURITY_APPLY] Identificador da intenção do recebível';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION.IDT_RECEIVABLE_UNIT_EXTERNAL IS '[NOT_SECURITY_APPLY] Identificador da tabela receivable unit external';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION.IDT_RECEIVABLE_UNIT_INTERNAL IS '[NOT_SECURITY_APPLY] Identificador da tabela receivable unit internal';

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION ADD CONSTRAINT REC_UNIT_ASSOCIATION_UK01 UNIQUE ( IDT_RECEIVABLE_UNIT_EXTERNAL, IDT_RECEIVABLE_UNIT_INTERNAL) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION ADD CONSTRAINT REC_UNIT_ASS_REC_EXT_IDT_FK FOREIGN KEY ( IDT_RECEIVABLE_UNIT_EXTERNAL )
REFERENCES RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL ( IDT_RECEIVABLE_UNIT ) ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION ADD CONSTRAINT REC_UNIT_ASS_REC_INT_IDT_FK FOREIGN KEY ( IDT_RECEIVABLE_UNIT_INTERNAL )
REFERENCES RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL ( IDT_RECEIVABLE_UNIT ) ENABLE NOVALIDATE;

CREATE INDEX RECEIVABLES_ADM.REC_UNIT_ASSOCIATION_IDX01 ON RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION ( IDT_RECEIVABLE_UNIT_EXTERNAL ) TABLESPACE TSIRECEIVABLES01 INITRANS 12 ONLINE;

CREATE INDEX RECEIVABLES_ADM.REC_UNIT_ASSOCIATION_IDX02 ON RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION ( IDT_RECEIVABLE_UNIT_INTERNAL ) TABLESPACE TSIRECEIVABLES01 INITRANS 12 ONLINE;

GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION TO MANUT_RECEIVABLES;