CREATE TABLE RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY (
    IDT_CCE_STATIC_AMOUNT_SUMMARY NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
    IDT_CONTRACTUAL_EFFECT NUMBER(20, 0) NOT NULL ,
    DAT_SETTLE DATE NOT NULL ,
    NUM_TOTAL_AMOUNT NUMBER(11, 0) NOT NULL ,
    NUM_RESERVED_AMOUNT NUMBER(11, 0) NOT NULL ,
    DAT_CREATION TIMESTAMP(6) NOT NULL ,
    DAT_UPDATE TIMESTAMP(6) NOT NULL ,
    NUM_VERSION NUMBER(10, 0) NOT NULL,
	CONSTRAINT CCE_STATIC_AMOUNT_SUMMARY_PK PRIMARY KEY ( IDT_CCE_STATIC_AMOUNT_SUMMARY ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
)
PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_1 VALUES LESS THAN (TO_DATE('2020-10-10','YYYY-MM-DD'))
) TABLESPACE TSDRECEIVABLES01 INITRANS 32
;

COMMENT ON TABLE RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY IS  'Tabela que guardará o valor sumarizado do contrato estático';
COMMENT ON COLUMN RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY.IDT_CCE_STATIC_AMOUNT_SUMMARY IS '[NOT_SECURITY_APPLY] Identificador do registro sumarizado do efeito de contrato estático';
COMMENT ON COLUMN RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY.IDT_CONTRACTUAL_EFFECT IS '[NOT_SECURITY_APPLY] Identificador do efeito de contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY.DAT_SETTLE IS '[NOT_SECURITY_APPLY] Data a ser liquidada da unidade de recebivel';
COMMENT ON COLUMN RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY.NUM_TOTAL_AMOUNT IS '[NOT_SECURITY_APPLY] Valor total somado da unidade de recebível';
COMMENT ON COLUMN RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY.NUM_RESERVED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor reservado para o contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';
COMMENT ON COLUMN RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data de atualização';
COMMENT ON COLUMN RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY.NUM_VERSION IS '[NOT_SECURITY_APPLY] Numero da versão';

CREATE INDEX RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY_IDX01 ON RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY ( DAT_SETTLE, IDT_CONTRACTUAL_EFFECT )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

ALTER TABLE RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY ADD CONSTRAINT STA_SUM_IDT_CON_EFFE_FK FOREIGN KEY ( IDT_CONTRACTUAL_EFFECT )
        REFERENCES RECEIVABLES_ADM.CONTRACTUAL_EFFECT ( IDT_CONTRACTUAL_EFFECT ) ENABLE NOVALIDATE;

GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY TO MANUT_RECEIVABLES;