CREATE TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT (
  IDT_CONTRACTUAL_EFFECT NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
  IDT_PAYMENT_ADDRESS NUMBER(20, 0) NOT NULL ,
  IDT_RECEIVABLE_UNIT_EXTERNAL NUMBER(20, 0) ,
  IDT_RECEIVABLE_UNIT_INTERNAL NUMBER(20, 0) ,
  COD_CONTRACTUAL_EFFECT VARCHAR2(36 BYTE) NOT NULL ,
  IND_TYPE VARCHAR2(50 BYTE) NOT NULL ,
  IND_DIVISION_RULE VARCHAR2(20 BYTE) NOT NULL ,
  NUM_SETTLE_AMOUNT NUMBER(11, 0) NOT NULL ,
  NUM_SETTLED_AMOUNT NUMBER(11, 0) ,
  NUM_ORDER NUMBER(2, 0) NOT NULL ,
  DAT_SETTLED TIMESTAMP(6) ,
  IND_STATUS VARCHAR2(40 BYTE) NOT NULL ,
  NUM_COMMITTED_VALUE NUMBER(11, 0) ,
  COD_CUSTOMER_RECEIVER VARCHAR2(36 BYTE) NOT NULL ,
  COD_CUSTOMER_HOLDER VARCHAR2(36 BYTE) NOT NULL ,
  IND_PAYMENT_GROUP VARCHAR2(50 BYTE) NOT NULL ,
  DAT_SETTLE DATE NOT NULL ,
  FLG_ACTIVE NUMBER(1, 0) NOT NULL ,
  FLG_EXTERNAL NUMBER(1, 0) NOT NULL, 
  NUM_VERSION NUMBER(10, 0) NOT NULL,
  DAT_CREATION TIMESTAMP(6) NOT NULL,
  DAT_UPDATE TIMESTAMP(6) NOT NULL,
    CONSTRAINT CONTRACTUAL_EFFECT_PK PRIMARY KEY ( IDT_CONTRACTUAL_EFFECT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
)
PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_1 VALUES LESS THAN (TO_DATE('2020-10-10','YYYY-MM-DD'))
) TABLESPACE TSDRECEIVABLES01 INITRANS 64 PCTFREE 20
;

COMMENT ON TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT IS
    'Tabela que guardará dados dos efeitos de contrato';

COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IDT_CONTRACTUAL_EFFECT IS '[NOT_SECURITY_APPLY] Identificador do efeito de contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IDT_PAYMENT_ADDRESS IS '[NOT_SECURITY_APPLY] Identificador do endereço de pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IDT_RECEIVABLE_UNIT_EXTERNAL IS '[NOT_SECURITY_APPLY] Identificador da unidade de recebível externa';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IDT_RECEIVABLE_UNIT_INTERNAL IS '[NOT_SECURITY_APPLY] Identificador da unidade de recebível interna';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.COD_CONTRACTUAL_EFFECT IS '[NOT_SECURITY_APPLY] Código do efeito de contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IND_TYPE IS '[NOT_SECURITY_APPLY] Indicador do tipo de contrato. Tipos: ONUS, OWNERSHIP_CHANGE';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IND_DIVISION_RULE IS '[NOT_SECURITY_APPLY] Indicador do tipo do campo COMMITTED_VALUE. Tipos: PERCENTAGE, STATIC_AMOUNT';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.NUM_SETTLE_AMOUNT IS '[NOT_SECURITY_APPLY] Valor a liquidar';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.NUM_SETTLED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor liquidado';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.NUM_ORDER IS '[NOT_SECURITY_APPLY] Número da ordem de prioridade do efeito de contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.DAT_SETTLED IS '[NOT_SECURITY_APPLY] Data que foi liquidado o efeito de contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IND_STATUS IS '[NOT_SECURITY_APPLY] Indicador do status do efeito de contrato. Tipos: SCHEDULED, CANCELLED, CASHOUT_AUTHORIZATION, COMPLETED';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.NUM_COMMITTED_VALUE IS '[NOT_SECURITY_APPLY] Valor aplicado ao tipo de efeito contrario';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.COD_CUSTOMER_RECEIVER IS '[NOT_SECURITY_APPLY] Código do usuário recebedor do efeito de contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.COD_CUSTOMER_HOLDER IS '[NOT_SECURITY_APPLY] Código do usuário titular do efeito de contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IND_PAYMENT_GROUP IS '[NOT_SECURITY_APPLY] Indicador de Bandeira + Meio de Pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.DAT_SETTLE IS '[NOT_SECURITY_APPLY] Data a ser liquidado do efeito de contrato';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.FLG_ACTIVE IS '[NOT_SECURITY_APPLY] Boleano que indicar se o efeito de contrato esta ativo (0 ou 1)';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.FLG_EXTERNAL IS '[NOT_SECURITY_APPLY] Boleano que indicar se o efeito de contrato é externo (0 ou 1)';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.NUM_VERSION IS '[NOT_SECURITY_APPLY] Numero da versão';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';
COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data de atualização';


CREATE INDEX RECEIVABLES_ADM.CONTRACTUAL_EFFECT_IDX01 ON RECEIVABLES_ADM.CONTRACTUAL_EFFECT ( DAT_SETTLE, COD_CONTRACTUAL_EFFECT )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX RECEIVABLES_ADM.CONTRACTUAL_EFFECT_IDX02 ON RECEIVABLES_ADM.CONTRACTUAL_EFFECT ( DAT_SETTLE, IDT_PAYMENT_ADDRESS )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX RECEIVABLES_ADM.CONTRACTUAL_EFFECT_IDX03 ON RECEIVABLES_ADM.CONTRACTUAL_EFFECT ( DAT_SETTLE, IDT_RECEIVABLE_UNIT_EXTERNAL )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX RECEIVABLES_ADM.CONTRACTUAL_EFFECT_IDX04 ON RECEIVABLES_ADM.CONTRACTUAL_EFFECT ( DAT_SETTLE, IDT_RECEIVABLE_UNIT_INTERNAL )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE UNIQUE INDEX RECEIVABLES_ADM.CONTRACTUAL_EFFECT_IDX05
ON CONTRACTUAL_EFFECT (
   CASE WHEN FLG_ACTIVE = 1 THEN DAT_SETTLE             ELSE NULL END,
   CASE WHEN FLG_ACTIVE = 1 THEN FLG_ACTIVE             ELSE NULL END,
   CASE WHEN FLG_ACTIVE = 1 THEN NUM_ORDER              ELSE NULL END,
   CASE WHEN FLG_ACTIVE = 1 THEN COD_CUSTOMER_RECEIVER  ELSE NULL END,
   CASE WHEN FLG_ACTIVE = 1 THEN COD_CUSTOMER_HOLDER    ELSE NULL END,
   CASE WHEN FLG_ACTIVE = 1 THEN IND_PAYMENT_GROUP      ELSE NULL END)
INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX RECEIVABLES_ADM.CONTRACTUAL_EFFECT_IDX06 ON RECEIVABLES_ADM.CONTRACTUAL_EFFECT 
( DAT_SETTLE, COD_CUSTOMER_RECEIVER,COD_CUSTOMER_HOLDER, IND_PAYMENT_GROUP, FLG_ACTIVE )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT ADD CONSTRAINT CONTRACTUAL_EFFECT_UK01 UNIQUE ( COD_CONTRACTUAL_EFFECT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48 ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT ADD CONSTRAINT CON_EFF_IDT_PAY_ADDR_FK FOREIGN KEY ( IDT_PAYMENT_ADDRESS )
        REFERENCES RECEIVABLES_ADM.PAYMENT_ADDRESS ( IDT_PAYMENT_ADDRESS ) ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT ADD CONSTRAINT CON_EFF_IDT_REC_EXT_FK FOREIGN KEY ( IDT_RECEIVABLE_UNIT_EXTERNAL )
        REFERENCES RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL ( IDT_RECEIVABLE_UNIT ) ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT ADD CONSTRAINT CON_EFF_IDT_REC_INT_FK FOREIGN KEY ( IDT_RECEIVABLE_UNIT_INTERNAL )
        REFERENCES RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL ( IDT_RECEIVABLE_UNIT ) ENABLE NOVALIDATE;
		
GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.CONTRACTUAL_EFFECT TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.CONTRACTUAL_EFFECT TO MANUT_RECEIVABLES;