CREATE TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL (
  IDT_RECEIVABLE_UNIT NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
  COD_RECEIVABLE_UNIT VARCHAR2(36 BYTE) NOT NULL ,
  COD_CUSTOMER_RECEIVER VARCHAR2(36 BYTE) NOT NULL ,
  IND_PAYMENT_GROUP VARCHAR2(50 BYTE) NOT NULL ,
  COD_CUSTOMER_HOLDER VARCHAR2(36 BYTE) NOT NULL, 
  DAT_SETTLE DATE NOT NULL ,
  DAT_CREATION TIMESTAMP(6) NOT NULL ,
  DAT_UPDATE TIMESTAMP(6) NOT NULL ,
  IND_STATUS VARCHAR2(40 BYTE) NOT NULL ,
  DAT_SETTLED TIMESTAMP(6) ,
  NUM_TOTAL_AMOUNT NUMBER(11, 0) NOT NULL ,
  NUM_SETTLE_AMOUNT NUMBER(11, 0) NOT NULL ,
  NUM_COMMITTED_AMOUNT NUMBER(11, 0) NOT NULL ,
  NUM_SETTLED_AMOUNT NUMBER(11, 0) ,
  NUM_ANTICIPATED_AMOUNT NUMBER(11, 0) NOT NULL ,
  NUM_SUSPENDED_AMOUNT NUMBER(11, 0) NOT NULL ,
  NUM_CANCELED_AMOUNT NUMBER(11, 0) NOT NULL ,
  NUM_ONLINE_AMOUNT NUMBER(11, 0) NOT NULL ,
  NUM_INPERSON_AMOUNT NUMBER(11, 0) NOT NULL, 
  JSN_SELLER_FEE VARCHAR2(4000 BYTE) NOT NULL, 
  JSN_BUYER_FEE VARCHAR2(4000 BYTE) ,
  NUM_VERSION NUMBER(10, 0) NOT NULL ,
  NUM_RECEIVER_DOCUMENT VARCHAR2(15 BYTE) NOT NULL ,
  IND_INTERNAL_STATUS VARCHAR2(50 BYTE)  NOT NULL,
  IND_ESCROW_TYPE VARCHAR2(30 BYTE) NOT NULL ,
  FLG_INTERMEDIATED NUMBER(1, 0) NOT NULL ,
  NUM_RECOVERED_AMOUNT NUMBER(11, 0) NOT NULL,  
  IDT_RECEIVER_SAFEPAY_USER NUMBER(20) NOT NULL,
	CONSTRAINT RECEIVABLE_UNIT_INTERNAL_PK PRIMARY KEY ( IDT_RECEIVABLE_UNIT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48,
	CONSTRAINT JSN_SEL_FEE_REC_UNIT_INT_CK CHECK (JSN_SELLER_FEE IS JSON),
	CONSTRAINT JSN_BUY_FEE_REC_UNIT_INT_CK CHECK (JSN_BUYER_FEE IS JSON)
)
PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_1 VALUES LESS THAN (TO_DATE('2020-10-10','YYYY-MM-DD'))
) TABLESPACE TSDRECEIVABLES01 INITRANS 64 PCTFREE 20
;

COMMENT ON TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL IS 'Tabela que guardará dados das unidades de recebíveis internas';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.IDT_RECEIVABLE_UNIT IS '[NOT_SECURITY_APPLY] Identificador da unidade de recebível interno';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.COD_RECEIVABLE_UNIT IS '[NOT_SECURITY_APPLY] Código da unidade de recebível interno';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.COD_CUSTOMER_RECEIVER IS '[NOT_SECURITY_APPLY] Identificador do usuário recebedor do PagSeguro';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.IND_PAYMENT_GROUP IS '[NOT_SECURITY_APPLY] Indicador de Bandeira + Meio de Pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.COD_CUSTOMER_HOLDER IS '[NOT_SECURITY_APPLY] Identificador do usuário titular da unidade';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.DAT_SETTLE IS '[NOT_SECURITY_APPLY] Data a ser liquidada da unidade de recebivel';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data de atualização';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.IND_STATUS IS '[NOT_SECURITY_APPLY] Indicador de Status. Tipos: SCHEDULED, UNSCHEDULED, CASHOUT_AUTHORIZATION e COMPLETED';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.DAT_SETTLED IS '[NOT_SECURITY_APPLY] Data que foi liquidada a unidade de recebivel';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_TOTAL_AMOUNT IS '[NOT_SECURITY_APPLY] Valor total da unidade de recebível';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_SETTLE_AMOUNT IS '[NOT_SECURITY_APPLY] Valor a liquidar';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_COMMITTED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor intermediado';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_SETTLED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor liquidado';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_ANTICIPATED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor antecipado';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_SUSPENDED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor suspenso';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_CANCELED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor cancelado';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_ONLINE_AMOUNT IS '[NOT_SECURITY_APPLY] Valor que foi transacionado de forma online';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_INPERSON_AMOUNT IS '[NOT_SECURITY_APPLY] Valor que foi transacionado de forma presencial';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.JSN_SELLER_FEE IS '[NOT_SECURITY_APPLY] Valores  e tipos de taxas do vendedor';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.JSN_BUYER_FEE IS '[NOT_SECURITY_APPLY] Valores  e tipos de taxas do comprador';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_VERSION IS '[NOT_SECURITY_APPLY] Numero da versão';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_RECEIVER_DOCUMENT IS '[PII] Numero do documento do recebedor';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.IND_INTERNAL_STATUS IS '[NOT_SECURITY_APPLY] Status para controle de processamento interno';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.IND_ESCROW_TYPE IS '[NOT_SECURITY_APPLY] Indicador de condições de pagamento. Ex.: UNIQUE ou MULTIPLE';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.FLG_INTERMEDIATED IS '[NOT_SECURITY_APPLY] Boleano que indica se o recebível será intermediado por entidade externa (0 ou 1).';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_RECOVERED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor recuperado após liquidação na agenda de débitos';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.IDT_RECEIVER_SAFEPAY_USER IS '[NOT_SECURITY_APPLY] Id do Legado do Pagseguro';

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL ADD CONSTRAINT RECEIVABLE_UNIT_INTERNAL_uk01 UNIQUE ( COD_RECEIVABLE_UNIT )  USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48 ENABLE NOVALIDATE;

CREATE INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL_IDX01 ON RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL (DAT_SETTLE , COD_CUSTOMER_RECEIVER , COD_CUSTOMER_HOLDER , IND_PAYMENT_GROUP , IND_STATUS , IND_ESCROW_TYPE ) LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE UNIQUE INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL_IDX02 
ON RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL 
   (DAT_SETTLE , 
   CASE IND_STATUS WHEN 'SCHEDULED' THEN DAT_SETTLE            ELSE NULL END , 
   CASE IND_STATUS WHEN 'SCHEDULED' THEN IND_STATUS            ELSE NULL END , 
   CASE IND_STATUS WHEN 'SCHEDULED' THEN COD_CUSTOMER_RECEIVER ELSE NULL END , 
   CASE IND_STATUS WHEN 'SCHEDULED' THEN COD_CUSTOMER_HOLDER   ELSE NULL END , 
   CASE IND_STATUS WHEN 'SCHEDULED' THEN IND_PAYMENT_GROUP     ELSE NULL END , 
   CASE IND_STATUS WHEN 'SCHEDULED' THEN IND_ESCROW_TYPE       ELSE NULL END ) 
LOCAL INITRANS 48 tablespace TSIRECEIVABLES01  online;   

GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL TO MANUT_RECEIVABLES;