CREATE TABLE RECEIVABLES_ADM.RECEIVABLE_INTENT (
IDT_RECEIVABLE_INTENT NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
COD_PAYMENT         VARCHAR2(36 BYTE) NOT NULL,
JSN_PAYLOAD         VARCHAR2(4000 BYTE) NOT NULL,
DAT_CREATION        TIMESTAMP NOT NULL,
DAT_SENT            TIMESTAMP,
CONSTRAINT RECEIVABLE_INTENT_PK PRIMARY KEY ( IDT_RECEIVABLE_INTENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
) INITRANS 32 TABLESPACE TSDRECEIVABLES01;

COMMENT ON TABLE RECEIVABLES_ADM.RECEIVABLE_INTENT IS 'Tabela que guardará dados referente os recebíveis com intenções de pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_INTENT.IDT_RECEIVABLE_INTENT IS '[NOT_SECURITY_APPLY] Identificador da intenção do recebível';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_INTENT.COD_PAYMENT IS '[NOT_SECURITY_APPLY] Código do pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_INTENT.JSN_PAYLOAD IS '[NOT_SECURITY_APPLY] Payload enviado na requisição';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_INTENT.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação do registro na tabela';
COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_INTENT.DAT_SENT IS '[NOT_SECURITY_APPLY] Data que foi enviado o registro para a fila';

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_INTENT ADD CONSTRAINT RECEIVABLE_INTENT_UK01 UNIQUE ( COD_PAYMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;

GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.RECEIVABLE_INTENT TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.RECEIVABLE_INTENT TO MANUT_RECEIVABLES;