CREATE TABLE RECEIVABLES_ADM.RECOVERY (
    IDT_RECOVERY NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
    IDT_SETTLEMENT                  NUMBER(20) NOT NULL,
    COD_REFERENCE                   VARCHAR2(36 BYTE) NOT NULL,
    NUM_RECOVERED_AMOUNT            NUMBER(11) NOT NULL,
    NUM_REMAINING_AMOUNT            NUMBER(11) NOT NULL,
    NUM_TOTAL_AMOUNT                NUMBER(11) NOT NULL,
    DAT_SETTLE                      DATE NOT NULL,
    DAT_CREATION                    TIMESTAMP NOT NULL,
	CONSTRAINT RECOVERY_PK PRIMARY KEY ( IDT_RECOVERY ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
)
PARTITION BY RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_2020_07_23 VALUES LESS THAN (TO_DATE('2020-07-23','YYYY-MM-DD'))) TABLESPACE TSDRECEIVABLES01 INITRANS 32;

COMMENT ON TABLE RECEIVABLES_ADM.RECOVERY IS 'Tabela para controle dos valores recuperados da unidade de recebível';

COMMENT ON COLUMN RECEIVABLES_ADM.RECOVERY.IDT_RECOVERY IS '[NOT_SECURITY_APPLY] Identificador da recuperação';

COMMENT ON COLUMN RECEIVABLES_ADM.RECOVERY.IDT_SETTLEMENT IS '[NOT_SECURITY_APPLY] Código de identificação da SETTLEMENT';

COMMENT ON COLUMN RECEIVABLES_ADM.RECOVERY.COD_REFERENCE IS '[NOT_SECURITY_APPLY] Código que referencia a origem do débito';

COMMENT ON COLUMN RECEIVABLES_ADM.RECOVERY.NUM_RECOVERED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor recuperado da agenda de débitos';

COMMENT ON COLUMN RECEIVABLES_ADM.RECOVERY.NUM_REMAINING_AMOUNT IS '[NOT_SECURITY_APPLY] Valor remanescente na unidade de recebíveis após liquidação';

COMMENT ON COLUMN RECEIVABLES_ADM.RECOVERY.NUM_TOTAL_AMOUNT IS '[NOT_SECURITY_APPLY] Valor total da liquidação';

COMMENT ON COLUMN RECEIVABLES_ADM.RECOVERY.DAT_SETTLE IS '[NOT_SECURITY_APPLY] Data efetiva da liquidação';

COMMENT ON COLUMN RECEIVABLES_ADM.RECOVERY.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data/Hora da criação do registro na tabela';

-- Unique
ALTER TABLE RECEIVABLES_ADM.RECOVERY ADD CONSTRAINT RECOVERY_UK01 UNIQUE ( COD_REFERENCE ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 36 ENABLE NOVALIDATE;

-- FK with index
ALTER TABLE RECEIVABLES_ADM.RECOVERY ADD CONSTRAINT RECOVERY_IDT_SETTLEMENT_FK FOREIGN KEY ( IDT_SETTLEMENT )
        REFERENCES RECEIVABLES_ADM.SETTLEMENT ( IDT_SETTLEMENT ) ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.RECOVERY ADD CONSTRAINT RECOVERY_COD_CASHOUT_FK FOREIGN KEY ( COD_REFERENCE )
        REFERENCES RECEIVABLES_ADM.CASHOUT ( COD_CASHOUT ) ENABLE NOVALIDATE;

CREATE INDEX RECEIVABLES_ADM.RECOVERY_IDX01
        ON RECEIVABLES_ADM.RECOVERY ( IDT_SETTLEMENT ) INITRANS 36 TABLESPACE TSIRECEIVABLES01 ONLINE;
		
GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.RECOVERY TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.RECOVERY TO MANUT_RECEIVABLES;		
