CREATE TABLE RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL (
    IDT_CCE_REASSOCIATE_CONTROL NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
    COD_CCE_REASSOCIATE_CONTROL VARCHAR2(36 BYTE),
    NUM_PAGE                    NUMBER(10) NOT NULL,
    IND_STATUS                  VARCHAR2(40 BYTE) NOT NULL,
    DAT_CREATION                TIMESTAMP NOT NULL,
    DAT_UPDATE                  TIMESTAMP NOT NULL,
    DAT_SETTLE                  DATE NOT NULL,
	CONSTRAINT CCE_REASSOCIATE_CONTROL_PK PRIMARY KEY ( IDT_CCE_REASSOCIATE_CONTROL ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
)
PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_1 VALUES LESS THAN (TO_DATE('2020-10-10','YYYY-MM-DD'))
) TABLESPACE TSDRECEIVABLES01 INITRANS 32
;

COMMENT ON TABLE RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL IS 'Tabela que irá controlar a associção dos recebíveis com os efeitos de contrato';

COMMENT ON COLUMN RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL.idt_cce_reassociate_control IS '[NOT_SECURITY_APPLY] Identificador do único e sequencial da tabela';

COMMENT ON COLUMN RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL.cod_cce_reassociate_control IS '[NOT_SECURITY_APPLY] Código identificador único de controle';

COMMENT ON COLUMN RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL.num_page IS '[NOT_SECURITY_APPLY] Número da página';

COMMENT ON COLUMN RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL.ind_status IS '[NOT_SECURITY_APPLY] Identificador de status';

COMMENT ON COLUMN RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL.dat_creation IS '[NOT_SECURITY_APPLY] Data de criação';

COMMENT ON COLUMN RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL.dat_update IS '[NOT_SECURITY_APPLY] Data de atualização';

COMMENT ON COLUMN RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL.dat_settle IS '[NOT_SECURITY_APPLY] Data que foi liquidado o efeito de contrato';

CREATE INDEX RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL_IDX01 ON RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL
(DAT_SETTLE, COD_CCE_REASSOCIATE_CONTROL, IND_STATUS) LOCAL TABLESPACE TSIRECEIVABLES01 INITRANS 48 ONLINE;

GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL TO MANUT_RECEIVABLES;