CREATE TABLE RECEIVABLES_ADM.PAYMENT (
  IDT_PAYMENT NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
  COD_PAYMENT VARCHAR2(36 BYTE) NOT NULL ,
  NUM_TOTAL_AMOUNT NUMBER(11, 0) NOT NULL ,
  JSN_SELLER_FEE VARCHAR2(4000 BYTE) ,
  JSN_BUYER_FEE VARCHAR2(4000 BYTE) ,
  IND_CAPTURE_TYPE VARCHAR2(30 BYTE) ,
  NUM_SELLER_DOCUMENT VARCHAR2(15 BYTE) ,
  IND_PAYMENT_PROCESSOR VARCHAR2(30 BYTE), 
  IND_PAYMENT_METHOD VARCHAR2(30 BYTE) NOT NULL ,
  DAT_CREATION TIMESTAMP(6) NOT NULL ,
  DAT_UPDATE TIMESTAMP(6) NOT NULL ,
  COD_CUSTOMER_SELLER VARCHAR2(36 BYTE) NOT NULL ,
  COD_CUSTOMER_BUYER VARCHAR2(36 BYTE) ,
  IND_ACQUIRER VARCHAR2(50 BYTE) ,
  IND_ESCROW_TYPE VARCHAR2(30 BYTE) NOT NULL ,
  NUM_ESCROW_VALUE NUMBER(11, 0) NOT NULL ,
  COD_NSU VARCHAR2(50 BYTE) ,
  DAT_PAYMENT_CREATION TIMESTAMP(6) NOT NULL ,
  IND_PROCESS VARCHAR2(30 BYTE) NOT NULL ,
  IDT_PRIMARY_PAYMENT NUMBER(20, 0) ,
  NUM_VERSION NUMBER(10, 0) NOT NULL ,
	CONSTRAINT PAYMENT_PK PRIMARY KEY ( IDT_PAYMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48,
	CONSTRAINT JSN_SEL_FEE_PAYMENT_CK CHECK (JSN_SELLER_FEE IS JSON),
	CONSTRAINT JSN_BUY_FEE_PAYMENT_CK CHECK (JSN_BUYER_FEE IS JSON)
)
PARTITION BY RANGE(IDT_PAYMENT)
INTERVAL (2500000)
(PARTITION P_1 VALUES LESS THAN (2500000)
) TABLESPACE TSDRECEIVABLES01 INITRANS 32
;

COMMENT ON TABLE RECEIVABLES_ADM.PAYMENT IS 'Tabela que guardará dados do pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.IDT_PAYMENT IS '[NOT_SECURITY_APPLY] Identificador do pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.COD_PAYMENT IS '[NOT_SECURITY_APPLY] Código do pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.NUM_TOTAL_AMOUNT IS '[NOT_SECURITY_APPLY] Valor total do pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.JSN_SELLER_FEE IS '[NOT_SECURITY_APPLY] Valores  e tipos de taxas do vendedor';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.JSN_BUYER_FEE IS '[NOT_SECURITY_APPLY] Valores  e tipos de taxas do comprador';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.IND_CAPTURE_TYPE IS '[NOT_SECURITY_APPLY] Indicador do produto utilizado para capturar a transação. Ex.:
PRESENTIAL ou ONLINE';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.NUM_SELLER_DOCUMENT IS '[PII] Número do documento vendedor do PagSeguro';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.IND_PAYMENT_PROCESSOR IS '[NOT_SECURITY_APPLY] Indicador de bandeira. Ex.: MASTERCARD, VISA, HIPERCARD, ELO, AMEX, DINERS, BANRICOMPRAS E OTHERS';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.IND_PAYMENT_METHOD IS '[NOT_SECURITY_APPLY] Indicador de meio de pagamento. Ex.: BOLETO, BALANCE, CREDIT_CARD, DEBIT_CARD e VOUCHER';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data de atualização';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.COD_CUSTOMER_SELLER IS '[NOT_SECURITY_APPLY] Identificador do usuário vendedor do PagSeguro';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.COD_CUSTOMER_BUYER IS '[NOT_SECURITY_APPLY] Identificador do usuário comprador do PagSeguro';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.IND_ACQUIRER IS '[NOT_SECURITY_APPLY] Indicador do adquirente';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.IND_ESCROW_TYPE IS '[NOT_SECURITY_APPLY] Indicador de condições de pagamento para o cliente. Ex.: UNIQUE ou MULTIPLE';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.NUM_ESCROW_VALUE IS '[NOT_SECURITY_APPLY] Valor de condições de pagamento para o cliente';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.COD_NSU IS '[NOT_SECURITY_APPLY] Código único do uso da funcionalidade';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.DAT_PAYMENT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação do pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.IND_PROCESS IS '[NOT_SECURITY_APPLY] Status do processamento';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.IDT_PRIMARY_PAYMENT IS '[NOT_SECURITY_APPLY] IDT da transação primária';
COMMENT ON COLUMN RECEIVABLES_ADM.PAYMENT.NUM_VERSION IS '[NOT_SECURITY_APPLY] Número da versão';

ALTER TABLE RECEIVABLES_ADM.PAYMENT ADD CONSTRAINT PAYMENT_UK01 UNIQUE ( COD_PAYMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;

ALTER TABLE RECEIVABLES_ADM.PAYMENT ADD CONSTRAINT PAYMENT_IDT_PAYMENT_FK2 FOREIGN KEY (IDT_PRIMARY_PAYMENT) 
REFERENCES RECEIVABLES_ADM.PAYMENT (IDT_PAYMENT) ENABLE NOVALIDATE;

CREATE INDEX RECEIVABLES_ADM.PAYMENT_idx01 ON RECEIVABLES_ADM.PAYMENT ( IDT_PRIMARY_PAYMENT ) INITRANS 12 TABLESPACE TSIRECEIVABLES01 ONLINE;

GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.PAYMENT TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.PAYMENT TO MANUT_RECEIVABLES;