-- Add coluna de NUM_HOLDER_DOCUMENT para tabela
--  CONTRACTUAL_EFFECT

ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT ADD NUM_HOLDER_DOCUMENT VARCHAR2(15 BYTE);

COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.NUM_HOLDER_DOCUMENT IS '[PII] Numero do documento do titular.';
