-- Add coluna de IND_ESCROW_TYPE para tabela
--  CONTRACTUAL_EFFECT
-- TODO Essa coluna deve ser NOT NULL após a purga da base

ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT ADD IND_ESCROW_TYPE VARCHAR2(30 BYTE);

COMMENT ON COLUMN RECEIVABLES_ADM.CONTRACTUAL_EFFECT.IND_ESCROW_TYPE IS '[NOT_SECURITY_APPLY] Indicador de condições de pagamento. Ex.: UNIQUE ou MULTIPLE';

