ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT MODIFY NUM_HOLDER_DOCUMENT NOT NULL;
ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL MODIFY NUM_HOLDER_DOCUMENT NOT NULL;
ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL MODIFY NUM_HOLDER_DOCUMENT NOT NULL;
ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT MODIFY IND_ESCROW_TYPE NOT NULL;