ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_ANTICIPATION ADD NUM_VERSION NUMBER DEFAULT 1 NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_ANTICIPATION.NUM_VERSION IS '[NOT_SECURITY_APPLY] Numero da versão';