DECLARE
resource_busy EXCEPTION;
PRAGMA EXCEPTION_INIT(resource_busy, -00054);
naoexecutou BOOLEAN := TRUE;
VCOUNT NUMBER := 0;
C_ROLLBACK VARCHAR2(2000) := 'ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL DROP COLUMN NUM_HOLDER_DOCUMENT';
C_ROLLBACK1 VARCHAR2(2000) := 'ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL DROP COLUMN NUM_HOLDER_DOCUMENT';

C_SQL1 VARCHAR2(2000) := 'DROP INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL_IDX02';
C_SQL2 VARCHAR2(2000) := 'CREATE UNIQUE INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL_IDX02 ON RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL
                             (DAT_SETTLE ,
                              COD_CUSTOMER_RECEIVER,
                              IND_PAYMENT_GROUP,
                              IND_ESCROW_TYPE
                             )
                          LOCAL INITRANS 48 tablespace TSIRECEIVABLES01  online';
C_SQL3 VARCHAR2(2000) := 'DROP INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL_IDX01';
C_SQL4 VARCHAR2(2000) := 'CREATE INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL_IDX01 ON
                          RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL (DAT_SETTLE , COD_CUSTOMER_RECEIVER, IND_PAYMENT_GROUP
                          , IND_STATUS , IND_ESCROW_TYPE ) LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE';

C_SQL5 VARCHAR2(2000) := 'DROP INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL_IDX02';
C_SQL6 VARCHAR2(2000) := 'CREATE UNIQUE INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL_IDX02 ON RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL
                             (DAT_SETTLE ,
                              COD_CUSTOMER_RECEIVER,
                              IND_PAYMENT_GROUP    ,
                              IND_ESCROW_TYPE
                             )
                          LOCAL INITRANS 48 tablespace TSIRECEIVABLES01  online';
C_SQL7 VARCHAR2(2000) := 'DROP INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL_IDX01';
C_SQL8 VARCHAR2(2000) := 'CREATE INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL_IDX01 ON RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL
                          (DAT_SETTLE, COD_CUSTOMER_RECEIVER, IND_PAYMENT_GROUP, IND_STATUS, IND_ESCROW_TYPE)
                          LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE';
C_SQL9 VARCHAR2(2000) := 'ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL MODIFY COD_CUSTOMER_HOLDER NULL';
C_SQL10 VARCHAR2(2000) := 'ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL MODIFY COD_CUSTOMER_HOLDER NULL';
C_SQL11 VARCHAR2(2000) := 'ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL ADD NUM_HOLDER_DOCUMENT VARCHAR(36)';
C_SQL12 VARCHAR2(2000) := 'ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL ADD NUM_HOLDER_DOCUMENT VARCHAR(36)';
C_SQL13 VARCHAR2(2000) := 'COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_HOLDER_DOCUMENT IS ''Identificará o código do holder''';
C_SQL14 VARCHAR2(2000) := 'COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL.NUM_HOLDER_DOCUMENT IS ''Identificará o código do holder''';

BEGIN
    SELECT COUNT(1)
    INTO VCOUNT
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'RECEIVABLES_ADM'
      AND TABLE_NAME = 'RECEIVABLE_UNIT_EXTERNAL'
      AND COLUMN_NAME = 'NUM_HOLDER_DOCUMENT';
    IF VCOUNT = 0 THEN
        WHILE naoexecutou
            LOOP
                begin
                    EXECUTE IMMEDIATE C_SQL1;
                    EXECUTE IMMEDIATE C_SQL2;
                    EXECUTE IMMEDIATE C_SQL3;
                    EXECUTE IMMEDIATE C_SQL4;
                    EXECUTE IMMEDIATE C_SQL5;
                    EXECUTE IMMEDIATE C_SQL6;
                    EXECUTE IMMEDIATE C_SQL7;
                    EXECUTE IMMEDIATE C_SQL8;
                    EXECUTE IMMEDIATE C_SQL9;
                    EXECUTE IMMEDIATE C_SQL10;
                    EXECUTE IMMEDIATE C_SQL11;
                    EXECUTE IMMEDIATE C_SQL12;
                    EXECUTE IMMEDIATE C_SQL13;
                    EXECUTE IMMEDIATE C_SQL14;
                    naoexecutou := FALSE;
                    DBMS_OUTPUT.PUT_LINE('COLUNA CRIADA COM SUCESSO !');
                    DBMS_OUTPUT.PUT_LINE('SCRIPT ROLLBACK : ' || C_ROLLBACK);
                    COMMIT;
                EXCEPTION
                    WHEN resource_busy THEN
                        DBMS_SESSION.SLEEP(0.25);
                    WHEN OTHERS THEN
                        RAISE;
                END;
            END LOOP;
    ELSE
        DBMS_OUTPUT.PUT_LINE('*** Coluna existente: ' || sys_context('USERENV', 'INSTANCE_NAME') || ' / ' ||
                             sys_context('USERENV', 'SERVER_HOST'));
    END IF;
END;