ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL ADD COD_INTERMEDIARY VARCHAR2(36 BYTE) NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.COD_INTERMEDIARY IS '[NOT_SECURITY_APPLY] UUID do intermediador da unidade de recebivel';