CREATE TABLE RECEIVABLES_ADM.INSTALLMENT (
    IDT_INSTALLMENT      NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
    IDT_PAYMENT          NUMBER(20) NOT NULL,
    NUM_INSTALLMENT      NUMBER(2) NOT NULL,
    DAT_DUE              DATE NOT NULL,
    NUM_AMOUNT           NUMBER(11) NOT NULL,
    NUM_INSTALLMENT_FEE  NUMBER(11) NOT NULL,
	NUM_INSTALLMENT_BUYER_FEE NUMBER(11) NOT NULL,
	CONSTRAINT INSTALLMENT_pk PRIMARY KEY ( idt_INSTALLMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
) TABLESPACE TSDRECEIVABLES01 INITRANS 32;

COMMENT ON TABLE RECEIVABLES_ADM.INSTALLMENT IS 'Tabela que guardará dados das parcelas do pagamento';

COMMENT ON COLUMN RECEIVABLES_ADM.INSTALLMENT.idt_INSTALLMENT IS '[NOT_SECURITY_APPLY] Identificador da parcela do pagamento';

COMMENT ON COLUMN RECEIVABLES_ADM.INSTALLMENT.idt_payment IS '[NOT_SECURITY_APPLY] Identificador do pagamento';

COMMENT ON COLUMN RECEIVABLES_ADM.INSTALLMENT.num_INSTALLMENT IS '[NOT_SECURITY_APPLY] Numero da parcela';

COMMENT ON COLUMN RECEIVABLES_ADM.INSTALLMENT.dat_due IS '[NOT_SECURITY_APPLY] Data de vencimento';

COMMENT ON COLUMN RECEIVABLES_ADM.INSTALLMENT.num_amount IS '[NOT_SECURITY_APPLY] Valor da parcela';

COMMENT ON COLUMN RECEIVABLES_ADM.INSTALLMENT.num_INSTALLMENT_fee IS '[NOT_SECURITY_APPLY] Valor da taxa da parcela';

COMMENT ON COLUMN RECEIVABLES_ADM.INSTALLMENT.NUM_INSTALLMENT_BUYER_FEE IS '[NOT_SECURITY_APPLY] Valor da taxa de parcelamento paga pelo comprador';

CREATE INDEX RECEIVABLES_ADM.INSTALLMENT_idx01 ON RECEIVABLES_ADM.INSTALLMENT ( idt_payment ) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

ALTER TABLE RECEIVABLES_ADM.INSTALLMENT ADD CONSTRAINT INSTALLMENT_idt_payment_fk FOREIGN KEY ( idt_payment )
        REFERENCES RECEIVABLES_ADM.payment ( idt_payment ) ENABLE NOVALIDATE;
		
GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.INSTALLMENT TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.INSTALLMENT TO MANUT_RECEIVABLES;		