ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL ADD IDT_SELLER_SAFEPAY_USER NUMBER DEFAULT 1 NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL.IDT_SELLER_SAFEPAY_USER IS '[NOT_SECURITY_APPLY] IDT DO VENDEDOR LEGADO';