DELETE FROM RECEIVABLES_ADM.SUSPENSION_OUTBOX;
COMMIT;

ALTER TABLE RECEIVABLES_ADM.SUSPENSION_OUTBOX
ADD COD_OUTBOX_EVENT VARCHAR(36) NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_OUTBOX.COD_OUTBOX_EVENT IS '[NOT_SECURITY_APPLY] CODIGO IDENTIFICADOR DO EVENTO';

CREATE INDEX RECEIVABLES_ADM.SUSPENSION_OUTBOX_IDX03 ON RECEIVABLES_ADM.SUSPENSION_OUTBOX
( DAT_PARTITION, COD_OUTBOX_EVENT)
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;