DELETE FROM RECEIVABLES_ADM.RECEIVABLE_UNIT_OUTBOX;
COMMIT;

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_OUTBOX
ADD COD_OUTBOX_EVENT VARCHAR(36) NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_OUTBOX.COD_OUTBOX_EVENT IS '[NOT_SECURITY_APPLY] CODIGO IDENTIFICADOR DO EVENTO';

CREATE INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_OUTBOX_IDX04 ON RECEIVABLES_ADM.RECEIVABLE_UNIT_OUTBOX
( DAT_PARTITION, COD_OUTBOX_EVENT)
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;