ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL ADD NUM_INTERMEDIATED_AMOUNT NUMBER(11, 0) DEFAULT 0 NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.NUM_INTERMEDIATED_AMOUNT
IS '[NOT_SECURITY_APPLY] Valor intermediado';

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL ADD NUM_INTERMEDIATED_AMOUNT NUMBER(11, 0) DEFAULT 0 NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL.NUM_INTERMEDIATED_AMOUNT
IS '[NOT_SECURITY_APPLY] Valor intermediado';

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL ADD IND_INTERMEDIATED VARCHAR2(50 BYTE) DEFAULT 'FALSE' NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL.IND_INTERMEDIATED
IS '[NOT_SECURITY_APPLY] Indicador do status de intermediacao. Tipos: FALSE, TRUE, PARTIAL';

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL ADD IND_INTERMEDIATED VARCHAR2(50 BYTE) DEFAULT 'FALSE' NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL.IND_INTERMEDIATED
IS '[NOT_SECURITY_APPLY]  Indicador do status de intermediacao. Tipos: FALSE, TRUE, PARTIAL';