ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_INTERNAL ADD NUM_INTERMEDIATED_AMOUNT NUMBER(11, 0) DEFAULT 0 NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_INTERNAL.NUM_INTERMEDIATED_AMOUNT
IS '[NOT_SECURITY_APPLY] Valor intermediado';

ALTER TABLE RECEIVABLES_ADM.RECEIVABLE_EXTERNAL ADD NUM_INTERMEDIATED_AMOUNT NUMBER(11, 0) DEFAULT 0 NOT NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.RECEIVABLE_EXTERNAL.NUM_INTERMEDIATED_AMOUNT
IS '[NOT_SECURITY_APPLY] Valor intermediado';