CREATE INDEX RECEIVABLES_ADM.CASHOUT_IDX03 ON RECEIVABLES_ADM.CASHOUT (IDT_LEGACY_SAFEPAY_USER ) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX RECEIVABLES_ADM.PAYMENT_IDX03 ON RECEIVABLES_ADM.PAYMENT ( IND_PROCESS ) INITRANS 12 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX RECEIVABLES_ADM.RECEIVABLE_INTENT_IDX01 ON RECEIVABLES_ADM.RECEIVABLE_INTENT ( DAT_CREATION ) INITRANS 12 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX RECEIVABLES_ADM.LEGACY_IDX01 ON RECEIVABLES_ADM.LEGACY (IDT_TRANSACTION) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;