ALTER TABLE RECEIVABLES_ADM.CASHOUT ADD DAT_SETTLE DATE NULL;

COMMENT ON COLUMN RECEIVABLES_ADM.CASHOUT.DAT_SETTLE IS '[NOT_SECURITY_APPLY] Data de Liquidacao';

UPDATE RECEIVABLES_ADM.CASHOUT C
SET C.DAT_SETTLE = (SELECT L.DAT_SETTLE FROM RECEIVABLES_ADM.CONTRACTUAL_EFFECT L WHERE L.IDT_CONTRACTUAL_EFFECT = C.IDT_CONTRACTUAL_EFFECT);
COMMIT;

ALTER TABLE RECEIVABLES_ADM.CASHOUT MODIFY
PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P1 VALUES LESS THAN (TO_DATE('2020-01-10' ,'YYYY-MM-DD'))
)
ONLINE;