ALTER TABLE RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL ADD (JSN_PAYLOAD BLOB) LOB (JSN_PAYLOAD) STORE AS SECUREFILE (TABLESPACE TSLOBRECEIVABLES);

COMMENT ON COLUMN RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL.JSN_PAYLOAD IS '[NOT_SECURITY_APPLY] Payload enviado na reassociação de recebiveis';