DECLARE
resource_busy EXCEPTION;
PRAGMA EXCEPTION_INIT(resource_busy, -00054);
naoexecutou BOOLEAN := TRUE;
VCOUNT NUMBER := 0;
C_ROLLBACK VARCHAR2(2000) := 'ALTER TABLE RECEIVABLES_ADM.CCE_RECEIVABLE_EXTERNAL MODIFY IDT_CCE_RECEIVABLE  NUMBER(20, 0) GENERATED ALWAYS AS IDENTITY (MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE)';
C_SQL VARCHAR2(2000)      := 'ALTER TABLE RECEIVABLES_ADM.CCE_RECEIVABLE_EXTERNAL MODIFY IDT_CCE_RECEIVABLE  NUMBER(20, 0) GENERATED ALWAYS AS IDENTITY (MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER)';

BEGIN
    SELECT COUNT(1)
 
    INTO VCOUNT
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'RECEIVABLES_ADM'
      AND TABLE_NAME = 'CCE_RECEIVABLE_EXTERNAL'
      AND COLUMN_NAME = 'IDT_CCE_RECEIVABLE';
    IF VCOUNT = 1 THEN
        WHILE naoexecutou
            LOOP
                begin
                    EXECUTE IMMEDIATE C_SQL;
                    naoexecutou := FALSE;
                    DBMS_OUTPUT.PUT_LINE('COLUNA ALTERADA COM SUCESSO !');
                    DBMS_OUTPUT.PUT_LINE('SCRIPT ROLLBACK : ' || C_ROLLBACK);
                    COMMIT;
                EXCEPTION
                    WHEN resource_busy THEN
                        DBMS_SESSION.SLEEP(0.25);
                    WHEN OTHERS THEN
                        RAISE;
                END;
            END LOOP;
    ELSE
        DBMS_OUTPUT.PUT_LINE('*** Coluna inexistente: ' || sys_context('USERENV', 'INSTANCE_NAME') || ' / ' ||
                             sys_context('USERENV', 'SERVER_HOST'));
    END IF;
END;
/