CREATE INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL_IDX03 ON RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL (DAT_SETTLE , IND_STATUS ) 
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE PARALLEL 16;

ALTER INDEX RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL_IDX03 NOPARALLEL;