CREATE TABLE RECEIVABLES_ADM.SUSPENSION_HISTORY (
IDT_SUSPENSION_HISTORY NUMBER(20) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 1000 NOCYCLE NOORDER NOT NULL,
IDT_SUSPENSION NUMBER(20) NOT NULL,
DES_REASON VARCHAR2(60) NOT NULL,
NUM_ORDER NUMBER(2) NOT NULL,
NUM_CANCELED_AMOUNT NUMBER(11) NOT NULL,
NUM_SUSPENDED_AMOUNT NUMBER(11) NOT NULL,
DAT_CREATION TIMESTAMP NOT NULL,
DAT_UPDATE TIMESTAMP NOT NULL,
JSN_PAYLOAD VARCHAR2(4000) NOT NULL,
IDT_PAYMENT_SUSPENSION NUMBER(20) NOT NULL,
CONSTRAINT SUSPENSION_HISTORY_PK PRIMARY KEY (IDT_SUSPENSION_HISTORY ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48,
CONSTRAINT JSN_PAYLOAD_SUSP_HIST_CK CHECK ( JSN_PAYLOAD IS JSON )
) INITRANS 32 TABLESPACE TSDRECEIVABLES01
;

COMMENT ON TABLE RECEIVABLES_ADM.SUSPENSION_HISTORY IS 'Tabela relacionada a valores de suspensões de pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.IDT_SUSPENSION_HISTORY IS '[NOT_SECURITY_APPLY] Identificador da suspensão';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.IDT_SUSPENSION IS '[NOT_SECURITY_APPLY] Tabela relacionada a valores de suspensões de pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.DES_REASON IS '[NOT_SECURITY_APPLY] Campo para identificar a razão da suspensão do pagamento';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.NUM_ORDER IS '[NOT_SECURITY_APPLY] Ordem das suspensões';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.NUM_CANCELED_AMOUNT IS '[NOT_SECURITY_APPLY] Campo para identificar o valor cancelado';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.NUM_SUSPENDED_AMOUNT IS '[NOT_SECURITY_APPLY] Campo para identificar o valor suspenso';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data de atualização';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.JSN_PAYLOAD IS '[NOT_SECURITY_APPLY] Payload enviado em formato json';
COMMENT ON COLUMN RECEIVABLES_ADM.SUSPENSION_HISTORY.IDT_PAYMENT_SUSPENSION IS '[NOT_SECURITY_APPLY] Identificador para relacionamento com a tabela PAYMENT_SUSPENSION';

ALTER TABLE RECEIVABLES_ADM.SUSPENSION_HISTORY ADD CONSTRAINT SUSP_HIST_IDT_SUSPENSION_FK FOREIGN KEY ( IDT_SUSPENSION )
        REFERENCES RECEIVABLES_ADM.SUSPENSION ( IDT_SUSPENSION ) ENABLE NOVALIDATE;

CREATE INDEX RECEIVABLES_ADM.SUSPENSION_HIST_IDX02 ON RECEIVABLES_ADM.SUSPENSION_HISTORY ( IDT_SUSPENSION ) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;		

ALTER TABLE RECEIVABLES_ADM.SUSPENSION_HISTORY ADD CONSTRAINT SUSP_HIST_IDT_PAY_SUSPENSION_FK
        FOREIGN KEY ( IDT_PAYMENT_SUSPENSION )
        REFERENCES RECEIVABLES_ADM.PAYMENT_SUSPENSION ( IDT_PAYMENT_SUSPENSION ) ENABLE NOVALIDATE;

CREATE INDEX RECEIVABLES_ADM.SUSPENSION_HISTORY_IDX01 ON RECEIVABLES_ADM.SUSPENSION_HISTORY ( IDT_PAYMENT_SUSPENSION ) TABLESPACE TSIRECEIVABLES01 INITRANS 12 ONLINE;
		
GRANT SELECT,UPDATE,INSERT,DELETE ON RECEIVABLES_ADM.SUSPENSION_HISTORY TO RECEIVABLESUBR;
GRANT SELECT ON RECEIVABLES_ADM.SUSPENSION_HISTORY TO MANUT_RECEIVABLES;
