-- DROP CONSTRAINTS

ALTER TABLE AD.PAYMENT DROP CONSTRAINT PAYMENT_IDT_PAYMENT_FK2;
ALTER TABLE AD.PAYMENT DROP CONSTRAINT PAYMENT_IDT_LEGACY_FK;	
ALTER TABLE AD.PAYMENT_SUSPENSION DROP CONSTRAINT PAYMENT_SUSPENSION_IDT_PAYMENT_FK;	
ALTER TABLE AD.INSTALLMENT DROP CONSTRAINT INSTALLMENT_IDT_PAYMENT_FK;	
ALTER TABLE AD.RECEIVABLE_EXTERNAL DROP CONSTRAINT REC_EXT_IDT_PAYMENT_FK;
ALTER TABLE AD.RECEIVABLE_EXTERNAL DROP CONSTRAINT REC_EXT_IDT_REC_UNIT_EXT_FK;
ALTER TABLE AD.SUSPENSION DROP CONSTRAINT SUSP_IDT_PAYMENT_SUSPENSION_FK;
ALTER TABLE AD.SUSPENSION_HISTORY DROP CONSTRAINT SUSP_HIST_IDT_SUSPENSION_FK;
ALTER TABLE AD.SUSPENSION_HISTORY DROP CONSTRAINT SUSP_HIST_IDT_PAY_SUSPENSION_FK;
ALTER TABLE AD.RECEIVABLE_INTERNAL DROP CONSTRAINT REC_INT_IDT_PAYMENT_FK;
ALTER TABLE AD.RECEIVABLE_INTERNAL DROP CONSTRAINT REC_INT_IDT_REC_UNIT_INT_FK;
ALTER TABLE AD.CONTRACTUAL_EFFECT DROP CONSTRAINT CON_EFF_IDT_PAY_ADDR_FK;
ALTER TABLE AD.CONTRACTUAL_EFFECT DROP CONSTRAINT CON_EFF_IDT_REC_EXT_FK;
ALTER TABLE AD.CONTRACTUAL_EFFECT DROP CONSTRAINT CON_EFF_IDT_REC_INT_FK;
ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX DROP CONSTRAINT REC_OUT_IDT_REC_EXT_FK;
ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX DROP CONSTRAINT REC_OUT_IDT_REC_INT_FK;
ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION DROP CONSTRAINT REC_UNIT_ASS_REC_EXT_IDT_FK;
ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION DROP CONSTRAINT REC_UNIT_ASS_REC_INT_IDT_FK;
ALTER TABLE AD.CCE_STATIC_AMOUNT_SUMMARY DROP CONSTRAINT STA_SUM_IDT_CON_EFFE_FK;
ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT DROP CONSTRAINT SET_CON_EFFE_IDT_CON_EFFE_FK;
ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT DROP CONSTRAINT SET_CON_EFFE_IDT_SETTLEMENT_FK;
ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DROP CONSTRAINT CCE_REC_EXTER_IDT_CCE_FK;
ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DROP CONSTRAINT CCE_REC_EXTER_IDT_REC_EXTER_FK;
ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DROP CONSTRAINT CCE_REC_EXTER_IDT_SETT_FK;
ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DROP CONSTRAINT CCE_REC_INTER_IDT_CCE_FK;
ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DROP CONSTRAINT CCE_REC_INTER_IDT_REC_INTER_FK;
ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DROP CONSTRAINT CCE_REC_INTER_IDT_SETT_FK;
ALTER TABLE AD.CASHOUT DROP CONSTRAINT CASHOUT_IDT_CON_EFFE_FK;
ALTER TABLE AD.CASHOUT DROP CONSTRAINT CASHOUT_IDT_SETTLEMENT_FK;
ALTER TABLE AD.RECOVERY DROP CONSTRAINT RECOVERY_IDT_SETTLEMENT_FK;
ALTER TABLE AD.RECOVERY DROP CONSTRAINT RECOVERY_COD_CASHOUT_FK;
ALTER TABLE AD.REC_ANTICIPATION_INTENT DROP CONSTRAINT REC_ANT_INT_IDT_REC_ANT_FK;
ALTER TABLE AD.REC_ANTICIPATION_INTENT DROP CONSTRAINT REC_ANT_INT_REC_UNI_INT_FK;
ALTER TABLE AD.REC_ANTICIPATION_INTENT DROP CONSTRAINT REC_ANT_INT_REC_UNI_EXT_FK;
ALTER TABLE AD.SUSPENSION_OUTBOX DROP CONSTRAINT REC_OUT_IDT_SUSP_OUTBOX_FK;
ALTER TABLE AD.CCE_HISTORY DROP CONSTRAINT CCE_INT_HIST_IDT_PAY_ADDR_FK;
ALTER TABLE AD.CCE_HISTORY DROP CONSTRAINT CCE_INT_HIST_IDT_CON_EFF_FK;
ALTER TABLE AD.SETTLEMENT_CONTRACT_EVENT DROP CONSTRAINT SETTLEMENT_CONTRACT_EVENT_IDT_RECEIVABLE_UNIT_EXTERNAL_FK;



-- CREATE CONSTRAINTS

ALTER TABLE AD.PAYMENT ADD CONSTRAINT PAYMENT_IDT_PAYMENT_FK2 FOREIGN KEY (IDT_PRIMARY_PAYMENT)
      REFERENCES AD.PAYMENT (IDT_PAYMENT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECEIVABLE_EXTERNAL ADD CONSTRAINT REC_EXT_IDT_PAYMENT_FK FOREIGN KEY (IDT_PAYMENT)
      REFERENCES AD.PAYMENT (IDT_PAYMENT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.INSTALLMENT ADD CONSTRAINT INSTALLMENT_IDT_PAYMENT_FK FOREIGN KEY (IDT_PAYMENT)
      REFERENCES AD.PAYMENT (IDT_PAYMENT) ON DELETE CASCADE ENABLE NOVALIDATE;	  
  ALTER TABLE AD.PAYMENT_SUSPENSION ADD CONSTRAINT PAYMENT_SUSPENSION_IDT_PAYMENT_FK FOREIGN KEY (IDT_PAYMENT)
      REFERENCES AD.PAYMENT (IDT_PAYMENT) ON DELETE CASCADE ENABLE NOVALIDATE;	  
  ALTER TABLE AD.SUSPENSION ADD CONSTRAINT SUSP_IDT_PAYMENT_SUSPENSION_FK FOREIGN KEY (IDT_PAYMENT_SUSPENSION)
      REFERENCES AD.PAYMENT_SUSPENSION (IDT_PAYMENT_SUSPENSION) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.SUSPENSION_HISTORY ADD CONSTRAINT SUSP_HIST_IDT_SUSPENSION_FK FOREIGN KEY (IDT_SUSPENSION)
      REFERENCES AD.SUSPENSION (IDT_SUSPENSION) ON DELETE CASCADE ENABLE NOVALIDATE;	  
  ALTER TABLE AD.SUSPENSION_HISTORY ADD CONSTRAINT SUSP_HIST_IDT_PAY_SUSPENSION_FK FOREIGN KEY (IDT_PAYMENT_SUSPENSION)
      REFERENCES AD.PAYMENT_SUSPENSION (IDT_PAYMENT_SUSPENSION) ON DELETE CASCADE ENABLE NOVALIDATE;	 	  
  ALTER TABLE AD.RECEIVABLE_EXTERNAL ADD CONSTRAINT REC_EXT_IDT_REC_UNIT_EXT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT)
      REFERENCES AD.RECEIVABLE_UNIT_EXTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECEIVABLE_INTERNAL ADD CONSTRAINT REC_INT_IDT_PAYMENT_FK FOREIGN KEY (IDT_PAYMENT)
      REFERENCES AD.PAYMENT (IDT_PAYMENT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECEIVABLE_INTERNAL ADD CONSTRAINT REC_INT_IDT_REC_UNIT_INT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT)
      REFERENCES AD.RECEIVABLE_UNIT_INTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CONTRACTUAL_EFFECT ADD CONSTRAINT CON_EFF_IDT_PAY_ADDR_FK FOREIGN KEY (IDT_PAYMENT_ADDRESS)
      REFERENCES AD.PAYMENT_ADDRESS (IDT_PAYMENT_ADDRESS) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CONTRACTUAL_EFFECT ADD CONSTRAINT CON_EFF_IDT_REC_EXT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_EXTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_EXTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CONTRACTUAL_EFFECT ADD CONSTRAINT CON_EFF_IDT_REC_INT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_INTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_INTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX ADD CONSTRAINT REC_OUT_IDT_REC_EXT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_EXTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_EXTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX ADD CONSTRAINT REC_OUT_IDT_REC_INT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_INTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_INTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION ADD CONSTRAINT REC_UNIT_ASS_REC_EXT_IDT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_EXTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_EXTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION ADD CONSTRAINT REC_UNIT_ASS_REC_INT_IDT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_INTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_INTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CCE_STATIC_AMOUNT_SUMMARY ADD CONSTRAINT STA_SUM_IDT_CON_EFFE_FK FOREIGN KEY (IDT_CONTRACTUAL_EFFECT)
      REFERENCES AD.CONTRACTUAL_EFFECT (IDT_CONTRACTUAL_EFFECT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT ADD CONSTRAINT SET_CON_EFFE_IDT_CON_EFFE_FK FOREIGN KEY (IDT_CONTRACTUAL_EFFECT)
      REFERENCES AD.CONTRACTUAL_EFFECT (IDT_CONTRACTUAL_EFFECT) ON DELETE CASCADE ENABLE NOVALIDATE;	  
  ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT ADD CONSTRAINT SET_CON_EFFE_IDT_SETTLEMENT_FK FOREIGN KEY (IDT_SETTLEMENT)
      REFERENCES AD.SETTLEMENT (IDT_SETTLEMENT) ON DELETE CASCADE ENABLE NOVALIDATE;	  
  ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL ADD CONSTRAINT CCE_REC_EXTER_IDT_CCE_FK FOREIGN KEY (IDT_CONTRACTUAL_EFFECT)
      REFERENCES AD.CONTRACTUAL_EFFECT (IDT_CONTRACTUAL_EFFECT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL ADD CONSTRAINT CCE_REC_EXTER_IDT_REC_EXTER_FK FOREIGN KEY (IDT_RECEIVABLE)
      REFERENCES AD.RECEIVABLE_EXTERNAL (IDT_RECEIVABLE) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL ADD CONSTRAINT CCE_REC_EXTER_IDT_SETT_FK FOREIGN KEY (IDT_SETTLEMENT)
      REFERENCES AD.SETTLEMENT (IDT_SETTLEMENT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL ADD CONSTRAINT CCE_REC_INTER_IDT_CCE_FK FOREIGN KEY (IDT_CONTRACTUAL_EFFECT)
      REFERENCES AD.CONTRACTUAL_EFFECT (IDT_CONTRACTUAL_EFFECT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL ADD CONSTRAINT CCE_REC_INTER_IDT_REC_INTER_FK FOREIGN KEY (IDT_RECEIVABLE)
      REFERENCES AD.RECEIVABLE_INTERNAL (IDT_RECEIVABLE) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL ADD CONSTRAINT CCE_REC_INTER_IDT_SETT_FK FOREIGN KEY (IDT_SETTLEMENT)
      REFERENCES AD.SETTLEMENT (IDT_SETTLEMENT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CASHOUT ADD CONSTRAINT CASHOUT_IDT_CON_EFFE_FK FOREIGN KEY (IDT_CONTRACTUAL_EFFECT)
      REFERENCES AD.CONTRACTUAL_EFFECT (IDT_CONTRACTUAL_EFFECT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECOVERY ADD CONSTRAINT RECOVERY_IDT_SETTLEMENT_FK FOREIGN KEY (IDT_SETTLEMENT)
      REFERENCES AD.SETTLEMENT (IDT_SETTLEMENT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.RECOVERY ADD CONSTRAINT RECOVERY_COD_CASHOUT_FK FOREIGN KEY (COD_REFERENCE)
      REFERENCES AD.CASHOUT (COD_CASHOUT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.REC_ANTICIPATION_INTENT ADD CONSTRAINT REC_ANT_INT_IDT_REC_ANT_FK FOREIGN KEY (IDT_RECEIVABLE_ANTICIPATION)
      REFERENCES AD.RECEIVABLE_ANTICIPATION (IDT_RECEIVABLE_ANTICIPATION) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.REC_ANTICIPATION_INTENT ADD CONSTRAINT REC_ANT_INT_REC_UNI_INT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_INTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_INTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.REC_ANTICIPATION_INTENT ADD CONSTRAINT REC_ANT_INT_REC_UNI_EXT_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_EXTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_EXTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.SUSPENSION_OUTBOX ADD CONSTRAINT REC_OUT_IDT_SUSP_OUTBOX_FK FOREIGN KEY (IDT_PAYMENT_SUSPENSION)
      REFERENCES AD.PAYMENT_SUSPENSION (IDT_PAYMENT_SUSPENSION) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CASHOUT ADD CONSTRAINT CASHOUT_IDT_SETTLEMENT_FK FOREIGN KEY (IDT_SETTLEMENT)
      REFERENCES AD.SETTLEMENT (IDT_SETTLEMENT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.PAYMENT ADD CONSTRAINT PAYMENT_IDT_LEGACY_FK FOREIGN KEY (IDT_LEGACY)
      REFERENCES AD.LEGACY (IDT_LEGACY) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.SETTLEMENT_CONTRACT_EVENT ADD CONSTRAINT SETTLEMENT_CONTRACT_EVENT_IDT_RECEIVABLE_UNIT_EXTERNAL_FK FOREIGN KEY (IDT_RECEIVABLE_UNIT_EXTERNAL)
      REFERENCES AD.RECEIVABLE_UNIT_EXTERNAL (IDT_RECEIVABLE_UNIT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CCE_HISTORY ADD CONSTRAINT CCE_INT_HIST_IDT_CON_EFF_FK FOREIGN KEY (IDT_CONTRACTUAL_EFFECT)
      REFERENCES AD.CONTRACTUAL_EFFECT (IDT_CONTRACTUAL_EFFECT) ON DELETE CASCADE ENABLE NOVALIDATE;
  ALTER TABLE AD.CCE_HISTORY ADD CONSTRAINT CCE_INT_HIST_IDT_PAY_ADDR_FK FOREIGN KEY (IDT_PAYMENT_ADDRESS)
      REFERENCES AD.PAYMENT_ADDRESS (IDT_PAYMENT_ADDRESS) ON DELETE CASCADE ENABLE NOVALIDATE;