--Prompt => sqlplus AD/rec1adqa@PDBRECEIVABLES.QA.BD.INTRANET.PAGS:1521/PDBRECEIVABLES
-- @C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\carga_receivable_unit_ad.sql


@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_0__DROP_TRUNCATE.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_1__RECEIVABLE_INTENT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_2__CCE_REASSOCIATE_CONTROL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_3__PAYMENT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_4__INSTALLMENT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_5__LEGACY.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_6__PAYMENT_SUSPENSION.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_7__SUSPENSION.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_8__SUSPENSION_HISTORY.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_9__RECEIVABLE_UNIT_EXTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_10__RECEIVABLE_UNIT_INTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_11__RECEIVABLE_EXTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_12__RECEIVABLE_INTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_13__PAYMENT_ADDRESS.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_14__CONTRACTUAL_EFFECT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_15__RECEIVABLE_UNIT_OUTBOX.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_16__RECEIVABLE_UNIT_ASSOCIATION.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_17__CCE_STATIC_AMOUNT_SUMMARY.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_18__SETTLEMENT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_19__SETTLEMENT_CONTRACTUAL_EFFECT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_20__CCE_RECEIVABLE_EXTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_21__CCE_RECEIVABLE_INTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_22__CASHOUT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_23__RECOVERY.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_24__RECEIVABLE_ANTICIPATION.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_25__REC_ANTICIPATION_INTENT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_26__SUSPENSION_OUTBOX.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_27__SETTLEMENT_CONTRACTUAL_EFFECT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_28__RECEIVABLE_UNIT_INTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_29__RECEIVABLE_UNIT_EXTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_30__DROP_CONSTRAINT_CONTRACTUAL_EFFECT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_31__ALTER_TABLE_RECEIVABLE_UNIT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_32__ADD_NUM_RECOVERED_AMOUNT_TO_RECEIVABLES.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_33__ADD_HOLDER_DOCUMENT_TO_CONTRACTUAL_EFFECT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_34__CHANGE_RECEIVABLE_UNIT_HOLDER_DOCUMENT_COMMENT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_35__DROP_UNIQUE_PAYMENT_SUSPENSION_CONSTRAINT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_36__ADD_NUM_VERSION_TO_RECEIVABLE_ANTICIPATION.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_37__ADD_ESCROW_TYPE_TO_CONTRACTUAL_EFFECT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_38__ALTER_UR_CONTRACTUAL_EFFECT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_39__ALTER_UR_CONTRACTUAL_EFFECT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_40__ADD_SELLER_SAFEPAY_USER_EXTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_41__ADD_IDT_SETTLEMENT_TO_CASHOUT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_42__ADD_INDEX_FOR_FK_IN_CASHOUT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_43__ADD_IDT_RECEIVER_SAFEPAY_USER_EXTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_44__ADD_IDENTIFIERS_CASHOUT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_45__ADD_EVENT_CODE_RECEIVABLE_UNIT_OUTBOX.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_46__ADD_EVENT_CODE_SUSPENSION_OUTBOX.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_47__ALTER_LEGACY_RELATIONSHIP.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_48__ADD_COD_INTERMEDIARY_TO_RUI.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_49__RENAME_COD_INTERMEDIARY_TO_COD_CUSTOMER_INTERMEDIARY_RUI.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_50__ALTER_DAT_CREATION_DEFAULT_OUTBOX.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_51__ADD_FLG_PARTIAL_OWNERSHIP_CHANGE.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_52__ADD_NUM_INTERMEDIATED_AMOUNT_IND_INTERMEDIATED.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_53__ADD_NUM_INTERMEDIATED_AMOUNT.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_54__ADD_IND_SETTLEMENT_ACQUIRER_TO_RECEIVABLE_UNIT_INTERNAL_EXTERNAL.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_97__ALTER_TABLES_FKS_DISABLE.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_98__INSERT_TABLES_AD.sql
@C:\Sammy\queries\0_Times\1_Miami\Receivable_Unit\migration_ad\V1_99__ALTER_TABLES_FKS_ENABLE.sql

