ALTER TABLE RECEIVABLES_ADM.CONTRACTUAL_EFFECT ADD CONSTRAINT CON_EFF_IDT_REC_UNIT_NULL_CK CHECK (
      (IDT_RECEIVABLE_UNIT_EXTERNAL IS NOT NULL) OR
      (IDT_RECEIVABLE_UNIT_INTERNAL IS NOT NULL)) ENABLE NOVALIDATE;