ALTER TABLE "RECEIVABLES_ADM"."PAYMENT" ADD CONSTRAINT "PAYMENT_IDT_PAYMENT_FK2" FOREIGN KEY ("IDT_PRIMARY_PAYMENT")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT" ("IDT_PAYMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."INSTALLMENT" ADD CONSTRAINT "INSTALLMENT_IDT_PAYMENT_FK" FOREIGN KEY ("IDT_PAYMENT")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT" ("IDT_PAYMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."PAYMENT_SUSPENSION" ADD CONSTRAINT "PAYMENT_SUSPENSION_IDT_PAYMENT_FK" FOREIGN KEY ("IDT_PAYMENT")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT" ("IDT_PAYMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."SUSPENSION" ADD CONSTRAINT "SUSP_IDT_PAYMENT_SUSPENSION_FK" FOREIGN KEY ("IDT_PAYMENT_SUSPENSION")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT_SUSPENSION" ("IDT_PAYMENT_SUSPENSION") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."SUSPENSION_HISTORY" ADD CONSTRAINT "SUSP_HIST_IDT_SUSPENSION_FK" FOREIGN KEY ("IDT_SUSPENSION")
      REFERENCES "RECEIVABLES_ADM"."SUSPENSION" ("IDT_SUSPENSION") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."SUSPENSION_HISTORY" ADD CONSTRAINT "SUSP_HIST_IDT_PAY_SUSPENSION_FK" FOREIGN KEY ("IDT_PAYMENT_SUSPENSION")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT_SUSPENSION" ("IDT_PAYMENT_SUSPENSION") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECEIVABLE_EXTERNAL" ADD CONSTRAINT "REC_EXT_IDT_PAYMENT_FK" FOREIGN KEY ("IDT_PAYMENT")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT" ("IDT_PAYMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECEIVABLE_EXTERNAL" ADD CONSTRAINT "REC_EXT_IDT_REC_UNIT_EXT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_EXTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECEIVABLE_INTERNAL" ADD CONSTRAINT "REC_INT_IDT_PAYMENT_FK" FOREIGN KEY ("IDT_PAYMENT")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT" ("IDT_PAYMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECEIVABLE_INTERNAL" ADD CONSTRAINT "REC_INT_IDT_REC_UNIT_INT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_INTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ADD CONSTRAINT "CON_EFF_IDT_PAY_ADDR_FK" FOREIGN KEY ("IDT_PAYMENT_ADDRESS")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT_ADDRESS" ("IDT_PAYMENT_ADDRESS") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ADD CONSTRAINT "CON_EFF_IDT_REC_EXT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_EXTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_EXTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ADD CONSTRAINT "CON_EFF_IDT_REC_INT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_INTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_INTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECEIVABLE_UNIT_OUTBOX" ADD CONSTRAINT "REC_OUT_IDT_REC_EXT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_EXTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_EXTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECEIVABLE_UNIT_OUTBOX" ADD CONSTRAINT "REC_OUT_IDT_REC_INT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_INTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_INTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECEIVABLE_UNIT_ASSOCIATION" ADD CONSTRAINT "REC_UNIT_ASS_REC_EXT_IDT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_EXTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_EXTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECEIVABLE_UNIT_ASSOCIATION" ADD CONSTRAINT "REC_UNIT_ASS_REC_INT_IDT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_INTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_INTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_STATIC_AMOUNT_SUMMARY" ADD CONSTRAINT "STA_SUM_IDT_CON_EFFE_FK" FOREIGN KEY ("IDT_CONTRACTUAL_EFFECT")
      REFERENCES "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ("IDT_CONTRACTUAL_EFFECT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."SETTLEMENT_CONTRACTUAL_EFFECT" ADD CONSTRAINT "SET_CON_EFFE_IDT_CON_EFFE_FK" FOREIGN KEY ("IDT_CONTRACTUAL_EFFECT")
      REFERENCES "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ("IDT_CONTRACTUAL_EFFECT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."SETTLEMENT_CONTRACTUAL_EFFECT" ADD CONSTRAINT "SET_CON_EFFE_IDT_SETTLEMENT_FK" FOREIGN KEY ("IDT_SETTLEMENT")
      REFERENCES "RECEIVABLES_ADM"."SETTLEMENT" ("IDT_SETTLEMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_RECEIVABLE_EXTERNAL" ADD CONSTRAINT "CCE_REC_EXTER_IDT_CCE_FK" FOREIGN KEY ("IDT_CONTRACTUAL_EFFECT")
      REFERENCES "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ("IDT_CONTRACTUAL_EFFECT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_RECEIVABLE_EXTERNAL" ADD CONSTRAINT "CCE_REC_EXTER_IDT_REC_EXTER_FK" FOREIGN KEY ("IDT_RECEIVABLE")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_EXTERNAL" ("IDT_RECEIVABLE") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_RECEIVABLE_EXTERNAL" ADD CONSTRAINT "CCE_REC_EXTER_IDT_SETT_FK" FOREIGN KEY ("IDT_SETTLEMENT")
      REFERENCES "RECEIVABLES_ADM"."SETTLEMENT" ("IDT_SETTLEMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_RECEIVABLE_INTERNAL" ADD CONSTRAINT "CCE_REC_INTER_IDT_CCE_FK" FOREIGN KEY ("IDT_CONTRACTUAL_EFFECT")
      REFERENCES "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ("IDT_CONTRACTUAL_EFFECT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_RECEIVABLE_INTERNAL" ADD CONSTRAINT "CCE_REC_INTER_IDT_REC_INTER_FK" FOREIGN KEY ("IDT_RECEIVABLE")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_INTERNAL" ("IDT_RECEIVABLE") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_RECEIVABLE_INTERNAL" ADD CONSTRAINT "CCE_REC_INTER_IDT_SETT_FK" FOREIGN KEY ("IDT_SETTLEMENT")
      REFERENCES "RECEIVABLES_ADM"."SETTLEMENT" ("IDT_SETTLEMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CASHOUT" ADD CONSTRAINT "CASHOUT_IDT_CON_EFFE_FK" FOREIGN KEY ("IDT_CONTRACTUAL_EFFECT")
      REFERENCES "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ("IDT_CONTRACTUAL_EFFECT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECOVERY" ADD CONSTRAINT "RECOVERY_IDT_SETTLEMENT_FK" FOREIGN KEY ("IDT_SETTLEMENT")
      REFERENCES "RECEIVABLES_ADM"."SETTLEMENT" ("IDT_SETTLEMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."RECOVERY" ADD CONSTRAINT "RECOVERY_COD_CASHOUT_FK" FOREIGN KEY ("COD_REFERENCE")
      REFERENCES "RECEIVABLES_ADM"."CASHOUT" ("COD_CASHOUT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."REC_ANTICIPATION_INTENT" ADD CONSTRAINT "REC_ANT_INT_IDT_REC_ANT_FK" FOREIGN KEY ("IDT_RECEIVABLE_ANTICIPATION")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_ANTICIPATION" ("IDT_RECEIVABLE_ANTICIPATION") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."REC_ANTICIPATION_INTENT" ADD CONSTRAINT "REC_ANT_INT_REC_UNI_INT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_INTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_INTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."REC_ANTICIPATION_INTENT" ADD CONSTRAINT "REC_ANT_INT_REC_UNI_EXT_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_EXTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_EXTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."SUSPENSION_OUTBOX" ADD CONSTRAINT "REC_OUT_IDT_SUSP_OUTBOX_FK" FOREIGN KEY ("IDT_PAYMENT_SUSPENSION")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT_SUSPENSION" ("IDT_PAYMENT_SUSPENSION") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CASHOUT" ADD CONSTRAINT "CASHOUT_IDT_SETTLEMENT_FK" FOREIGN KEY ("IDT_SETTLEMENT")
      REFERENCES "RECEIVABLES_ADM"."SETTLEMENT" ("IDT_SETTLEMENT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."PAYMENT" ADD CONSTRAINT "PAYMENT_IDT_LEGACY_FK" FOREIGN KEY ("IDT_LEGACY")
      REFERENCES "RECEIVABLES_ADM"."LEGACY" ("IDT_LEGACY") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."SETTLEMENT_CONTRACT_EVENT" ADD CONSTRAINT "SETTLEMENT_CONTRACT_EVENT_IDT_RECEIVABLE_UNIT_EXTERNAL_FK" FOREIGN KEY ("IDT_RECEIVABLE_UNIT_EXTERNAL")
      REFERENCES "RECEIVABLES_ADM"."RECEIVABLE_UNIT_EXTERNAL" ("IDT_RECEIVABLE_UNIT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_HISTORY" ADD CONSTRAINT "CCE_INT_HIST_IDT_CON_EFF_FK" FOREIGN KEY ("IDT_CONTRACTUAL_EFFECT")
      REFERENCES "RECEIVABLES_ADM"."CONTRACTUAL_EFFECT" ("IDT_CONTRACTUAL_EFFECT") ENABLE NOVALIDATE;
  ALTER TABLE "RECEIVABLES_ADM"."CCE_HISTORY" ADD CONSTRAINT "CCE_INT_HIST_IDT_PAY_ADDR_FK" FOREIGN KEY ("IDT_PAYMENT_ADDRESS")
      REFERENCES "RECEIVABLES_ADM"."PAYMENT_ADDRESS" ("IDT_PAYMENT_ADDRESS") ENABLE NOVALIDATE;