-- DROP
DROP TABLE AD.REC_ANTICIPATION_INTENT CASCADE CONSTRAINTS;
DROP TABLE AD.RECEIVABLE_ANTICIPATION CASCADE CONSTRAINTS;
DROP TABLE AD.RECOVERY CASCADE CONSTRAINTS;
DROP TABLE AD.CASHOUT CASCADE CONSTRAINTS;
DROP TABLE AD.CCE_RECEIVABLE_INTERNAL CASCADE CONSTRAINTS;
DROP TABLE AD.CCE_RECEIVABLE_EXTERNAL CASCADE CONSTRAINTS;
DROP TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT CASCADE CONSTRAINTS;
DROP TABLE AD.SETTLEMENT CASCADE CONSTRAINTS;
DROP TABLE AD.CCE_STATIC_AMOUNT_SUMMARY CASCADE CONSTRAINTS;
DROP TABLE AD.CONTRACTUAL_EFFECT CASCADE CONSTRAINTS;
DROP TABLE AD.PAYMENT_ADDRESS CASCADE CONSTRAINTS;
DROP TABLE AD.RECEIVABLE_INTERNAL CASCADE CONSTRAINTS;
DROP TABLE AD.RECEIVABLE_EXTERNAL CASCADE CONSTRAINTS;
DROP TABLE AD.RECEIVABLE_UNIT_OUTBOX CASCADE CONSTRAINTS;
DROP TABLE AD.RECEIVABLE_UNIT_ASSOCIATION CASCADE CONSTRAINTS;
DROP TABLE AD.RECEIVABLE_UNIT_INTERNAL CASCADE CONSTRAINTS;
DROP TABLE AD.RECEIVABLE_UNIT_EXTERNAL CASCADE CONSTRAINTS;
DROP TABLE AD.SUSPENSION_OUTBOX CASCADE CONSTRAINTS;
DROP TABLE AD.SUSPENSION_HISTORY CASCADE CONSTRAINTS;
DROP TABLE AD.SUSPENSION CASCADE CONSTRAINTS;
DROP TABLE AD.LEGACY CASCADE CONSTRAINTS;
DROP TABLE AD.INSTALLMENT CASCADE CONSTRAINTS;
DROP TABLE AD.PAYMENT_SUSPENSION CASCADE CONSTRAINTS;
DROP TABLE AD.PAYMENT CASCADE CONSTRAINTS;
DROP TABLE AD.RECEIVABLE_INTENT CASCADE CONSTRAINTS;
DROP TABLE AD.CCE_REASSOCIATE_CONTROL CASCADE CONSTRAINTS;
DROP TABLE AD.CCE_INTERNAL_HISTORY CASCADE CONSTRAINTS;

-- TRUNCATE
/*
TRUNCATE TABLE AD.REC_ANTICIPATION_INTENT;
TRUNCATE TABLE AD.RECEIVABLE_ANTICIPATION;
TRUNCATE TABLE AD.RECOVERY;
TRUNCATE TABLE AD.CASHOUT;
TRUNCATE TABLE AD.CCE_RECEIVABLE_INTERNAL;
TRUNCATE TABLE AD.CCE_RECEIVABLE_EXTERNAL;
TRUNCATE TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT;
TRUNCATE TABLE AD.SETTLEMENT;
TRUNCATE TABLE AD.CCE_STATIC_AMOUNT_SUMMARY;
TRUNCATE TABLE AD.CONTRACTUAL_EFFECT;
TRUNCATE TABLE AD.PAYMENT_ADDRESS;
TRUNCATE TABLE AD.RECEIVABLE_INTERNAL;
TRUNCATE TABLE AD.RECEIVABLE_EXTERNAL;
TRUNCATE TABLE AD.RECEIVABLE_UNIT_OUTBOX;
TRUNCATE TABLE AD.RECEIVABLE_UNIT_ASSOCIATION;
TRUNCATE TABLE AD.RECEIVABLE_UNIT_INTERNAL;
TRUNCATE TABLE AD.RECEIVABLE_UNIT_EXTERNAL;
TRUNCATE TABLE AD.SUSPENSION_OUTBOX;
TRUNCATE TABLE AD.SUSPENSION_HISTORY;
TRUNCATE TABLE AD.SUSPENSION;
TRUNCATE TABLE AD.LEGACY;
TRUNCATE TABLE AD.INSTALLMENT;
TRUNCATE TABLE AD.PAYMENT_SUSPENSION;
TRUNCATE TABLE AD.PAYMENT;
TRUNCATE TABLE AD.RECEIVABLE_INTENT;
TRUNCATE TABLE AD.CCE_REASSOCIATE_CONTROL;
TRUNCATE TABLE AD.CCE_INTERNAL_HISTORY;
*/


