CREATE TABLE AD.PAYMENT_ADDRESS (
    IDT_PAYMENT_ADDRESS NUMBER(20)  NOT NULL,
    IND_TYPE            VARCHAR2(20 BYTE),
    COD_ISPB            VARCHAR2(30 BYTE),
    IND_PERSON_TYPE     VARCHAR2(20 BYTE),
    IND_ACCOUNT_TYPE    VARCHAR2(20 BYTE),
    NUM_BRANCH          VARCHAR2(5 BYTE),
    NUM_ACCOUNT         VARCHAR2(10 BYTE),
    NAM_NAME            VARCHAR2(120 BYTE),
    NUM_DOCUMENT        VARCHAR2(15 BYTE),
	COD_CUSTOMER 		VARCHAR2(36 BYTE),
	CONSTRAINT PAYMENT_ADDRESS_PK PRIMARY KEY ( IDT_PAYMENT_ADDRESS ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
) INITRANS 32
TABLESPACE TSDRECEIVABLES01;

COMMENT ON TABLE AD.PAYMENT_ADDRESS IS 'Tabela que guardará dados do cliente da unidade de recebível';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.idt_payment_ADDRESS IS '[NOT_SECURITY_APPLY] Identificador do cliente';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.ind_type IS '[NOT_SECURITY_APPLY] Indicador de Tipo da conta do cliente. Ex.: BANK , PAGBANK, BALANCE';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.cod_ispb IS '[NOT_SECURITY_APPLY] Código Identificador de ISPB';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.ind_person_type IS '[NOT_SECURITY_APPLY] Indicador do Tipo de Pessoa. Ex.: PERSONAL, ENTERPRISE';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.ind_account_type IS '[NOT_SECURITY_APPLY] Indicador do Tipo de Conta. Ex.: CHECKING, SAVING, PAYMENT';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.num_branch IS '[PCI-DSS] Número da agência';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.num_account IS '[PCI-DSS] Código da conta';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.nam_name IS '[PII] Nome do cliente';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.num_document IS '[PII] Documento do cliente';

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.COD_CUSTOMER IS '[NOT_SECURITY_APPLY] Codigo identificador do recebedor da conta a ser liquidada';

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.PAYMENT_ADDRESS TO RECEIVABLESUBR;
GRANT SELECT ON AD.PAYMENT_ADDRESS TO MANUT_RECEIVABLES;