CREATE TABLE AD.RECEIVABLE_INTENT (
IDT_RECEIVABLE_INTENT NUMBER(20)  NOT NULL,
COD_PAYMENT         VARCHAR2(36 BYTE) NOT NULL,
JSN_PAYLOAD         VARCHAR2(4000 BYTE) NOT NULL,
DAT_CREATION        TIMESTAMP NOT NULL,
DAT_SENT            TIMESTAMP,
CONSTRAINT RECEIVABLE_INTENT_PK PRIMARY KEY ( IDT_RECEIVABLE_INTENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
) INITRANS 32 TABLESPACE TSDRECEIVABLES01;

COMMENT ON TABLE AD.RECEIVABLE_INTENT IS 'Tabela que guardará dados referente os recebíveis com intenções de pagamento';
COMMENT ON COLUMN AD.RECEIVABLE_INTENT.IDT_RECEIVABLE_INTENT IS '[NOT_SECURITY_APPLY] Identificador da intenção do recebível';
COMMENT ON COLUMN AD.RECEIVABLE_INTENT.COD_PAYMENT IS '[NOT_SECURITY_APPLY] Código do pagamento';
COMMENT ON COLUMN AD.RECEIVABLE_INTENT.JSN_PAYLOAD IS '[NOT_SECURITY_APPLY] Payload enviado na requisição';
COMMENT ON COLUMN AD.RECEIVABLE_INTENT.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação do registro na tabela';
COMMENT ON COLUMN AD.RECEIVABLE_INTENT.DAT_SENT IS '[NOT_SECURITY_APPLY] Data que foi enviado o registro para a fila';

ALTER TABLE AD.RECEIVABLE_INTENT ADD CONSTRAINT RECEIVABLE_INTENT_UK01 UNIQUE ( COD_PAYMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.RECEIVABLE_INTENT TO RECEIVABLESUBR;
GRANT SELECT ON AD.RECEIVABLE_INTENT TO MANUT_RECEIVABLES;