CREATE TABLE AD.SETTLEMENT (
    IDT_SETTLEMENT      NUMBER(20)  NOT NULL,
    COD_SETTLEMENT      VARCHAR2(36 BYTE) NOT NULL,
    DAT_CREATION        TIMESTAMP NOT NULL,
    CONSTRAINT SETTLEMENT_PK PRIMARY KEY ( IDT_SETTLEMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
) INITRANS 32
TABLESPACE TSDRECEIVABLES01;

COMMENT ON TABLE AD.SETTLEMENT IS 'Tabela para controle do processo de liquidação';

COMMENT ON COLUMN AD.SETTLEMENT.IDT_SETTLEMENT IS '[NOT_SECURITY_APPLY] Identificador da entidade';

COMMENT ON COLUMN AD.SETTLEMENT.COD_SETTLEMENT IS '[NOT_SECURITY_APPLY] Código de identificação da SETTLEMENT';

COMMENT ON COLUMN AD.SETTLEMENT.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';

-- Unique
ALTER TABLE AD.SETTLEMENT ADD CONSTRAINT SETTLEMENT_UK01 UNIQUE ( COD_SETTLEMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;

-- Grants
GRANT SELECT,UPDATE,INSERT,DELETE ON AD.SETTLEMENT TO RECEIVABLESUBR;
GRANT SELECT ON AD.SETTLEMENT TO MANUT_RECEIVABLES;