CREATE TABLE AD.SUSPENSION_OUTBOX (
    IDT_SUSPENSION_OUTBOX      NUMBER(20)  NOT NULL,
    IDT_PAYMENT_SUSPENSION    NUMBER(20)            NOT NULL,
    DAT_PARTITION                   DATE            NOT NULL,
    DAT_CREATION                    TIMESTAMP       NOT NULL,
    COD_CUSTOMER                    VARCHAR2(36)    NOT NULL,
    IND_STATUS                      CHAR(1)         NOT NULL,
    NUM_TOPIC_OFFSET                NUMBER(20),
    JSN_METADATA                    BLOB            NOT NULL,
    CONSTRAINT SUSPENSION_OUTBOX_PK PRIMARY KEY ( IDT_SUSPENSION_OUTBOX ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
)
LOB (JSN_METADATA) STORE as SECUREFILE
PARTITION BY
RANGE(DAT_PARTITION)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_1 VALUES LESS THAN (TO_DATE('2020-10-16','YYYY-MM-DD'))
) TABLESPACE TSLOBRECEIVABLES INITRANS 32
;

COMMENT ON TABLE AD.SUSPENSION_OUTBOX IS
    'Tabela de outbox de suspenções para replicar no kafka';

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.IDT_SUSPENSION_OUTBOX IS
    '[NOT_SECURITY_APPLY] Identificador unico e sequencial da tabela';

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.IDT_PAYMENT_SUSPENSION IS
    '[NOT_SECURITY_APPLY] Identificador do registor da suspenção';

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.dat_partition IS
    '[NOT_SECURITY_APPLY] Dia da criacao do registro usado para particionar a tabela';

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.dat_creation IS
    '[NOT_SECURITY_APPLY] Data e hora da criacao do registro na tabela';

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.cod_customer IS
    '[NOT_SECURITY_APPLY] Codigo identificador unico do customer que sera usado como chave de particao no kafka';

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.ind_status IS
    '[NOT_SECURITY_APPLY] Status do envio do registro ao kafka, W - waiting, S - sent, E - error';

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.num_topic_offset IS
    '[NOT_SECURITY_APPLY] Offset corrente da mensagem no topico';

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.jsn_metadata IS
    '[NOT_SECURITY_APPLY] Binario do conteudo da mensagem a ser postado no kafka';

CREATE INDEX AD.SUSPENSION_OUTBOX_IDX01 ON AD.SUSPENSION_OUTBOX
(IND_STATUS) TABLESPACE TSIRECEIVABLES01 INITRANS 48 ONLINE;

ALTER TABLE AD.SUSPENSION_OUTBOX ADD CONSTRAINT REC_OUT_IDT_SUSP_OUTBOX_FK FOREIGN KEY ( IDT_PAYMENT_SUSPENSION )
REFERENCES AD.PAYMENT_SUSPENSION ( IDT_PAYMENT_SUSPENSION ) ENABLE NOVALIDATE;

CREATE INDEX AD.SUSPENSION_OUTBOX_IDX02 ON AD.SUSPENSION_OUTBOX
(IDT_PAYMENT_SUSPENSION) TABLESPACE TSIRECEIVABLES01 INITRANS 48 ONLINE;

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.SUSPENSION_OUTBOX TO RECEIVABLESUBR;
GRANT SELECT ON AD.SUSPENSION_OUTBOX TO MANUT_RECEIVABLES;