CREATE TABLE AD.CASHOUT (
    IDT_CASHOUT                 NUMBER(20)  NOT NULL,
    IDT_CONTRACTUAL_EFFECT      NUMBER(20) NOT NULL,
    COD_CASHOUT                 VARCHAR2(36 BYTE) NOT NULL,
    NUM_AMOUNT                  NUMBER(11) NOT NULL,
    IND_STATUS                  VARCHAR2(50 BYTE) NOT NULL,
    DAT_CASHOUT_CONFIRMATION    TIMESTAMP NULL,
    DAT_CREATION                TIMESTAMP NOT NULL,
    DAT_UPDATE                  TIMESTAMP NOT NULL,
    CONSTRAINT CASHOUT_PK PRIMARY KEY ( IDT_CASHOUT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
) TABLESPACE TSDRECEIVABLES01 INITRANS 32
;

COMMENT ON TABLE AD.CASHOUT IS '[NOT_SECURITY_APPLY] Tabela para controle de cashout autorizados e confirmados no processo de liquidação';

COMMENT ON COLUMN AD.CASHOUT.IDT_CASHOUT IS '[NOT_SECURITY_APPLY] Identificador da entidade';

COMMENT ON COLUMN AD.CASHOUT.IDT_CONTRACTUAL_EFFECT IS '[NOT_SECURITY_APPLY] Identificador do efeito de contrato dono do Cashout';
	
COMMENT ON COLUMN AD.CASHOUT.COD_CASHOUT IS '[NOT_SECURITY_APPLY] Código do cashout';

COMMENT ON COLUMN AD.CASHOUT.NUM_AMOUNT IS '[NOT_SECURITY_APPLY] Valor total do cashout';

COMMENT ON COLUMN AD.CASHOUT.IND_STATUS IS '[NOT_SECURITY_APPLY] Status da entidade cashout';

COMMENT ON COLUMN AD.CASHOUT.DAT_CASHOUT_CONFIRMATION IS '[NOT_SECURITY_APPLY] Data que o cashout foi confirmado para domínio de Cashout do PagSeguro';

COMMENT ON COLUMN AD.CASHOUT.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';

COMMENT ON COLUMN AD.CASHOUT.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data de atualização';

-- Unique
ALTER TABLE AD.CASHOUT ADD CONSTRAINT CASHOUT_UK01 UNIQUE ( COD_CASHOUT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;


-- FK with index
ALTER TABLE AD.CASHOUT ADD CONSTRAINT CASHOUT_IDT_CON_EFFE_FK FOREIGN KEY ( IDT_CONTRACTUAL_EFFECT )
        REFERENCES AD.CONTRACTUAL_EFFECT ( IDT_CONTRACTUAL_EFFECT ) ENABLE NOVALIDATE;

-- Grants
GRANT SELECT,UPDATE,INSERT,DELETE ON AD.CASHOUT TO RECEIVABLESUBR;
GRANT SELECT ON AD.CASHOUT TO MANUT_RECEIVABLES;