
DECLARE index_count INTEGER;
BEGIN
SELECT COUNT(*) INTO index_count
    FROM USER_INDEXES
    WHERE INDEX_NAME = 'RECEIVABLE_UNIT_EXTERNAL_IDX02';

IF index_count > 0 THEN
    EXECUTE IMMEDIATE 'DROP INDEX RECEIVABLE_UNIT_EXTERNAL_IDX02';
END IF;
END;
/



CREATE UNIQUE INDEX AD.RECEIVABLE_UNIT_EXTERNAL_IDX02 ON AD.RECEIVABLE_UNIT_EXTERNAL 
   (DAT_SETTLE ,           
    COD_CUSTOMER_RECEIVER, 
    COD_CUSTOMER_HOLDER  , 
    IND_PAYMENT_GROUP    , 
    IND_ESCROW_TYPE      
   ) 
LOCAL INITRANS 48 tablespace TSIRECEIVABLES01  online;


