-- Add colunas de NUM_RECOVERED_AMOUNT para tabelas
--  RECEIVABLE_EXTERNAL
--  RECEIVABLE_INTERNAL

ALTER TABLE AD.RECEIVABLE_EXTERNAL ADD NUM_RECOVERED_AMOUNT NUMBER(11, 0) DEFAULT 0 NOT NULL;
ALTER TABLE AD.RECEIVABLE_INTERNAL ADD NUM_RECOVERED_AMOUNT NUMBER(11, 0) DEFAULT 0 NOT NULL;

COMMENT ON COLUMN AD.RECEIVABLE_EXTERNAL.NUM_RECOVERED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor recuperado após liquidação na agenda de débitos.';

COMMENT ON COLUMN AD.RECEIVABLE_INTERNAL.NUM_RECOVERED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor recuperado após liquidação na agenda de débitos.';
