DECLARE
resource_busy EXCEPTION;
PRAGMA EXCEPTION_INIT(resource_busy, -00054);
naoexecutou BOOLEAN := TRUE;
VCOUNT NUMBER := 0;
C_ROLLBACK VARCHAR2(2000) := 'ALTER TABLE AD.CONTRACTUAL_EFFECT MODIFY IND_ESCROW_TYPE NULL';
C_ROLLBACK2 VARCHAR2(2000) := 'ALTER TABLE AD.CONTRACTUAL_EFFECT MODIFY NUM_HOLDER_DOCUMENT NULL';
C_ROLLBACK3 VARCHAR2(2000) := 'ALTER TABLE AD.RECEIVABLE_UNIT_EXTERNAL MODIFY NUM_HOLDER_DOCUMENT NULL';
C_ROLLBACK4 VARCHAR2(2000) := 'ALTER TABLE AD.RECEIVABLE_UNIT_INTERNAL MODIFY NUM_HOLDER_DOCUMENT NULL';

C_SQL1 VARCHAR2(2000) := 'ALTER TABLE AD.CONTRACTUAL_EFFECT MODIFY IND_ESCROW_TYPE NOT NULL';
C_SQL2 VARCHAR2(2000) := 'ALTER TABLE AD.CONTRACTUAL_EFFECT MODIFY NUM_HOLDER_DOCUMENT NOT NULL';
C_SQL3 VARCHAR2(2000) := 'ALTER TABLE AD.RECEIVABLE_UNIT_EXTERNAL MODIFY NUM_HOLDER_DOCUMENT NOT NULL';
C_SQL4 VARCHAR2(2000) := 'ALTER TABLE AD.RECEIVABLE_UNIT_INTERNAL MODIFY NUM_HOLDER_DOCUMENT NOT NULL';


BEGIN
    SELECT COUNT(1)
    INTO VCOUNT
    FROM ALL_TAB_COLUMNS
    WHERE OWNER = 'AD'
      AND TABLE_NAME = 'RECEIVABLE_UNIT_EXTERNAL'
      AND COLUMN_NAME = 'NUM_HOLDER_DOCUMENT';
    IF VCOUNT = 0 THEN
        WHILE naoexecutou
            LOOP
                begin
                    EXECUTE IMMEDIATE C_SQL1;
                    EXECUTE IMMEDIATE C_SQL2;
                    EXECUTE IMMEDIATE C_SQL3;
                    EXECUTE IMMEDIATE C_SQL4;
                    naoexecutou := FALSE;
                    DBMS_OUTPUT.PUT_LINE('COLUNA CRIADA COM SUCESSO !');
                    DBMS_OUTPUT.PUT_LINE('SCRIPT ROLLBACK : ' || C_ROLLBACK);
                    COMMIT;
                EXCEPTION
                    WHEN resource_busy THEN
                        DBMS_SESSION.SLEEP(0.25);
                    WHEN OTHERS THEN
                        RAISE;
                END;
            END LOOP;
    ELSE
        DBMS_OUTPUT.PUT_LINE('*** Coluna existente: ' || sys_context('USERENV', 'INSTANCE_NAME') || ' / ' ||
                             sys_context('USERENV', 'SERVER_HOST'));
    END IF;
END;