DELETE FROM AD.SUSPENSION_OUTBOX;
COMMIT;

ALTER TABLE AD.SUSPENSION_OUTBOX
ADD COD_OUTBOX_EVENT VARCHAR(36) NOT NULL;

COMMENT ON COLUMN AD.SUSPENSION_OUTBOX.COD_OUTBOX_EVENT IS '[NOT_SECURITY_APPLY] CODIGO IDENTIFICADOR DO EVENTO';

CREATE INDEX AD.SUSPENSION_OUTBOX_IDX03 ON AD.SUSPENSION_OUTBOX
( DAT_PARTITION, COD_OUTBOX_EVENT)
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;