CREATE TABLE AD.INSTALLMENT (
    IDT_INSTALLMENT      NUMBER(20)  NOT NULL,
    IDT_PAYMENT          NUMBER(20) NOT NULL,
    NUM_INSTALLMENT      NUMBER(2) NOT NULL,
    DAT_DUE              DATE NOT NULL,
    NUM_AMOUNT           NUMBER(11) NOT NULL,
    NUM_INSTALLMENT_FEE  NUMBER(11) NOT NULL,
	NUM_INSTALLMENT_BUYER_FEE NUMBER(11) NOT NULL,
	CONSTRAINT INSTALLMENT_pk PRIMARY KEY ( idt_INSTALLMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
) TABLESPACE TSDRECEIVABLES01 INITRANS 32;

COMMENT ON TABLE AD.INSTALLMENT IS 'Tabela que guardará dados das parcelas do pagamento';

COMMENT ON COLUMN AD.INSTALLMENT.idt_INSTALLMENT IS '[NOT_SECURITY_APPLY] Identificador da parcela do pagamento';

COMMENT ON COLUMN AD.INSTALLMENT.idt_payment IS '[NOT_SECURITY_APPLY] Identificador do pagamento';

COMMENT ON COLUMN AD.INSTALLMENT.num_INSTALLMENT IS '[NOT_SECURITY_APPLY] Numero da parcela';

COMMENT ON COLUMN AD.INSTALLMENT.dat_due IS '[NOT_SECURITY_APPLY] Data de vencimento';

COMMENT ON COLUMN AD.INSTALLMENT.num_amount IS '[NOT_SECURITY_APPLY] Valor da parcela';

COMMENT ON COLUMN AD.INSTALLMENT.num_INSTALLMENT_fee IS '[NOT_SECURITY_APPLY] Valor da taxa da parcela';

COMMENT ON COLUMN AD.INSTALLMENT.NUM_INSTALLMENT_BUYER_FEE IS '[NOT_SECURITY_APPLY] Valor da taxa de parcelamento paga pelo comprador';

CREATE INDEX AD.INSTALLMENT_idx01 ON AD.INSTALLMENT ( idt_payment ) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

ALTER TABLE AD.INSTALLMENT ADD CONSTRAINT INSTALLMENT_idt_payment_fk FOREIGN KEY ( idt_payment )
        REFERENCES AD.payment ( idt_payment ) ENABLE NOVALIDATE;
		
GRANT SELECT,UPDATE,INSERT,DELETE ON AD.INSTALLMENT TO RECEIVABLESUBR;
GRANT SELECT ON AD.INSTALLMENT TO MANUT_RECEIVABLES;		