-- Adiciona IDT_SETTLEMENT ao CASHOUT
--  Com este novo campo será possível identificar quais foram as Settlements
--  que geraram quais Cashouts.

ALTER TABLE AD.CASHOUT ADD IDT_SETTLEMENT NUMBER(20) NULL;

COMMENT ON COLUMN AD.CASHOUT.IDT_SETTLEMENT 
    IS '[NOT_SECURITY_APPLY] Identificador da SETTLEMENT que liquidou os CONTRACTUAL_EFFECT';

-- Fk with indexes
ALTER TABLE AD.CASHOUT
    ADD CONSTRAINT CASHOUT_IDT_SETTLEMENT_FK FOREIGN KEY ( IDT_SETTLEMENT )
        REFERENCES AD.SETTLEMENT ( IDT_SETTLEMENT ) ENABLE NOVALIDATE;

CREATE INDEX AD.CASHOUT_IDX01 
    ON AD.CASHOUT ( IDT_SETTLEMENT ) INITRANS 12 TABLESPACE TSIRECEIVABLES01 ONLINE;
