DELETE FROM AD.RECEIVABLE_UNIT_OUTBOX;
COMMIT;

ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX
ADD COD_OUTBOX_EVENT VARCHAR(36) NOT NULL;

COMMENT ON COLUMN AD.RECEIVABLE_UNIT_OUTBOX.COD_OUTBOX_EVENT IS '[NOT_SECURITY_APPLY] CODIGO IDENTIFICADOR DO EVENTO';

CREATE INDEX AD.RECEIVABLE_UNIT_OUTBOX_IDX04 ON AD.RECEIVABLE_UNIT_OUTBOX
( DAT_PARTITION, COD_OUTBOX_EVENT)
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;