CREATE INDEX AD.CASHOUT_IDX03 ON AD.CASHOUT (IDT_LEGACY_SAFEPAY_USER ) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX AD.PAYMENT_IDX03 ON AD.PAYMENT ( IND_PROCESS ) INITRANS 12 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX AD.RECEIVABLE_INTENT_IDX01 ON AD.RECEIVABLE_INTENT ( DAT_CREATION ) INITRANS 12 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX AD.LEGACY_IDX01 ON AD.LEGACY (IDT_TRANSACTION) INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;