ALTER TABLE AD.RECEIVABLE_UNIT_INTERNAL ADD FLG_PARTIAL_OWNERSHIP_CHANGE NUMBER(1, 0) DEFAULT 0 NOT NULL ;

COMMENT ON COLUMN AD.RECEIVABLE_UNIT_INTERNAL.FLG_PARTIAL_OWNERSHIP_CHANGE
IS '[NOT_SECURITY_APPLY] Quando ativo, indica que a unidade de recebivel possui troca de titularidade parcial';

ALTER TABLE AD.RECEIVABLE_UNIT_EXTERNAL ADD FLG_PARTIAL_OWNERSHIP_CHANGE NUMBER(1, 0) DEFAULT 0 NOT NULL ;

COMMENT ON COLUMN AD.RECEIVABLE_UNIT_EXTERNAL.FLG_PARTIAL_OWNERSHIP_CHANGE
IS '[NOT_SECURITY_APPLY] Quando ativo, indica que a unidade de recebivel possui troca de titularidade parcial';

ALTER TABLE AD.CONTRACTUAL_EFFECT ADD FLG_PARTIAL_OWNERSHIP_CHANGE NUMBER(1, 0) DEFAULT 0 NOT NULL ;

COMMENT ON COLUMN AD.CONTRACTUAL_EFFECT.FLG_PARTIAL_OWNERSHIP_CHANGE
IS '[NOT_SECURITY_APPLY] Quando ativo, indica que o contrato possui troca de titularidade parcial';
