-- ANTIGO TINHA ESSAS COLUNAS: AT_SETTLE, COD_CUSTOMER_RECEIVER,COD_CUSTOMER_HOLDER, IND_PAYMENT_GROUP, FLG_ACTIVE
DROP INDEX AD.CONTRACTUAL_EFFECT_IDX06;
CREATE INDEX AD.CONTRACTUAL_EFFECT_IDX06 ON AD.CONTRACTUAL_EFFECT 
( DAT_SETTLE, COD_CUSTOMER_RECEIVER, IND_ESCROW_TYPE, IND_PAYMENT_GROUP, FLG_ACTIVE )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;


-- ANTIGO TINHA ESSAS COLUNAS: DAT_SETTLE, COD_CUSTOMER_RECEIVER, IND_PAYMENT_GROUP, IND_STATUS, IND_ESCROW_TYPE
DROP INDEX AD.RECEIVABLE_UNIT_EXTERNAL_IDX01;
CREATE INDEX AD.RECEIVABLE_UNIT_EXTERNAL_IDX01 ON AD.RECEIVABLE_UNIT_EXTERNAL
(DAT_SETTLE, COD_CUSTOMER_RECEIVER, IND_PAYMENT_GROUP, IND_STATUS, IND_SETTLEMENT_ACQUIRER)
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;



-- ANTIGO TINHA ESSAS COLUNAS: DAT_SETTLE, COD_CUSTOMER_RECEIVER, IND_PAYMENT_GROUP, IND_STATUS, IND_ESCROW_TYPE
DROP INDEX AD.RECEIVABLE_UNIT_INTERNAL_IDX01;
CREATE INDEX AD.RECEIVABLE_UNIT_INTERNAL_IDX01 ON
AD.RECEIVABLE_UNIT_INTERNAL (DAT_SETTLE , COD_CUSTOMER_RECEIVER, IND_PAYMENT_GROUP
, IND_STATUS , IND_SETTLEMENT_ACQUIRER ) LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;
