CREATE INDEX AD.CASHOUT_IDX04 ON AD.CASHOUT ( DAT_SETTLE, IDT_CONTRACTUAL_EFFECT )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

BEGIN DBMS_STATS.GATHER_TABLE_STATS ( ownname => 'RECEIVABLES_ADM', tabname => 'CASHOUT', cascade => true, degree  => 16); END;