CREATE TABLE AD.PAYMENT_SUSPENSION (
    IDT_PAYMENT_SUSPENSION      NUMBER(20)  NOT NULL,
    IDT_PAYMENT                 NUMBER(20) NOT NULL,
    COD_REFERENCE               VARCHAR2(36 BYTE) NOT NULL,
    FLG_ACTIVE                  NUMBER(1) NOT NULL,
    DAT_CREATION                TIMESTAMP NOT NULL,
    DAT_UPDATE                  TIMESTAMP NOT NULL,
    JSN_PAYLOAD                 VARCHAR2(4000)  NOT NULL,
	NUM_SETTLE_AMOUNT 			NUMBER(11) NOT NULL,
    CONSTRAINT IDT_PAYMENT_SUSPENSION_PK PRIMARY KEY ( IDT_PAYMENT_SUSPENSION ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48,
    CONSTRAINT JSN_PAYLOAD_PAYMENT_SUSPENSION_CK CHECK ( JSN_PAYLOAD IS JSON )
) INITRANS 32
TABLESPACE TSDRECEIVABLES01;

COMMENT ON TABLE AD.PAYMENT_SUSPENSION IS 'Tabela de relação do código de suspensão com o pagamento (1:1)';

COMMENT ON COLUMN AD.PAYMENT_SUSPENSION.IDT_PAYMENT_SUSPENSION IS '[NOT_SECURITY_APPLY] Identificador PK da tabela';

COMMENT ON COLUMN AD.PAYMENT_SUSPENSION.IDT_PAYMENT IS '[NOT_SECURITY_APPLY] Identificador para relacionamento com a tabela Payment';

COMMENT ON COLUMN AD.PAYMENT_SUSPENSION.COD_REFERENCE IS '[NOT_SECURITY_APPLY] Código de referencia da suspensão, informado pelo client';
	
COMMENT ON COLUMN AD.PAYMENT_SUSPENSION.FLG_ACTIVE IS '[NOT_SECURITY_APPLY] Boleano que indicar se a suspensão do pagamento esta ativo (0 ou 1)';	

COMMENT ON COLUMN AD.PAYMENT_SUSPENSION.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação do registro';

COMMENT ON COLUMN AD.PAYMENT_SUSPENSION.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data de alteração do registro';

COMMENT ON COLUMN AD.PAYMENT_SUSPENSION.JSN_PAYLOAD IS '[NOT_SECURITY_APPLY] Payload enviado pelo client em formato json';

COMMENT ON COLUMN AD.PAYMENT_SUSPENSION.NUM_SETTLE_AMOUNT IS '[NOT_SECURITY_APPLY] Campo para identificar o valor que será liquidado';

CREATE INDEX AD.PAYMENT_SUSPENSION_IDX01 ON AD.PAYMENT_SUSPENSION ( IDT_PAYMENT ) TABLESPACE TSIRECEIVABLES01 INITRANS 12 ONLINE;

CREATE INDEX AD.PAYMENT_SUSPENSION_IDX02 ON AD.PAYMENT_SUSPENSION ( COD_REFERENCE ) TABLESPACE TSIRECEIVABLES01 INITRANS 12 ONLINE;

ALTER TABLE AD.PAYMENT_SUSPENSION ADD CONSTRAINT PAYMENT_SUSPENSION_UK01 UNIQUE ( COD_REFERENCE ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;
ALTER TABLE AD.PAYMENT_SUSPENSION ADD CONSTRAINT PAYMENT_SUSPENSION_UK02 UNIQUE ( IDT_PAYMENT ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 12 ENABLE NOVALIDATE;
ALTER TABLE AD.PAYMENT_SUSPENSION ADD CONSTRAINT PAYMENT_SUSPENSION_IDT_PAYMENT_FK FOREIGN KEY ( IDT_PAYMENT )
        REFERENCES AD.PAYMENT ( IDT_PAYMENT ) ENABLE NOVALIDATE;

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.PAYMENT_SUSPENSION TO RECEIVABLESUBR;
GRANT SELECT ON AD.PAYMENT_SUSPENSION TO MANUT_RECEIVABLES;