ALTER TABLE AD.PAYMENT_ADDRESS ADD FLG_SELLER_CHAIN_SUBSIDIARY NUMBER(1);

COMMENT ON COLUMN AD.PAYMENT_ADDRESS.FLG_SELLER_CHAIN_SUBSIDIARY IS '[NOT_SECURITY_APPLY] Flag informando se o cliente é uma filial pertencente a uma rede centralizada.';

