CREATE INDEX AD.RECEIVABLE_UNIT_OUTBOX_IDX05 ON AD.RECEIVABLE_UNIT_OUTBOX ( DAT_PARTITION, IND_STATUS )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE PARALLEL 16;

ALTER INDEX AD.RECEIVABLE_UNIT_OUTBOX_IDX05 NOPARALLEL;