CREATE TABLE AD.CCE_INTERNAL_HISTORY (
  IDT_CCE_INTERNAL_HISTORY NUMBER(20)  NOT NULL,
  IDT_CONTRACTUAL_EFFECT NUMBER(20, 0) NOT NULL ,
  IDT_PAYMENT_ADDRESS NUMBER(20, 0) NOT NULL ,
  DAT_SETTLE DATE NOT NULL ,
  COD_CONTRACTUAL_EFFECT_OLD VARCHAR2(36 BYTE) NOT NULL ,
  DAT_CREATION TIMESTAMP(6) NOT NULL,
    CONSTRAINT CCE_INTERNAL_HISTORY_PK PRIMARY KEY ( IDT_CCE_INTERNAL_HISTORY ) USING INDEX TABLESPACE TSIRECEIVABLES01 INITRANS 48
)
PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_1 VALUES LESS THAN (TO_DATE('2021-04-07','YYYY-MM-DD'))
) TABLESPACE TSDRECEIVABLES01 INITRANS 64 PCTFREE 20
;

COMMENT ON TABLE AD.CCE_INTERNAL_HISTORY IS
    'Tabela que guardará o histórico de alterações de efeitos de contrato internos';

COMMENT ON COLUMN AD.CCE_INTERNAL_HISTORY.IDT_CCE_INTERNAL_HISTORY IS '[NOT_SECURITY_APPLY] Identificador do histórico de efeito de contrato';
COMMENT ON COLUMN AD.CCE_INTERNAL_HISTORY.IDT_CONTRACTUAL_EFFECT IS '[NOT_SECURITY_APPLY] Identificador do efeito de contrato';
COMMENT ON COLUMN AD.CCE_INTERNAL_HISTORY.IDT_PAYMENT_ADDRESS IS '[NOT_SECURITY_APPLY] Identificador do endereço de pagamento';
COMMENT ON COLUMN AD.CCE_INTERNAL_HISTORY.DAT_SETTLE IS '[NOT_SECURITY_APPLY] Data a ser liquidado do efeito de contrato';
COMMENT ON COLUMN AD.CCE_INTERNAL_HISTORY.COD_CONTRACTUAL_EFFECT_OLD IS '[NOT_SECURITY_APPLY] Código do efeito de contrato anterior';
COMMENT ON COLUMN AD.CCE_INTERNAL_HISTORY.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de criação';


CREATE INDEX AD.CCE_INTERNAL_HISTORY_IDX01 ON AD.CCE_INTERNAL_HISTORY ( DAT_SETTLE, COD_CONTRACTUAL_EFFECT_OLD )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX AD.CCE_INTERNAL_HISTORY_IDX02 ON AD.CCE_INTERNAL_HISTORY ( DAT_SETTLE, IDT_CONTRACTUAL_EFFECT )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

CREATE INDEX AD.CCE_INTERNAL_HISTORY_IDX03 ON AD.CCE_INTERNAL_HISTORY ( DAT_SETTLE, IDT_PAYMENT_ADDRESS )
LOCAL INITRANS 48 TABLESPACE TSIRECEIVABLES01 ONLINE;

ALTER TABLE AD.CCE_INTERNAL_HISTORY ADD CONSTRAINT CCE_INT_HIST_IDT_PAY_ADDR_FK FOREIGN KEY ( IDT_PAYMENT_ADDRESS )
        REFERENCES AD.PAYMENT_ADDRESS ( IDT_PAYMENT_ADDRESS ) ENABLE NOVALIDATE;

ALTER TABLE AD.CCE_INTERNAL_HISTORY ADD CONSTRAINT CCE_INT_HIST_IDT_CON_EFF_FK FOREIGN KEY ( IDT_CONTRACTUAL_EFFECT )
        REFERENCES AD.CONTRACTUAL_EFFECT ( IDT_CONTRACTUAL_EFFECT ) ENABLE NOVALIDATE;

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.CCE_INTERNAL_HISTORY TO RECEIVABLESUBR;
GRANT SELECT ON AD.CCE_INTERNAL_HISTORY TO MANUT_RECEIVABLES;

GRANT SELECT,UPDATE ON AD.CCE_INTERNAL_HISTORY TO KAFKA_RECEIVABLESUBR;
GRANT SELECT ON AD.CCE_INTERNAL_HISTORY TO RECMONITORSUBR;