ALTER TABLE AD.PAYMENT ENABLE CONSTRAINT PAYMENT_IDT_PAYMENT_FK2;


ALTER TABLE AD.INSTALLMENT ENABLE CONSTRAINT INSTALLMENT_idt_payment_fk;
	

ALTER TABLE AD.PAYMENT ENABLE CONSTRAINT PAYMENT_IDT_LEGACY_FK;		
	

ALTER TABLE AD.PAYMENT_SUSPENSION ENABLE CONSTRAINT PAYMENT_SUSPENSION_IDT_PAYMENT_FK;


ALTER TABLE AD.SUSPENSION ENABLE CONSTRAINT SUSP_IDT_PAYMENT_SUSPENSION_FK;


ALTER TABLE AD.SUSPENSION_HISTORY ENABLE CONSTRAINT SUSP_HIST_IDT_SUSPENSION_FK;


ALTER TABLE AD.SUSPENSION_HISTORY ENABLE CONSTRAINT SUSP_HIST_IDT_PAY_SUSPENSION_FK;


ALTER TABLE AD.RECEIVABLE_EXTERNAL ENABLE CONSTRAINT REC_EXT_IDT_PAYMENT_FK;

ALTER TABLE AD.RECEIVABLE_EXTERNAL ENABLE CONSTRAINT REC_EXT_IDT_REC_UNIT_EXT_FK;


ALTER TABLE AD.RECEIVABLE_INTERNAL ENABLE CONSTRAINT REC_INT_IDT_PAYMENT_FK;

ALTER TABLE AD.RECEIVABLE_INTERNAL ENABLE CONSTRAINT REC_INT_IDT_REC_UNIT_INT_FK;
	

ALTER TABLE AD.CONTRACTUAL_EFFECT ENABLE CONSTRAINT CON_EFF_IDT_PAY_ADDR_FK;

ALTER TABLE AD.CONTRACTUAL_EFFECT ENABLE CONSTRAINT CON_EFF_IDT_REC_EXT_FK;

ALTER TABLE AD.CONTRACTUAL_EFFECT ENABLE CONSTRAINT CON_EFF_IDT_REC_INT_FK;


ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX ENABLE CONSTRAINT REC_OUT_IDT_REC_EXT_FK;
	
 
ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX ENABLE CONSTRAINT REC_OUT_IDT_REC_INT_FK;


ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION ENABLE CONSTRAINT REC_UNIT_ASS_REC_EXT_IDT_FK;

ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION ENABLE CONSTRAINT REC_UNIT_ASS_REC_INT_IDT_FK;


ALTER TABLE AD.CCE_STATIC_AMOUNT_SUMMARY ENABLE CONSTRAINT STA_SUM_IDT_CON_EFFE_FK;


ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT ENABLE CONSTRAINT SET_CON_EFFE_IDT_CON_EFFE_FK;


ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT ENABLE CONSTRAINT SET_CON_EFFE_IDT_SETTLEMENT_FK;


ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL ENABLE CONSTRAINT CCE_REC_EXTER_IDT_CCE_FK;

ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL ENABLE CONSTRAINT CCE_REC_EXTER_IDT_REC_EXTER_FK;
		
ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL ENABLE CONSTRAINT CCE_REC_EXTER_IDT_SETT_FK;


ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL ENABLE CONSTRAINT CCE_REC_INTER_IDT_CCE_FK;

ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL ENABLE CONSTRAINT CCE_REC_INTER_IDT_REC_INTER_FK;
		
ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL ENABLE CONSTRAINT CCE_REC_INTER_IDT_SETT_FK;


-- FK with index
ALTER TABLE AD.CASHOUT ENABLE CONSTRAINT CASHOUT_IDT_CON_EFFE_FK;

ALTER TABLE AD.CASHOUT ENABLE CONSTRAINT CASHOUT_IDT_SETTLEMENT_FK;


-- FK with index
ALTER TABLE AD.RECOVERY ENABLE CONSTRAINT RECOVERY_IDT_SETTLEMENT_FK;

ALTER TABLE AD.RECOVERY ENABLE CONSTRAINT RECOVERY_COD_CASHOUT_FK;


ALTER TABLE AD.REC_ANTICIPATION_INTENT ENABLE CONSTRAINT REC_ANT_INT_IDT_REC_ANT_FK;


ALTER TABLE AD.REC_ANTICIPATION_INTENT ENABLE CONSTRAINT REC_ANT_INT_REC_UNI_INT_FK;

		
ALTER TABLE AD.REC_ANTICIPATION_INTENT ENABLE CONSTRAINT REC_ANT_INT_REC_UNI_EXT_FK;


ALTER TABLE AD.SUSPENSION_OUTBOX ENABLE CONSTRAINT REC_OUT_IDT_SUSP_OUTBOX_FK;


ALTER TABLE AD.CCE_INTERNAL_HISTORY ENABLE CONSTRAINT CCE_INT_HIST_IDT_PAY_ADDR_FK;

ALTER TABLE AD.CCE_INTERNAL_HISTORY ENABLE CONSTRAINT CCE_INT_HIST_IDT_CON_EFF_FK;