ALTER TABLE AD.PAYMENT DISABLE CONSTRAINT PAYMENT_IDT_PAYMENT_FK2;


ALTER TABLE AD.INSTALLMENT DISABLE CONSTRAINT INSTALLMENT_idt_payment_fk;
	

ALTER TABLE AD.PAYMENT DISABLE CONSTRAINT PAYMENT_IDT_LEGACY_FK;		
	

ALTER TABLE AD.PAYMENT_SUSPENSION DISABLE CONSTRAINT PAYMENT_SUSPENSION_IDT_PAYMENT_FK;


ALTER TABLE AD.SUSPENSION DISABLE CONSTRAINT SUSP_IDT_PAYMENT_SUSPENSION_FK;


ALTER TABLE AD.SUSPENSION_HISTORY DISABLE CONSTRAINT SUSP_HIST_IDT_SUSPENSION_FK;


ALTER TABLE AD.SUSPENSION_HISTORY DISABLE CONSTRAINT SUSP_HIST_IDT_PAY_SUSPENSION_FK;


ALTER TABLE AD.RECEIVABLE_EXTERNAL DISABLE CONSTRAINT REC_EXT_IDT_PAYMENT_FK;

ALTER TABLE AD.RECEIVABLE_EXTERNAL DISABLE CONSTRAINT REC_EXT_IDT_REC_UNIT_EXT_FK;


ALTER TABLE AD.RECEIVABLE_INTERNAL DISABLE CONSTRAINT REC_INT_IDT_PAYMENT_FK;

ALTER TABLE AD.RECEIVABLE_INTERNAL DISABLE CONSTRAINT REC_INT_IDT_REC_UNIT_INT_FK;
	

ALTER TABLE AD.CONTRACTUAL_EFFECT DISABLE CONSTRAINT CON_EFF_IDT_PAY_ADDR_FK;

ALTER TABLE AD.CONTRACTUAL_EFFECT DISABLE CONSTRAINT CON_EFF_IDT_REC_EXT_FK;

ALTER TABLE AD.CONTRACTUAL_EFFECT DISABLE CONSTRAINT CON_EFF_IDT_REC_INT_FK;


ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX DISABLE CONSTRAINT REC_OUT_IDT_REC_EXT_FK;
	
 
ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX DISABLE CONSTRAINT REC_OUT_IDT_REC_INT_FK;


ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION DISABLE CONSTRAINT REC_UNIT_ASS_REC_EXT_IDT_FK;

ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION DISABLE CONSTRAINT REC_UNIT_ASS_REC_INT_IDT_FK;


ALTER TABLE AD.CCE_STATIC_AMOUNT_SUMMARY DISABLE CONSTRAINT STA_SUM_IDT_CON_EFFE_FK;


ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT DISABLE CONSTRAINT SET_CON_EFFE_IDT_CON_EFFE_FK;


ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT DISABLE CONSTRAINT SET_CON_EFFE_IDT_SETTLEMENT_FK;


ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DISABLE CONSTRAINT CCE_REC_EXTER_IDT_CCE_FK;

ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DISABLE CONSTRAINT CCE_REC_EXTER_IDT_REC_EXTER_FK;
		
ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DISABLE CONSTRAINT CCE_REC_EXTER_IDT_SETT_FK;


ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DISABLE CONSTRAINT CCE_REC_INTER_IDT_CCE_FK;

ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DISABLE CONSTRAINT CCE_REC_INTER_IDT_REC_INTER_FK;
		
ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DISABLE CONSTRAINT CCE_REC_INTER_IDT_SETT_FK;


-- FK with index
ALTER TABLE AD.CASHOUT DISABLE CONSTRAINT CASHOUT_IDT_CON_EFFE_FK;

ALTER TABLE AD.CASHOUT DISABLE CONSTRAINT CASHOUT_IDT_SETTLEMENT_FK;


-- FK with index
ALTER TABLE AD.RECOVERY DISABLE CONSTRAINT RECOVERY_IDT_SETTLEMENT_FK;

ALTER TABLE AD.RECOVERY DISABLE CONSTRAINT RECOVERY_COD_CASHOUT_FK;


ALTER TABLE AD.REC_ANTICIPATION_INTENT DISABLE CONSTRAINT REC_ANT_INT_IDT_REC_ANT_FK;


ALTER TABLE AD.REC_ANTICIPATION_INTENT DISABLE CONSTRAINT REC_ANT_INT_REC_UNI_INT_FK;

		
ALTER TABLE AD.REC_ANTICIPATION_INTENT DISABLE CONSTRAINT REC_ANT_INT_REC_UNI_EXT_FK;


ALTER TABLE AD.SUSPENSION_OUTBOX DISABLE CONSTRAINT REC_OUT_IDT_SUSP_OUTBOX_FK;

ALTER TABLE AD.CCE_INTERNAL_HISTORY DISABLE CONSTRAINT CCE_INT_HIST_IDT_PAY_ADDR_FK;

ALTER TABLE AD.CCE_INTERNAL_HISTORY DISABLE CONSTRAINT CCE_INT_HIST_IDT_CON_EFF_FK;
