insert into AD.RECEIVABLE_INTENT
select * from RECEIVABLES_ADM.RECEIVABLE_INTENT;
commit;

insert into AD.CCE_REASSOCIATE_CONTROL
select * from RECEIVABLES_ADM.CCE_REASSOCIATE_CONTROL;
commit;

insert into AD.PAYMENT
select * from RECEIVABLES_ADM.PAYMENT;
commit;

insert into AD.INSTALLMENT
select * from RECEIVABLES_ADM.INSTALLMENT;
commit;

insert into AD.LEGACY
select * from RECEIVABLES_ADM.LEGACY;
commit;

insert into AD.PAYMENT_SUSPENSION
select * from RECEIVABLES_ADM.PAYMENT_SUSPENSION;
commit;

insert into AD.SUSPENSION
select * from RECEIVABLES_ADM.SUSPENSION;
commit;

insert into AD.SUSPENSION_HISTORY
select * from RECEIVABLES_ADM.SUSPENSION_HISTORY;
commit;

insert into AD.RECEIVABLE_UNIT_EXTERNAL
select * from RECEIVABLES_ADM.RECEIVABLE_UNIT_EXTERNAL;
commit;

insert into AD.RECEIVABLE_UNIT_INTERNAL
select * from RECEIVABLES_ADM.RECEIVABLE_UNIT_INTERNAL;
commit;

insert into AD.RECEIVABLE_EXTERNAL
select * from RECEIVABLES_ADM.RECEIVABLE_EXTERNAL;
commit;

insert into AD.RECEIVABLE_INTERNAL
select * from RECEIVABLES_ADM.RECEIVABLE_INTERNAL;
commit;

insert into AD.PAYMENT_ADDRESS
select * from RECEIVABLES_ADM.PAYMENT_ADDRESS;
commit;

insert into AD.CONTRACTUAL_EFFECT
select * from RECEIVABLES_ADM.CONTRACTUAL_EFFECT;
commit;

insert into AD.RECEIVABLE_UNIT_OUTBOX
select * from RECEIVABLES_ADM.RECEIVABLE_UNIT_OUTBOX;
commit;

insert into AD.RECEIVABLE_UNIT_ASSOCIATION
select * from RECEIVABLES_ADM.RECEIVABLE_UNIT_ASSOCIATION;
commit;

insert into AD.CCE_STATIC_AMOUNT_SUMMARY
select * from RECEIVABLES_ADM.CCE_STATIC_AMOUNT_SUMMARY;
commit;

insert into AD.SETTLEMENT
select * from RECEIVABLES_ADM.SETTLEMENT;
commit;

insert into AD.SETTLEMENT_CONTRACTUAL_EFFECT
select * from RECEIVABLES_ADM.SETTLEMENT_CONTRACTUAL_EFFECT;
commit;

insert into AD.CCE_RECEIVABLE_EXTERNAL
select * from RECEIVABLES_ADM.CCE_RECEIVABLE_EXTERNAL;
commit;

insert into AD.CCE_RECEIVABLE_INTERNAL
select * from RECEIVABLES_ADM.CCE_RECEIVABLE_INTERNAL;
commit;

insert into AD.CASHOUT
select * from RECEIVABLES_ADM.CASHOUT;
commit;

insert into AD.RECOVERY
select * from RECEIVABLES_ADM.RECOVERY;
commit;

insert into AD.RECEIVABLE_ANTICIPATION
select * from RECEIVABLES_ADM.RECEIVABLE_ANTICIPATION;
commit;

insert into AD.REC_ANTICIPATION_INTENT
select * from RECEIVABLES_ADM.REC_ANTICIPATION_INTENT;
commit;

insert into AD.SUSPENSION_OUTBOX
select * from RECEIVABLES_ADM.SUSPENSION_OUTBOX;
commit;

insert into AD.CCE_INTERNAL_HISTORY
select * from RECEIVABLES_ADM.CCE_INTERNAL_HISTORY;
commit;


