ALTER TABLE AD.PAYMENT DROP CONSTRAINT PAYMENT_IDT_PAYMENT_FK2;


ALTER TABLE AD.INSTALLMENT DROP CONSTRAINT INSTALLMENT_idt_payment_fk;
	

ALTER TABLE AD.PAYMENT DROP CONSTRAINT PAYMENT_IDT_LEGACY_FK;		
	

ALTER TABLE AD.PAYMENT_SUSPENSION DROP CONSTRAINT PAYMENT_SUSPENSION_IDT_PAYMENT_FK;


ALTER TABLE AD.SUSPENSION DROP CONSTRAINT SUSP_IDT_PAYMENT_SUSPENSION_FK;


ALTER TABLE AD.SUSPENSION_HISTORY DROP CONSTRAINT SUSP_HIST_IDT_SUSPENSION_FK;


ALTER TABLE AD.SUSPENSION_HISTORY DROP CONSTRAINT SUSP_HIST_IDT_PAY_SUSPENSION_FK;


ALTER TABLE AD.RECEIVABLE_EXTERNAL DROP CONSTRAINT REC_EXT_IDT_PAYMENT_FK;

ALTER TABLE AD.RECEIVABLE_EXTERNAL DROP CONSTRAINT REC_EXT_IDT_REC_UNIT_EXT_FK;


ALTER TABLE AD.RECEIVABLE_INTERNAL DROP CONSTRAINT REC_INT_IDT_PAYMENT_FK;

ALTER TABLE AD.RECEIVABLE_INTERNAL DROP CONSTRAINT REC_INT_IDT_REC_UNIT_INT_FK;
	

ALTER TABLE AD.CONTRACTUAL_EFFECT DROP CONSTRAINT CON_EFF_IDT_PAY_ADDR_FK;

ALTER TABLE AD.CONTRACTUAL_EFFECT DROP CONSTRAINT CON_EFF_IDT_REC_EXT_FK;

ALTER TABLE AD.CONTRACTUAL_EFFECT DROP CONSTRAINT CON_EFF_IDT_REC_INT_FK;


ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX DROP CONSTRAINT REC_OUT_IDT_REC_EXT_FK;
	
 
ALTER TABLE AD.RECEIVABLE_UNIT_OUTBOX DROP CONSTRAINT REC_OUT_IDT_REC_INT_FK;


ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION DROP CONSTRAINT REC_UNIT_ASS_REC_EXT_IDT_FK;

ALTER TABLE AD.RECEIVABLE_UNIT_ASSOCIATION DROP CONSTRAINT REC_UNIT_ASS_REC_INT_IDT_FK;


ALTER TABLE AD.CCE_STATIC_AMOUNT_SUMMARY DROP CONSTRAINT STA_SUM_IDT_CON_EFFE_FK;


ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT DROP CONSTRAINT SET_CON_EFFE_IDT_CON_EFFE_FK;


ALTER TABLE AD.SETTLEMENT_CONTRACTUAL_EFFECT DROP CONSTRAINT SET_CON_EFFE_IDT_SETTLEMENT_FK;


ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DROP CONSTRAINT CCE_REC_EXTER_IDT_CCE_FK;

ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DROP CONSTRAINT CCE_REC_EXTER_IDT_REC_EXTER_FK;
		
ALTER TABLE AD.CCE_RECEIVABLE_EXTERNAL DROP CONSTRAINT CCE_REC_EXTER_IDT_SETT_FK;


ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DROP CONSTRAINT CCE_REC_INTER_IDT_CCE_FK;

ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DROP CONSTRAINT CCE_REC_INTER_IDT_REC_INTER_FK;
		
ALTER TABLE AD.CCE_RECEIVABLE_INTERNAL DROP CONSTRAINT CCE_REC_INTER_IDT_SETT_FK;


-- FK with index
ALTER TABLE AD.CASHOUT DROP CONSTRAINT CASHOUT_IDT_CON_EFFE_FK;

ALTER TABLE AD.CASHOUT DROP CONSTRAINT CASHOUT_IDT_SETTLEMENT_FK;


-- FK with index
ALTER TABLE AD.RECOVERY DROP CONSTRAINT RECOVERY_IDT_SETTLEMENT_FK;

ALTER TABLE AD.RECOVERY DROP CONSTRAINT RECOVERY_COD_CASHOUT_FK;


ALTER TABLE AD.REC_ANTICIPATION_INTENT DROP CONSTRAINT REC_ANT_INT_IDT_REC_ANT_FK;


ALTER TABLE AD.REC_ANTICIPATION_INTENT DROP CONSTRAINT REC_ANT_INT_REC_UNI_INT_FK;

		
ALTER TABLE AD.REC_ANTICIPATION_INTENT DROP CONSTRAINT REC_ANT_INT_REC_UNI_EXT_FK;


ALTER TABLE AD.SUSPENSION_OUTBOX DROP CONSTRAINT REC_OUT_IDT_SUSP_OUTBOX_FK;

ALTER TABLE AD.CCE_HISTORY DROP CONSTRAINT CCE_INT_HIST_IDT_PAY_ADDR_FK;

ALTER TABLE AD.CCE_HISTORY DROP CONSTRAINT CCE_INT_HIST_IDT_CON_EFF_FK;

ALTER TABLE AD.SETTLEMENT_CONTRACT_EVENT DROP CONSTRAINT SETTLEMENT_CONTRACT_EVENT_IDT_RECEIVABLE_UNIT_EXTERNAL_FK;