SELECT
    UP.IDT_USER_APPLICATION , -- ID QUE VOCES USAM
    AC.IDT_SAFEPAY_USER , -- VELHO ID DO USUARIO NO PAG
    AC.COD_CUSTOMER ,-- NOVO ID DO USUARIO NO PAG
    cpf.NUM_CPF ,
    cpj.NUM_CNPJ ,
    P.NAM_PERSON
FROM SAFEPAY_ADM.USER_APPLICATION UP
INNER JOIN SAFEPAY_ADM.ACCOUNT_CUSTOMER AC ON AC.IDT_SAFEPAY_USER = UP.IDT_SAFEPAY_USER
INNER JOIN SAFEPAY_ADM.SAFEUSER_REGISTERED SR ON SR.IDT_SAFEPAY_USER  = AC.IDT_SAFEPAY_USER
LEFT JOIN UOLBR.CADASTRO_PESSOA_FISICA cpf ON cpf.IDT_PERSON = SR.IDT_PERSON 
LEFT JOIN UOLBR.CADASTRO_PESSOA_JURIDICA CPJ ON cpj.IDT_PERSON = SR.IDT_PERSON 
INNER JOIN PERSON P ON P.IDT_PERSON = SR.IDT_PERSON;
Colla