-- DROP

DROP TABLE AD.CERC_AP007 CASCADE CONSTRAINTS;
DROP TABLE AD.CONTRACT_CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE AD.CONTRACT_CUSTOMER_LEGACY CASCADE CONSTRAINTS;
DROP TABLE AD.CUSTOMER CASCADE CONSTRAINTS;
DROP TABLE AD.CUSTOMER_ESCROW CASCADE CONSTRAINTS;
DROP TABLE AD.CUSTOMER_PLAN CASCADE CONSTRAINTS;
DROP TABLE AD.CUSTOMER_REPLICATION CASCADE CONSTRAINTS;
DROP TABLE AD.PAYMENT_GROUP CASCADE CONSTRAINTS;

-- TRUNCATE

TRUNCATE TABLE AD.CERC_AP007;
TRUNCATE TABLE AD.CONTRACT_CUSTOMER;
TRUNCATE TABLE AD.CONTRACT_CUSTOMER_LEGACY;
TRUNCATE TABLE AD.CUSTOMER;
TRUNCATE TABLE AD.CUSTOMER_ESCROW;
TRUNCATE TABLE AD.CUSTOMER_PLAN;
TRUNCATE TABLE AD.CUSTOMER_REPLICATION;
TRUNCATE TABLE AD.PAYMENT_GROUP;