create TABLE AD.CUSTOMER (
	COD_CUSTOMER					VARCHAR(50)				   NOT NULL,
	NAM_CONTRACTOR_DOCUMENT			VARCHAR(18)				   NOT NULL,
	CONSTRAINT CUSTOMER_PK PRIMARY KEY ( COD_CUSTOMER ) USING INDEX TABLESPACE TSICONTRACTMANAGER01 INITRANS 10
)TABLESPACE TSDCONTRACTMANAGER01 INITRANS 10;

COMMENT ON TABLE AD.CUSTOMER                             			IS 'Tabela para associar códigos aos documentos de lojistas';
COMMENT ON COLUMN AD.CUSTOMER.COD_CUSTOMER      					IS 'Código do lojista';
COMMENT ON COLUMN AD.CUSTOMER.NAM_CONTRACTOR_DOCUMENT      		IS 'PII - Documento do lojista';

create or replace synonym CONTRACTMANAGERUBR.CUSTOMER for AD.CUSTOMER;
create or replace synonym MANUT_CONTRACTMANAGER.CUSTOMER for AD.CUSTOMER;

GRANT SELECT,UPDATE,INSERT,DELETE ON CONTRACTMANAGERUBR.CUSTOMER TO CONTRACTMANAGERUBR;
GRANT SELECT ON CONTRACTMANAGERUBR.CUSTOMER TO MANUT_CONTRACTMANAGER;