create TABLE AD.CUSTOMER_ESCROW (
    IDT_CUSTOMER_ESCROW             NUMBER(20)
     NOT NULL,
	COD_CUSTOMER					VARCHAR(50)				   NOT NULL,
	NUM_CONTRACTOR_DOCUMENT		    VARCHAR(18)				   NOT NULL,
    FLG_VALIDATION_DOCUMENT         NUMBER(1)                  NOT NULL,
    FLG_REGISTER_CUSTOMER           NUMBER(1)                  NOT NULL,
    NUM_CHECKS                      NUMBER(2)                  NOT NULL,
    DAT_CREATION                    TIMESTAMP DEFAULT SYSDATE  NOT NULL,
    DAT_UPDATE                      TIMESTAMP DEFAULT SYSDATE  NOT NULL,
	CONSTRAINT CUSTOMER_ESCROW_PK PRIMARY KEY ( COD_CUSTOMER ) USING INDEX TABLESPACE TSICONTRACTMANAGER01 INITRANS 10
)TABLESPACE TSDCONTRACTMANAGER01 INITRANS 10;

COMMENT ON TABLE AD.CUSTOMER_ESCROW                             	 IS 'Tabela com documentos dos lojistas escrow do PagS';
COMMENT ON COLUMN AD.CUSTOMER_ESCROW.IDT_CUSTOMER_ESCROW            IS 'Identificador da tabela';
COMMENT ON COLUMN AD.CUSTOMER_ESCROW.COD_CUSTOMER      			 IS 'Código do lojista';
COMMENT ON COLUMN AD.CUSTOMER_ESCROW.NUM_CONTRACTOR_DOCUMENT      	 IS 'PII - Documento do lojista';
COMMENT ON COLUMN AD.CUSTOMER_ESCROW.FLG_VALIDATION_DOCUMENT        IS 'Verifica se o documento do cliente é válido';
COMMENT ON COLUMN AD.CUSTOMER_ESCROW.FLG_REGISTER_CUSTOMER          IS 'Verifica se o cadastro do cliente foi realizado com sucesso e o dado está na tabela CUSTOMER_REPLICATION';
COMMENT ON COLUMN AD.CUSTOMER_ESCROW.NUM_CHECKS                     IS 'Número de verificações do registro do cliente na tabela CUSTOMER_REPLICATION';
COMMENT ON COLUMN AD.CUSTOMER_ESCROW.DAT_CREATION                   IS 'Data de inserção do evento na tabela';
COMMENT ON COLUMN AD.CUSTOMER_ESCROW.DAT_UPDATE                     IS 'Data de atualização do evento na tabela';

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.CUSTOMER_ESCROW TO CONTRACTMANAGERUBR;
GRANT SELECT ON AD.CUSTOMER_ESCROW TO MANUT_CONTRACTMANAGER;

CREATE INDEX CUSTOMER_ESCROW_IDX01 ON AD.CUSTOMER_ESCROW(DAT_UPDATE) INITRANS 12 TABLESPACE TSICONTRACTMANAGER01 ONLINE;
