ALTER TABLE AD.CUSTOMER_REPLICATION ADD FLG_MIGRATED NUMBER(1) NOT NULL;

COMMENT ON COLUMN AD.CUSTOMER_REPLICATION.FLG_MIGRATED IS 'Flag que indica se foram criados todos os contratos para o lojista';
