create TABLE AD.CERC_AP007 (
	IDT_OPERATION	   				NUMBER(20) NOT NULL,
	COD_EXTERNAL_REFERENCE_AP007A	VARCHAR(50 BYTE)				   NOT NULL,
	COD_CONTRACT					VARCHAR(50 BYTE)				   NOT NULL,
	COD_EXTERNAL_REFERENCE_AP007B	VARCHAR(50 BYTE)				   NOT NULL,
	COD_CUSTOMER					VARCHAR(50 BYTE)				   NOT NULL,
	NAM_CONTRACTOR_DOCUMENT			VARCHAR(18 BYTE)				   NOT NULL,
	FLG_SENT						NUMBER(1)					        NOT NULL,
	NUM_RETRIES						NUMBER(2),
	NUM_RESPONSE					NUMBER(3),
	COD_PROTOCOL					VARCHAR(18  BYTE),
    DAT_CREATION       				TIMESTAMP DEFAULT SYSDATE  NOT NULL ,
	DAT_UPDATE         				TIMESTAMP DEFAULT SYSDATE   NOT NULL ,
	CONSTRAINT CERC_AP007_PK PRIMARY KEY ( IDT_OPERATION ) USING INDEX TABLESPACE TSICONTRACTMANAGER01 INITRANS 10
) TABLESPACE TSDCONTRACTMANAGER01 INITRANS 10;

COMMENT ON TABLE AD.CERC_AP007            							IS 'Tabela de controle de contratos para serem enviados a CERC';
COMMENT ON COLUMN AD.CERC_AP007.IDT_OPERATION              		IS 'Chave primária da tabela';
COMMENT ON COLUMN AD.CERC_AP007.COD_EXTERNAL_REFERENCE_AP007A      IS 'Código de referência externa do contrato CERC_AP007A';
COMMENT ON COLUMN AD.CERC_AP007.COD_CONTRACT					    IS 'Código do contrato CERC_AP007';
COMMENT ON COLUMN AD.CERC_AP007.COD_EXTERNAL_REFERENCE_AP007B      IS 'Código de referência externa do contrato CERC_AP007B';
COMMENT ON COLUMN AD.CERC_AP007.COD_CUSTOMER      					IS 'Código do lojista';
COMMENT ON COLUMN AD.CERC_AP007.NAM_CONTRACTOR_DOCUMENT      		IS 'Documento do lojista';
COMMENT ON COLUMN AD.CERC_AP007.FLG_SENT      						IS 'Flag que indica se o contrato foi enviado a CERC';
COMMENT ON COLUMN AD.CERC_AP007.NUM_RETRIES      					IS 'Quantidade de retentativas de envio do contrato';
COMMENT ON COLUMN AD.CERC_AP007.NUM_RESPONSE      					IS 'Resposta da requisição de criação de contrato';
COMMENT ON COLUMN AD.CERC_AP007.COD_PROTOCOL      					IS 'Código do protocolo de resposta da requisição de criação de contrato';
COMMENT ON COLUMN AD.CERC_AP007.DAT_CREATION      					IS 'Data de criação de contrato';
COMMENT ON COLUMN AD.CERC_AP007.DAT_UPDATE      					IS 'Data de atualização de contrato';

ALTER TABLE AD.CERC_AP007 ADD CONSTRAINT CERC_AP007_COD_CUSTOMER_FK FOREIGN KEY ( COD_CUSTOMER )
        REFERENCES AD.CUSTOMER ( COD_CUSTOMER );

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.CERC_AP007 TO CONTRACTMANAGERUBR;

GRANT SELECT ON AD.CERC_AP007 TO MANUT_CONTRACTMANAGER;
		
