create TABLE AD.contract_customer (
	COD_CONTRACT					VARCHAR(50)				    NOT NULL,
	COD_CUSTOMER					VARCHAR(50)				    NOT NULL,
    FLG_ACTIVE                      NUMBER(1)                   NOT NULL,
    CONSTRAINT CONTRACT_CUSTOMER_PK PRIMARY KEY (COD_CONTRACT)
    USING INDEX TABLESPACE TSICONTRACTMANAGER01 INITRANS 10
) TABLESPACE TSDCONTRACTMANAGER01 INITRANS 10;

COMMENT ON TABLE  AD.CONTRACT_CUSTOMER                                   IS 'Tabela de controle de contratos para serem enviados a CERC';
COMMENT ON COLUMN AD.CONTRACT_CUSTOMER.COD_CONTRACT                      IS 'Código do contrato, identificador da tabela';
COMMENT ON COLUMN AD.CONTRACT_CUSTOMER.COD_CUSTOMER                      IS 'Código do lojista';
COMMENT ON COLUMN AD.CONTRACT_CUSTOMER.FLG_ACTIVE                        IS 'Flag que indica se o contrato está ativo';

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.CONTRACT_CUSTOMER TO CONTRACTMANAGERUBR;
GRANT SELECT ON AD.CONTRACT_CUSTOMER TO MANUT_CONTRACTMANAGER;