insert into AD.CERC_AP007
select * from CONTRACTMANAGER_ADM.CERC_AP007;
commit;

insert into AD.CONTRACT_CUSTOMER
select * from CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER;
commit;

insert into AD.CONTRACT_CUSTOMER_LEGACY
select * from CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY;
commit;

insert into AD.CUSTOMER
select * from CONTRACTMANAGER_ADM.CUSTOMER;
commit;

insert into AD.CUSTOMER_ESCROW
select * from CONTRACTMANAGER_ADM.CUSTOMER_ESCROW;
commit;

insert into AD.CUSTOMER_PLAN
select * from CONTRACTMANAGER_ADM.CUSTOMER_PLAN;
commit;

insert into AD.CUSTOMER_REPLICATION
select * from CONTRACTMANAGER_ADM.CUSTOMER_REPLICATION;
commit;