CREATE TABLE CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY (

    IDT_CONTRACT_CUSTOMER_LEGACY    NUMBER(20)
    GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE NOCYCLE NOT NULL,
    COD_CUSTOMER				    VARCHAR(50)	                NOT NULL,
  	COD_CONTRACT					VARCHAR(50)		            NOT NULL,
    IND_STATUS                      NUMBER(3)                   NOT NULL,
    DAT_CREATION                    TIMESTAMP DEFAULT SYSDATE   NOT NULL,
    DAT_UPDATE                      TIMESTAMP DEFAULT SYSDATE   NOT NULL,
    FLG_ACTIVE                      NUMBER(1)                   NOT NULL,
    DES_MESSAGE                     VARCHAR (50)                NOT NULL,
    FLG_REGISTER_CUSTOMER           NUMBER(1)                   NOT NULL,
    FLG_VALIDATION_DOCUMENT         NUMBER(1)                   NOT NULL,
    IDT_PAYMENT_GROUP               NUMBER(20)                  NOT NULL,

    CONSTRAINT CONTRACT_CUSTOMER_LEGACY_PK PRIMARY KEY (IDT_CONTRACT_CUSTOMER_LEGACY)
    USING INDEX TABLESPACE TSICONTRACTMANAGER01 INITRANS 10
)   TABLESPACE TSDCONTRACTMANAGER01 INITRANS 10;

COMMENT ON TABLE  CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY                                       IS 'Tabela com os Indicadores de Bandeira + Meio de Pagamento';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.IDT_CONTRACT_CUSTOMER_LEGACY          IS 'Identificador da tabela';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.COD_CUSTOMER                          IS 'Código do lojista';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.COD_CONTRACT                          IS 'Código do contrato';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.IND_STATUS                            IS 'Status do envio do contrato à CERC';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.FLG_ACTIVE                            IS 'Flag que indica se o contrato está ativo';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.DAT_CREATION                          IS 'Data de criação do contrato';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.DAT_UPDATE                            IS 'Data de atualização do contrato';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.IDT_PAYMENT_GROUP                     IS 'Indicadores de Bandeira + Meio de Pagamento';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.DES_MESSAGE                           IS 'Mensagem de sucesso ou erro no processamento';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.FLG_REGISTER_CUSTOMER                 IS 'Verifica se o cadastro do cliente foi realizado com sucesso no Paraty';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY.FLG_VALIDATION_DOCUMENT               IS 'Verifica se o documento do cliente é válido';

ALTER TABLE CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY ADD CONSTRAINT CONTR_CUST_LEG_PAY_GROUP_FK
  FOREIGN KEY (IDT_PAYMENT_GROUP) REFERENCES CONTRACTMANAGER_ADM.PAYMENT_GROUP (IDT_PAYMENT_GROUP) ENABLE NOVALIDATE;

GRANT SELECT,UPDATE,INSERT,DELETE ON CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY TO CONTRACTMANAGERUBR;
GRANT SELECT ON CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY TO MANUT_CONTRACTMANAGER;

CREATE INDEX CONTRACT_CUSTOMER_LEGACY_IDX01 ON CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY(COD_CUSTOMER) INITRANS 12 TABLESPACE TSICONTRACTMANAGER01 ONLINE;
CREATE INDEX CONTRACT_CUSTOMER_LEGACY_IDX02 ON CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY(COD_CONTRACT) INITRANS 12 TABLESPACE TSICONTRACTMANAGER01 ONLINE;
CREATE INDEX CONTRACT_CUSTOMER_LEGACY_IDX03 ON CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER_LEGACY(IDT_PAYMENT_GROUP) INITRANS 12 TABLESPACE TSICONTRACTMANAGER01 ONLINE;
