ALTER TABLE CONTRACTMANAGER_ADM.CUSTOMER_REPLICATION ADD FLG_MIGRATED NUMBER(1) NOT NULL;

COMMENT ON COLUMN CONTRACTMANAGER_ADM.CUSTOMER_REPLICATION.FLG_MIGRATED IS 'Flag que indica se foram criados todos os contratos para o lojista';
