create TABLE CONTRACTMANAGER_ADM.customer_plan (
    IDT_CUSTOMER_PLAN               NUMBER(20)
    GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 NOCACHE NOCYCLE NOT NULL,
	COD_CUSTOMER					VARCHAR(50)				    NOT NULL,
	COD_CONTRACT					VARCHAR(50)				    NOT NULL,
    IND_PAYMENT_PROCESSOR           VARCHAR(30)                 NOT NULL,
    IND_STATUS                      NUMBER(2)                   NOT NULL,
    DAT_CREATION                    TIMESTAMP DEFAULT SYSDATE   NOT NULL,
    DAT_UPDATE                      TIMESTAMP DEFAULT SYSDATE   NOT NULL,
    CONSTRAINT CUSTOMER_PLAN_PK PRIMARY KEY (IDT_CUSTOMER_PLAN)
    USING INDEX TABLESPACE TSICONTRACTMANAGER01 INITRANS 10
) TABLESPACE TSDCONTRACTMANAGER01 INITRANS 10;

COMMENT ON TABLE  CONTRACTMANAGER_ADM.CUSTOMER_PLAN                                       IS 'Tabela de controle de planos de usuários para serem criados contratos';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CUSTOMER_PLAN.IDT_CUSTOMER_PLAN                     IS 'Identificador da tabela';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CUSTOMER_PLAN.COD_CUSTOMER                          IS 'Código do lojista';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CUSTOMER_PLAN.COD_CONTRACT                          IS 'Código do contrato';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CUSTOMER_PLAN.IND_PAYMENT_PROCESSOR                 IS 'Bandeira do cartão de crédito';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CUSTOMER_PLAN.IND_STATUS                            IS 'Status do envio do contrato à CERC';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CUSTOMER_PLAN.DAT_CREATION                          IS 'Data de criação do contrato';
COMMENT ON COLUMN CONTRACTMANAGER_ADM.CUSTOMER_PLAN.DAT_UPDATE                            IS 'Data de atualização do contrato';

ALTER TABLE CONTRACTMANAGER_ADM.CUSTOMER_PLAN ADD CONSTRAINT CUSTOMER_PLAN_COD_CONTRACT_FK FOREIGN KEY ( COD_CONTRACT )
        REFERENCES CONTRACTMANAGER_ADM.CONTRACT_CUSTOMER ( COD_CONTRACT );

GRANT SELECT,UPDATE,INSERT,DELETE ON CONTRACTMANAGER_ADM.CUSTOMER_PLAN TO CONTRACTMANAGERUBR;
GRANT SELECT ON CONTRACTMANAGER_ADM.CUSTOMER_PLAN TO MANUT_CONTRACTMANAGER;
