-- Casos Duplicados
SELECT COD_EVENT_CORRELATION
,IND_EVENT_TYPE
,COUNT(*)
FROM SAFEPAY_ADM.CM_EVENT_LOG
GROUP BY COD_EVENT_CORRELATION
,IND_EVENT_TYPE
HAVING COUNT(*) > 1;

-- Tabela
SELECT e.owner
, e.segment_name
, ROUND(sum(e.bytes)/1024/1024,2) "SIZE (MB)" 
, ROUND(sum(e.bytes)/1024/1024/1024,2) "SIZE (GB)" 
, ROUND(sum(e.bytes)/1024/1024/1024/1024,2) "SIZE (TB)" 
FROM dba_extents e 
where e.owner = 'SAFEPAY_ADM' 
and E.SEGMENT_NAME = 'CM_EVENT_LOG' 
GROUP BY e.owner
, e.segment_name 
;


-- Tablespace
SELECT DDF.TABLESPACE_NAME
,ROUND(DDF.BYTES/1024/1024/1024/1024,2)"TAMANHO ATUAL (TB)"
,ROUND(DDF.MAXBYTES/1024/1024/1024/1024,2) "TAMANHO MAXIMO (TB)"
,ROUND(USED_PERCENT,2) USED_PERCENT
FROM DBA_DATA_FILES DDF
INNER JOIN DBA_TABLESPACE_USAGE_METRICS DTUM
ON DDF.TABLESPACE_NAME = DTUM.TABLESPACE_NAME
WHERE DDF.TABLESPACE_NAME = 'TSDCMEVENTLOG02_2';

-- Validação de alteração da UK
SELECT CASE WHEN (SELECT COUNT(*) 
                  FROM ALL_CONSTRAINTS 
                  WHERE OWNER = 'SAFEPAY_ADM' 
                  AND TABLE_NAME = 'CM_EVENT_LOG' 
                  AND CONSTRAINT_TYPE = 'U') = 0 THEN 'NOK - NAO EXISTE'
                  
            WHEN (SELECT CASE WHEN STATUS <> 'ENABLED' THEN 'NOK' ELSE 'OK' END 
                  FROM ALL_CONSTRAINTS 
                  WHERE OWNER = 'SAFEPAY_ADM' 
                  AND TABLE_NAME = 'CM_EVENT_LOG' 
                  AND CONSTRAINT_TYPE = 'U') <> 'OK' THEN 'NOK - DESABILITADA'
                  
            WHEN (SELECT CASE WHEN TRUNC(LAST_CHANGE) = TRUNC(SYSDATE) THEN 'NOK' ELSE 'OK' END 
                  FROM ALL_CONSTRAINTS 
                  WHERE OWNER = 'SAFEPAY_ADM' 
                  AND TABLE_NAME = 'CM_EVENT_LOG' 
                  AND CONSTRAINT_TYPE = 'U') <> 'OK' THEN 'NOK - ALTERADA'  
       ELSE 'OK'     
       END VALIDA_UK
FROM DUAL;