COL TABLE_OWNER FOR A20
COL TABLE_NAME FOR A20
COL TABLESPACE_NO_PART FOR A20
COL TABLESPACE_PART FOR A20
COL TABLESPACE_DEF_PART FOR A20
COL INDEX_NAME FOR A30
COL LOB_OWNER FOR A20
COL LOB_NAME FOR A20

VARIABLE NOME_OWNER VARCHAR2(128)
VARIABLE NOME_TABELA VARCHAR2(128)
EXEC :NOME_OWNER := SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM';
EXEC :NOME_TABELA := '&NOME_TABELA';

TTITLE LEFT '--- DADOS TABELA ----'
SELECT COALESCE(TAB_NO_PART.TABLE_OWNER,TAB_PART.TABLE_OWNER) AS TABLE_OWNER
,COALESCE(TAB_NO_PART.TABLE_NAME,TAB_PART.TABLE_NAME) AS TABLE_NAME
,NVL(TAB_NO_PART.TABLESPACE_NO_PART,'NAO E PARTICIONADA!') AS TABLESPACE_NO_PART
,NVL(TAB_PART.TABLESPACE_PART,'NAO E PARTICIONADA!') AS TABLESPACE_PART
,NVL(TAB_DEF.TABLESPACE_DEF_PART,'NAO E PARTICIONADA!') AS TABLESPACE_DEF_PART
FROM 
(SELECT OWNER AS TABLE_OWNER,TABLE_NAME,TABLESPACE_NAME AS TABLESPACE_NO_PART
FROM DBA_TABLES
WHERE OWNER = :NOME_OWNER
AND TABLE_NAME = :NOME_TABELA) TAB_NO_PART
CROSS JOIN
(SELECT DISTINCT TABLE_OWNER, TABLE_NAME, TABLESPACE_NAME AS TABLESPACE_PART
FROM DBA_TAB_PARTITIONS
WHERE TABLE_OWNER = :NOME_OWNER
AND TABLE_NAME = :NOME_TABELA) TAB_PART
CROSS JOIN
(SELECT OWNER AS TABLE_OWNER, TABLE_NAME, DEF_TABLESPACE_NAME AS TABLESPACE_DEF_PART
FROM DBA_PART_TABLES
WHERE OWNER = :NOME_OWNER
AND TABLE_NAME = :NOME_TABELA) TAB_DEF;

TTITLE LEFT '---- DADOS INDICES ----'
SELECT DISTINCT COALESCE(INDEX_NO_PART.INDEX_OWNER,INDEX_PART.INDEX_OWNER) AS TABLE_OWNER
,COALESCE(INDEX_NO_PART.TABLE_NAME,INDEX_PART.TABLE_NAME) AS TABLE_NAME
,COALESCE(INDEX_NO_PART.INDEX_NAME,INDEX_PART.INDEX_NAME) AS INDEX_NAME
,NVL(INDEX_NO_PART.TABLESPACE_NO_PART,'NAO E PARTICIONADO!') AS TABLESPACE_NO_PART
,NVL(INDEX_PART.TABLESPACE_PART,'NAO E PARTICIONADO!') AS TABLESPACE_PART
,NVL(INDEX_DEF.TABLESPACE_DEF_PART,'NAO E PARTICIONADO!') AS TABLESPACE_DEF_PART
FROM 
(SELECT OWNER AS INDEX_OWNER, TABLE_NAME, INDEX_NAME, TABLESPACE_NAME AS TABLESPACE_NO_PART
FROM DBA_INDEXES
WHERE PARTITIONED = 'NO'
AND OWNER = :NOME_OWNER
AND TABLE_NAME = :NOME_TABELA) INDEX_NO_PART
CROSS JOIN
(SELECT DISTINCT IP.INDEX_OWNER, :NOME_TABELA AS TABLE_NAME, IP.INDEX_NAME, IP.TABLESPACE_NAME AS TABLESPACE_PART
FROM DBA_IND_PARTITIONS IP
WHERE IP.INDEX_OWNER = :NOME_OWNER
AND IP.INDEX_NAME IN (SELECT I.INDEX_NAME FROM DBA_INDEXES I 
                      WHERE I.OWNER = IP.INDEX_OWNER AND I.PARTITIONED = 'YES' AND I.TABLE_NAME = :NOME_TABELA )) INDEX_PART
CROSS JOIN
(SELECT OWNER AS INDEX_OWNER, TABLE_NAME, INDEX_NAME, DEF_TABLESPACE_NAME AS TABLESPACE_DEF_PART
FROM DBA_PART_INDEXES
WHERE OWNER = :NOME_OWNER
AND TABLE_NAME = :NOME_TABELA) INDEX_DEF;

TTITLE LEFT '---- DADOS LOBS ----'
SELECT COALESCE(LOB_NO_PART.LOB_OWNER,LOB_PART.LOB_OWNER) AS LOB_OWNER
,COALESCE(LOB_NO_PART.TABLE_NAME,LOB_PART.TABLE_NAME) AS TABLE_NAME
,COALESCE(LOB_NO_PART.COLUMN_NAME,LOB_PART.COLUMN_NAME) AS LOB_NAME
,NVL(LOB_NO_PART.TABLESPACE_NO_PART,'NAO E PARTICIONADA!') AS TABLESPACE_NO_PART
,NVL(LOB_PART.TABLESPACE_PART,'NAO E PARTICIONADA!') AS TABLESPACE_PART
,NVL(LOB_DEF.TABLESPACE_DEF_PART,'NAO E PARTICIONADA!') AS TABLESPACE_DEF_PART
FROM 
(SELECT OWNER AS LOB_OWNER, TABLE_NAME, COLUMN_NAME, TABLESPACE_NAME AS TABLESPACE_NO_PART
FROM DBA_LOBS
WHERE OWNER = :NOME_OWNER
AND TABLE_NAME = :NOME_TABELA) LOB_NO_PART
CROSS JOIN
(SELECT DISTINCT TABLE_OWNER AS LOB_OWNER, TABLE_NAME, COLUMN_NAME, TABLESPACE_NAME AS TABLESPACE_PART
FROM DBA_LOB_PARTITIONS
WHERE TABLE_OWNER = :NOME_OWNER
AND TABLE_NAME = :NOME_TABELA) LOB_PART
CROSS JOIN
(SELECT TABLE_OWNER AS LOB_OWNER, TABLE_NAME, COLUMN_NAME, DEF_TABLESPACE_NAME AS TABLESPACE_DEF_PART
FROM DBA_PART_LOBS
WHERE TABLE_OWNER = :NOME_OWNER
AND TABLE_NAME = :NOME_TABELA) LOB_DEF;
