  SELECT C.OWNER CONSTRAINT_OWNER
         ,C.TABLE_NAME
         ,C.CONSTRAINT_NAME
         ,LISTAGG(CC.COLUMN_NAME,', ') COLUMNS_NAME
         ,CR.OWNER OWNER_R
         ,CR.TABLE_NAME TABLE_NAME_R
  FROM DBA_CONSTRAINTS C 
  INNER JOIN DBA_CONS_COLUMNS CC
  ON C.OWNER = CC.OWNER
  AND C.TABLE_NAME = CC.TABLE_NAME
  AND C.CONSTRAINT_NAME = CC.CONSTRAINT_NAME
  INNER JOIN DBA_CONSTRAINTS CR
  ON CR.OWNER = C.R_OWNER
  AND CR.CONSTRAINT_NAME = C.R_CONSTRAINT_NAME 
  WHERE C.OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
  AND (C.TABLE_NAME = 'REG_REGISTERED_CONTRACT_BALLAST' OR CR.TABLE_NAME = 'REG_REGISTERED_CONTRACT_BALLAST')
  AND C.CONSTRAINT_TYPE = 'R'
  GROUP BY C.OWNER
        ,C.TABLE_NAME
        ,C.CONSTRAINT_NAME
        ,CR.OWNER
        ,CR.TABLE_NAME; 