-- EXECUTE ESSA QUERY PARA VERIFICAR COMO DEVE SER O NOME DO USUÁRIO
SELECT SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50) USER_MANUT FROM DUAL;

-- CRIACAO DO PROFILE / SCHEMA / USER, SUBSTITUA '<USUARIO>' PELO RESULTADO DA QUERY ACIMA
CREATE PROFILE PR_MANUT_<USUARIO>
LIMIT
COMPOSITE_LIMIT DEFAULT
SESSIONS_PER_USER 50
CPU_PER_SESSION DEFAULT
CPU_PER_CALL DEFAULT
LOGICAL_READS_PER_SESSION DEFAULT
LOGICAL_READS_PER_CALL DEFAULT
IDLE_TIME 30
CONNECT_TIME DEFAULT
PRIVATE_SGA DEFAULT
FAILED_LOGIN_ATTEMPTS UNLIMITED
PASSWORD_LIFE_TIME UNLIMITED
PASSWORD_REUSE_TIME UNLIMITED
PASSWORD_REUSE_MAX UNLIMITED
PASSWORD_VERIFY_FUNCTION NULL
PASSWORD_LOCK_TIME UNLIMITED
PASSWORD_GRACE_TIME UNLIMITED
INACTIVE_ACCOUNT_TIME DEFAULT;

CREATE USER MANUT_<USUARIO> IDENTIFIED BY "MANUT_<USUARIO>" 
DEFAULT TABLESPACE TSD<USUARIO>01
TEMPORARY TABLESPACE TEMP 
PROFILE PR_MANUT_<USUARIO>;

GRANT CREATE SESSION TO MANUT_<USUARIO>;
GRANT CONNECT, RESOURCE TO MANUT_<USUARIO>;

-- GRANT DE SELECT PARA AS TABELAS, SE JÁ EXISTEM
SELECT 'GRANT SELECT ON '||OWNER||'.'||TABLE_NAME||' TO MANUT_'||SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||';'
FROM DBA_TABLES
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM';