SELECT I.OWNER
,I.INDEX_NAME
,I.TABLE_NAME
,I.PARTITIONED
,I.UNIQUENESS
,I.VISIBILITY
,ROUND(SI.BYTES/1024/1024/1024,2) TAM_GB
,ROUND(SI.BYTES/1024/1024/1024/1024,2) TAM_TB
,LISTAGG(IC.COLUMN_NAME,',') WITHIN GROUP (ORDER BY IC.COLUMN_POSITION) COLUMNS_INDEX 
FROM DBA_INDEXES I 
INNER JOIN (SELECT S.OWNER
                  ,S.SEGMENT_NAME
                  ,SUM(S.BYTES) BYTES
            FROM DBA_SEGMENTS S
            GROUP BY S.OWNER
                    ,S.SEGMENT_NAME) SI
ON I.OWNER = SI.OWNER
AND I.INDEX_NAME = SI.SEGMENT_NAME
INNER JOIN DBA_IND_COLUMNS IC
ON I.OWNER  = IC.INDEX_OWNER
AND I.TABLE_NAME = IC.TABLE_NAME
AND I.INDEX_NAME = IC.INDEX_NAME
WHERE I.OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND I.INDEX_NAME = 'CONTRACTUAL_EFFECT_IDX01'
--AND I.TABLE_NAME = 'CONTRACTUAL_EFFECT'
GROUP BY I.OWNER
,I.INDEX_NAME
,I.TABLE_NAME
,I.PARTITIONED
,I.UNIQUENESS
,I.VISIBILITY
,SI.BYTES
ORDER BY 6 DESC;
