SELECT DISTINCT   
    UPPER(SYS_CONTEXT('USERENV','INSTANCE_NAME')) || ' / ' || UPPER(SYS_CONTEXT('USERENV','SERVER_HOST')) AS DES_HOSTNAME,
    CC.OWNER AS DES_SCHEMA_OWNER,
    O.OBJECT_TYPE AS DES_OBJECT_TYPE,
    CC.TABLE_NAME AS DES_TABLE_NAME,
    CC.COLUMN_NAME AS DES_COLUMN_NAME,
    CO.DATA_TYPE AS DES_COLUMN_DATA_TYPE,
    CASE WHEN CO.DATA_PRECISION IS NULL THEN CO.DATA_LENGTH
    ELSE CO.DATA_PRECISION
    END AS DAT_LENGTH,
    CC.COMMENTS AS DES_ORIGIN_TAB_COMMENTS,
    'N' AS FLG_PROCESSED
  FROM DBA_COL_COMMENTS CC
  INNER JOIN DBA_USERS U ON U.USERNAME = CC.OWNER  
  INNER JOIN DBA_TAB_COLUMNS CO ON CO.COLUMN_NAME = CC.COLUMN_NAME AND CO.TABLE_NAME = CC.TABLE_NAME AND CO.OWNER = CC.OWNER  
  INNER JOIN DBA_OBJECTS O ON O.OBJECT_NAME = CC.TABLE_NAME   
  LEFT JOIN REDACTION_POLICIES RP ON RP.OBJECT_OWNER = CC.OWNER AND RP.OBJECT_NAME = CC.TABLE_NAME
  LEFT JOIN REDACTION_COLUMNS RC ON RC.OBJECT_OWNER = CC.OWNER AND RC.OBJECT_NAME = CC.TABLE_NAME AND RC.COLUMN_NAME = CC.COLUMN_NAME
  WHERE O.OBJECT_TYPE IN ('TABLE','MATERIALIZED VIEW')
    AND U.ACCOUNT_STATUS = 'OPEN'
    AND CC.TABLE_NAME NOT LIKE '%$%'