DECLARE
  resource_busy EXCEPTION;
  PRAGMA EXCEPTION_INIT(resource_busy, -00054);
  naoexecutou BOOLEAN := TRUE;
  VCOUNT NUMBER := 0;
  C_ROLLBACK  VARCHAR2(2000) := 'DELETE FROM safepay_adm.safepay_parameter WHERE NAM_PARAMETER IN 
  (''BANCO_SEGURO_USER_ID'',''BANCO_SEGURO_LIQUIDATION_RATE_LIMIT'')';
  C_SQL   VARCHAR2(2000) := 'INSERT INTO safepay_adm.safepay_parameter (IDT_PARAMETER, NAM_PARAMETER, VAL_PARAMETER, DAT_UPDATE) 
  VALUES (SQ_SAFEPARA_IDT.NEXTVAL, ''BANCO_SEGURO_USER_ID'', ''10983571'', SYSDATE)';
  C_SQL2  VARCHAR2(2000) := 'INSERT INTO safepay_adm.safepay_parameter (IDT_PARAMETER, NAM_PARAMETER, VAL_PARAMETER, DAT_UPDATE) 
  VALUES (SQ_SAFEPARA_IDT.NEXTVAL, ''BANCO_SEGURO_LIQUIDATION_RATE_LIMIT'', ''1.00'', SYSDATE)';  
BEGIN
SELECT COUNT(1) INTO VCOUNT FROM safepay_adm.safepay_parameter WHERE NAM_PARAMETER IN ('BANCO_SEGURO_USER_ID','BANCO_SEGURO_LIQUIDATION_RATE_LIMIT');
	IF VCOUNT = 0 THEN
		WHILE naoexecutou
		LOOP	
			begin 
				EXECUTE IMMEDIATE C_SQL;
				EXECUTE IMMEDIATE C_SQL2;
				naoexecutou := FALSE;
				DBMS_OUTPUT.PUT_LINE('PARAMETROS CRIADOS COM SUCESSO !');
				DBMS_OUTPUT.PUT_LINE('SCRIPT ROLLBACK : '||C_ROLLBACK);
				COMMIT;
			EXCEPTION
				WHEN resource_busy THEN
                    DBMS_SESSION.SLEEP(0.25);
				WHEN OTHERS THEN
					RAISE;
			END;
		END LOOP;
	ELSE 
dbms_output.put_line('*** Parametros existentes: ' || sys_context('USERENV','INSTANCE_NAME') || ' / ' || sys_context('USERENV','SERVER_HOST'));	
	END IF;	  
END;
/
