ALTER SESSION SET NLS_DATE_FORMAT = 'YYYY-MM-DD HH24:MI:SS';

SELECT AVG(COUNT(1)) AS MEDIA, MAX(COUNT(1)) AS MAXIMO
   FROM DBA_HIST_ACTIVE_SESS_HISTORY HIST,
        DBA_USERS USR
  WHERE USR.USERNAME = 'ATMUBR' 
    AND HIST.USER_ID = USR.USER_ID
    AND SAMPLE_TIME BETWEEN TO_DATE('01/01/2020 08:00:00', 'DD/MM/YYYY HH24:MI:SS') AND TO_DATE('01/02/2020 09:00:00', 'DD/MM/YYYY HH24:MI:SS')
  GROUP BY SAMPLE_TIME  ;