SET SERVEROUTPUT ON

DECLARE

  V_INCOMING    VARCHAR2(32767);
  V_RETURN_HOLD VARCHAR2(4000);
  V_DDL1 VARCHAR2(4000);
  V_DDL2 VARCHAR2(4000);
    
CURSOR C_PARTS IS

   SELECT TP.TABLE_OWNER	
		  ,TP.TABLE_NAME
		  ,TP.PARTITION_NAME
          ,TP.TABLESPACE_NAME
          ,TP.HIGH_VALUE
          ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
          ,ROUND(S.BYTES/1024/1024/1024,2) SIZE_GB		
          ,ROUND(S.BYTES/1024/1024/1024/1024,2) SIZE_TB	
	FROM DBA_TAB_PARTITIONS TP	    
    INNER JOIN DBA_SEGMENTS S		
    ON S.OWNER = TP.TABLE_OWNER 		
    AND S.SEGMENT_NAME = TP.TABLE_NAME		
    AND S.PARTITION_NAME = TP.PARTITION_NAME		
	WHERE TP.TABLE_OWNER = 'SETTLEMENTCONTRACT_ADM'	
	AND TP.TABLE_NAME = 'TTO_RECORD'
    AND TP.TABLESPACE_NAME = 'TSDSETTLEMENTCONTRACT01'
    ORDER BY TP.PARTITION_POSITION;
	
CURSOR C_INDS (P_OWNER VARCHAR, P_TABLE_NAME VARCHAR, P_PARTITION_NAME VARCHAR) IS	
   SELECT  TP.TABLE_OWNER	
          ,IP.INDEX_NAME
          ,TP.PARTITION_POSITION          
		  ,TP.PARTITION_NAME
          ,IP.TABLESPACE_NAME
          ,TP.HIGH_VALUE
          ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
          ,ROUND(S.BYTES/1024/1024/1024,2) SIZE_GB		
          ,ROUND(S.BYTES/1024/1024/1024/1024,2) SIZE_TB	
	FROM DBA_TAB_PARTITIONS TP	    
    INNER JOIN DBA_IND_PARTITIONS IP
    ON TP.TABLE_OWNER = IP.INDEX_OWNER
    AND TP.PARTITION_NAME = IP.PARTITION_NAME
    INNER JOIN DBA_SEGMENTS S		
    ON S.OWNER = TP.TABLE_OWNER 		
    AND S.SEGMENT_NAME = TP.TABLE_NAME		
    AND S.PARTITION_NAME = TP.PARTITION_NAME		
	WHERE TP.TABLE_OWNER = P_OWNER
	AND TP.TABLE_NAME = P_TABLE_NAME
	AND TP.PARTITION_NAME = P_PARTITION_NAME
    AND IP.TABLESPACE_NAME = 'TSISETTLEMENTCONTRACT01'
    ORDER BY TP.PARTITION_POSITION,IP.INDEX_NAME;

BEGIN

  FOR R1 IN C_PARTS LOOP  

    SELECT HIGH_VALUE 
    INTO V_INCOMING 
    FROM ALL_TAB_PARTITIONS
    WHERE TABLE_OWNER = R1.TABLE_OWNER
      AND TABLE_NAME = R1.TABLE_NAME
      AND PARTITION_NAME = R1.PARTITION_NAME;
      
     V_RETURN_HOLD := SUBSTR(V_INCOMING,1,4000);
     
     V_DDL1 := '-- '||R1.TABLE_NAME||' -- '||R1.PARTITION_NAME||' -- '||V_RETURN_HOLD||' -- '||R1.SIZE_GB||' GB '||CHR(10)||'ALTER TABLE '|| R1.TABLE_OWNER||'.'||R1.TABLE_NAME||' MOVE PARTITION '||R1.PARTITION_NAME||' TABLESPACE TSDSETTLEMENTCONTRACT05 PARALLEL 12 ONLINE;';
 
     DBMS_OUTPUT.PUT_LINE(V_DDL1);	
 
     FOR R2 IN C_INDS(R1.TABLE_OWNER,R1.TABLE_NAME,R1.PARTITION_NAME) LOOP
	 
       V_DDL2 := 'ALTER INDEX '||R1.TABLE_OWNER||'.'||R2.INDEX_NAME||' REBUILD PARTITION '||R1.PARTITION_NAME||' TABLESPACE TSISETTLEMENTCONTRACT02 PARALLEL 12 ONLINE;';
	   
       DBMS_OUTPUT.PUT_LINE(V_DDL2);	   
	   
     END LOOP;
    
  END LOOP;
    
END;
/


    SELECT TP.TABLE_OWNER	
		  ,TP.TABLE_NAME
		  ,TP.PARTITION_NAME
          ,TP.HIGH_VALUE
          ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
          ,ROUND(S.BYTES/1024/1024/1024,2) SIZE_GB		
          ,ROUND(S.BYTES/1024/1024/1024/1024,2) SIZE_TB	
          ,'EXEC DBMS_STATS.GATHER_TABLE_STATS( OWNNAME=>'''|| TP.TABLE_OWNER||''', TABNAME=>'''||TP.TABLE_NAME||''', PARTNAME=>'''||TP.PARTITION_NAME||''', ESTIMATE_PERCENT => dbms_stats.auto_sample_size, DEGREE => 12, GRANULARITY => ''AUTO'', NO_INVALIDATE => TRUE ); ' SCRIPT
	FROM DBA_TAB_PARTITIONS TP	    
    INNER JOIN DBA_SEGMENTS S		
    ON S.OWNER = TP.TABLE_OWNER 		
    AND S.SEGMENT_NAME = TP.TABLE_NAME		
    AND S.PARTITION_NAME = TP.PARTITION_NAME		
	WHERE TP.TABLE_OWNER = 'RECEIVABLES_ADM'	
	AND TP.TABLE_NAME = 'SUSPENSION_OUTBOX' -- 7 dias de retenção
    --AND ROUND(S.BYTES/1024/1024/1024/1024,2) <> 0
    ORDER BY TP.PARTITION_POSITION DESC;
    
    SELECT IP.INDEX_OWNER	
		  ,IP.INDEX_NAME
		  ,IP.PARTITION_NAME
          ,IP.HIGH_VALUE
          ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
          ,ROUND(S.BYTES/1024/1024/1024,2) SIZE_GB		
          ,ROUND(S.BYTES/1024/1024/1024/1024,2) SIZE_TB	
          ,'EXEC DBMS_STATS.GATHER_INDEX_STATS( OWNNAME=>'''|| IP.INDEX_OWNER||''', INDNAME=>'''||IP.INDEX_NAME||''', PARTNAME=>'''||S.PARTITION_NAME||''', ESTIMATE_PERCENT => dbms_stats.auto_sample_size, DEGREE => 12, GRANULARITY => ''AUTO'', NO_INVALIDATE => TRUE ); ' SCRIPT
	FROM DBA_IND_PARTITIONS IP	    
    INNER JOIN DBA_SEGMENTS S		
    ON S.OWNER = IP.INDEX_OWNER 		
    AND S.SEGMENT_NAME = IP.INDEX_NAME		
    AND S.PARTITION_NAME = IP.PARTITION_NAME		
	WHERE IP.INDEX_OWNER = 'RECEIVABLES_ADM'	
	AND IP.INDEX_NAME IN (SELECT INDEX_NAME FROM DBA_INDEXES WHERE OWNER = 'RECEIVABLES_ADM' AND TABLE_NAME = 'SUSPENSION_OUTBOX') -- 7 dias de retenção
    --AND ROUND(S.BYTES/1024/1024/1024/1024,2) <> 0
    AND S.SEGMENT_TYPE = 'INDEX PARTITION'
    ORDER BY IP.PARTITION_POSITION DESC;    
    
    
SET SERVEROUTPUT ON

DECLARE

  V_INCOMING    VARCHAR2(32767);
  V_RETURN_HOLD VARCHAR2(4000);
  V_DDL1 VARCHAR2(4000);
  V_DDL2 VARCHAR2(4000);
    
CURSOR C_PARTS IS

   SELECT TP.TABLE_OWNER	
		  ,TP.TABLE_NAME
		  ,TP.PARTITION_NAME
          ,TP.TABLESPACE_NAME
          ,TP.HIGH_VALUE
          ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
          ,ROUND(S.BYTES/1024/1024/1024,2) SIZE_GB		
          ,ROUND(S.BYTES/1024/1024/1024/1024,2) SIZE_TB	
	FROM DBA_TAB_PARTITIONS TP	    
    INNER JOIN DBA_SEGMENTS S		
    ON S.OWNER = TP.TABLE_OWNER 		
    AND S.SEGMENT_NAME = TP.TABLE_NAME		
    AND S.PARTITION_NAME = TP.PARTITION_NAME		
	WHERE TP.TABLE_OWNER = 'RECEIVABLES_ADM'	
	AND TP.TABLE_NAME = 'RECEIVABLE_UNIT_INTERNAL_OUTBOX'
    ORDER BY TP.PARTITION_POSITION;
	
CURSOR C_INDS (P_OWNER VARCHAR, P_TABLE_NAME VARCHAR, P_PARTITION_NAME VARCHAR) IS	
   SELECT  TP.TABLE_OWNER AS INDEX_OWNER	
          ,IP.INDEX_NAME
          ,TP.PARTITION_POSITION          
		  ,TP.PARTITION_NAME
          ,IP.TABLESPACE_NAME
          ,TP.HIGH_VALUE
          ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
          ,ROUND(S.BYTES/1024/1024/1024,2) SIZE_GB		
          ,ROUND(S.BYTES/1024/1024/1024/1024,2) SIZE_TB	
	FROM DBA_TAB_PARTITIONS TP	    
    INNER JOIN DBA_IND_PARTITIONS IP
    ON TP.TABLE_OWNER = IP.INDEX_OWNER
    AND TP.PARTITION_NAME = IP.PARTITION_NAME
    INNER JOIN DBA_SEGMENTS S		
    ON S.OWNER = TP.TABLE_OWNER 		
    AND S.SEGMENT_NAME = TP.TABLE_NAME		
    AND S.PARTITION_NAME = TP.PARTITION_NAME		
	WHERE TP.TABLE_OWNER = P_OWNER
	AND TP.TABLE_NAME = P_TABLE_NAME
	AND TP.PARTITION_NAME = P_PARTITION_NAME
    ORDER BY TP.PARTITION_POSITION,IP.INDEX_NAME;

BEGIN

  FOR R1 IN C_PARTS LOOP  

     V_DDL1 := 'EXEC DBMS_STATS.GATHER_TABLE_STATS( OWNNAME=>'''|| R1.TABLE_OWNER||''', TABNAME=>'''||R1.TABLE_NAME||''', PARTNAME=>'''||R1.PARTITION_NAME||''', ESTIMATE_PERCENT => dbms_stats.auto_sample_size, DEGREE => 12, GRANULARITY => ''AUTO'', NO_INVALIDATE => TRUE ); ';
 
     DBMS_OUTPUT.PUT_LINE(V_DDL1);	
 
     FOR R2 IN C_INDS(R1.TABLE_OWNER,R1.TABLE_NAME,R1.PARTITION_NAME) LOOP
	 
       V_DDL2 := 'EXEC DBMS_STATS.GATHER_INDEX_STATS( OWNNAME=>'''|| R2.INDEX_OWNER||''', INDNAME=>'''||R2.INDEX_NAME||''', PARTNAME=>'''||R2.PARTITION_NAME||''', ESTIMATE_PERCENT => dbms_stats.auto_sample_size, DEGREE => 12, GRANULARITY => ''AUTO'', NO_INVALIDATE => TRUE ); ';
	   
       DBMS_OUTPUT.PUT_LINE(V_DDL2);	   
	   
     END LOOP;
    
  END LOOP;
    
END;
/    
