CREATE OR REPLACE PROCEDURE RISKDATASOURCEAPI_ADM.P_PURGE_SWITCH_AUTHORIZATION(
		P_DAY 	 		INTEGER,  -- Dias para exclusão
        P_COMMIT_LINES  INTEGER   -- Quantidades de linhas que serão excluídas por bloco
)
IS
    CURSOR C_CURSOR
    IS
        SELECT  TRANSACTION_CODE
        FROM    RISKDATASOURCEAPI_ADM.SWITCH_AUTHORIZATION
        WHERE 	DAT_CREATION <= (SYSDATE - P_DAY);

    TYPE TYPE_CURSOR IS TABLE OF C_CURSOR%ROWTYPE INDEX BY BINARY_INTEGER;
    R_CURSOR  TYPE_CURSOR;
BEGIN

    OPEN C_CURSOR;
    LOOP
        FETCH C_CURSOR BULK COLLECT INTO R_CURSOR LIMIT P_COMMIT_LINES;
        EXIT WHEN R_CURSOR.COUNT = 0;

        FORALL I IN 1 .. R_CURSOR.COUNT

            DELETE 	FROM RISKDATASOURCEAPI_ADM.SWITCH_AUTHORIZATION
			WHERE 	TRANSACTION_CODE = R_CURSOR(I).TRANSACTION_CODE;

       COMMIT;
    END LOOP C_CURSOR;
    CLOSE C_CURSOR;
EXCEPTION
WHEN OTHERS THEN
      RAISE_APPLICATION_ERROR(-20999,'ATENÇÃO! Falha ao apagar os registros!', FALSE);
      ROLLBACK;
END;
/

GRANT EXECUTE ON RISKDATASOURCEAPI_ADM.P_PURGE_SWITCH_AUTHORIZATION TO RISKDATASOURCEAPIUBR;