SELECT TP.TABLE_OWNER	
	  ,TP.TABLE_NAME
	  ,TP.PARTITION_NAME
      ,TP.HIGH_VALUE DATA_PARTITION
      ,TP.COMPRESSION
      ,TP.COMPRESS_FOR      
      ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
FROM DBA_TAB_PARTITIONS TP	    
INNER JOIN DBA_SEGMENTS S		
ON S.OWNER = TP.TABLE_OWNER 		
AND S.SEGMENT_NAME = TP.TABLE_NAME		
AND S.PARTITION_NAME = TP.PARTITION_NAME		
WHERE TP.TABLE_OWNER = 'RECEIVABLES_ADM'	
AND TP.TABLE_NAME = 'RECEIVABLE_UNIT_INTERNAL'
ORDER BY TP.PARTITION_POSITION;  
  
SELECT PI.OWNER
      ,PI.TABLE_NAME
	  ,IP.INDEX_NAME
	  ,IP.PARTITION_NAME DATA_PARTITION
      ,IP.HIGH_VALUE
      ,IP.COMPRESSION
      ,ROUND(S.BYTES/1024/1024,2) SIZE_MB			
FROM DBA_PART_INDEXES PI
INNER JOIN DBA_IND_PARTITIONS IP
ON IP.INDEX_OWNER = PI.OWNER
AND IP.INDEX_NAME = PI.INDEX_NAME
INNER JOIN DBA_SEGMENTS S		
ON S.OWNER = IP.INDEX_OWNER 		
AND S.SEGMENT_NAME = IP.INDEX_NAME		
AND S.PARTITION_NAME = IP.PARTITION_NAME	
WHERE PI.OWNER = 'RECEIVABLES_ADM'
AND PI.TABLE_NAME = 'RECEIVABLE_UNIT_INTERNAL'
ORDER BY IP.PARTITION_POSITION,IP.INDEX_NAME;	

SELECT LP.TABLE_OWNER
	  ,LP.TABLE_NAME
	  ,LP.COLUMN_NAME
      ,TP.HIGH_VALUE DATA_PARTITION	  
      ,LP.COMPRESSION
      ,ROUND(S.BYTES/1024/1024) TAM_MB
FROM DBA_LOB_PARTITIONS LP
INNER JOIN DBA_TAB_PARTITIONS TP
ON LP.TABLE_OWNER = TP.TABLE_OWNER
AND LP.TABLE_NAME = TP.TABLE_NAME		
AND LP.PARTITION_NAME = TP.PARTITION_NAME		
INNER JOIN DBA_SEGMENTS S
ON LP.TABLE_OWNER = S.OWNER
AND LP.LOB_NAME = S.SEGMENT_NAME
AND LP.LOB_PARTITION_NAME = S.PARTITION_NAME
WHERE LP.TABLE_OWNER = 'RECEIVABLES_ADM'
AND LP.TABLE_NAME = 'RECEIVABLE_UNIT_EXTERNAL_OUTBOX'
ORDER BY LP.PARTITION_POSITION,LP.COMPRESSION;