-- detalhes do cadastro do expurgo
SELECT P.DES_TABLE_OWNER,P.DES_TABLE_NAME,P.FLG_ACTIVE,P.DES_CRON_EXPRESSION,PP.NUM_RETENTION_VALUE,PP.DES_MEASUREMENT_UNIT
FROM THANATOS_ADM.PURGE P
INNER JOIN THANATOS_ADM.PURGE_PERIOD PP
ON P.IDT_PURGE_PERIOD = PP.IDT_PURGE_PERIOD
WHERE P.DES_TABLE_OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND P.DES_TABLE_NAME = 'CCE_CHANGE_EVENT_SCHEDULE';


-- log do expurgo da tabela
SELECT PL.IDT_PURGE_LOG,PL.DES_OWNER,PL.DES_TABLE_NAME,PL.DAT_BEGIN,PL.DAT_END,PLS.DES_LOG_STATUS
FROM THANATOS_ADM.PURGE_LOG PL
INNER JOIN THANATOS_ADM.PURGE_LOG_STATUS PLS
ON PL.IDT_PURGE_LOG_STATUS = PLS.IDT_PURGE_LOG_STATUS
WHERE PL.DES_OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND PL.DES_TABLE_NAME = 'CCE_CHANGE_EVENT_SCHEDULE'
ORDER BY 4 DESC;

-- log detalhado do expurgo da tabela
SELECT PLD.DES_MESSAGE
from THANATOS_ADM.PURGE_LOG_DETAIL PLD
WHERE PLD.IDT_PURGE_LOG = (SELECT MAX(PL.IDT_PURGE_LOG) 
						   FROM THANATOS_ADM.PURGE_LOG PL 
						   WHERE PL.DES_OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
						   AND PL.DES_TABLE_NAME = 'CCE_CHANGE_EVENT_SCHEDULE')
ORDER BY PLD.DAT_CREATION DESC;


-- partições restantes da tabela
SELECT TP.TABLE_NAME,TP.HIGH_VALUE
FROM DBA_TAB_PARTITIONS TP
WHERE TP.TABLE_OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND TP.TABLE_NAME = 'CCE_CHANGE_EVENT_SCHEDULE'
ORDER BY TP.PARTITION_POSITION;