SELECT 'ALTER '|| 
CASE WHEN OBJECT_TYPE != 'PACKAGE BODY ' THEN OBJECT_TYPE ||' ' ELSE 'PACKAGE ' END ||
OWNER ||'.'|| OBJECT_NAME || 
CASE WHEN OBJECT_TYPE != 'PACKAGE BODY ' THEN ' COMPILE;' ELSE ' COMPILE BODY;' END AS SCRIPT
FROM ALL_OBJECTS
WHERE STATUS = 'INVALID';