SET SERVEROUTPUT ON SIZE UNLIMITED
SET TIMING ON
ALTER SESSION SET NLS_DATE_FORMAT = 'dd/MM/yyyy HH24:MI:SS';

DECLARE

  V_OWNER VARCHAR2(100) := SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'; -- OWNER DO BANCO
  
  CURSOR C_TABLES IS
    SELECT T.OWNER
          ,T.TABLE_NAME
    FROM DBA_TABLES T
    WHERE OWNER = V_OWNER
    ORDER BY T.OWNER
          ,T.TABLE_NAME;
    
  CURSOR C_COLUMNS(P_OWNER VARCHAR, P_TABLE_NAME VARCHAR)  IS  
    SELECT TB.OWNER
          ,TB.TABLE_NAME
          ,TB.COLUMN_NAME
          ,CASE 
             WHEN TB.DATA_TYPE = 'NUMBER' THEN
               TB.DATA_TYPE||'('||TO_CHAR(TB.DATA_PRECISION)||','||TO_CHAR(TB.DATA_SCALE)||')'
             WHEN TB.DATA_TYPE LIKE '%CHAR%' THEN  
               TB.DATA_TYPE||'('||TO_CHAR(TB.DATA_LENGTH)||')'  
             ELSE   
               TB.DATA_TYPE
           END DATA_TYPE
         ,TB.AVG_COL_LEN
    FROM DBA_TAB_COLUMNS TB
    WHERE TB.OWNER = P_OWNER
    AND   TB.TABLE_NAME = P_TABLE_NAME
    ORDER BY TB.OWNER
            ,TB.TABLE_NAME
            ,TB.COLUMN_ID;

  CURSOR C_MODIF(P_OWNER VARCHAR, P_TABLE_NAME VARCHAR)  IS  
    SELECT T.OWNER
          ,T.TABLE_NAME
          ,NVL(T.NUM_ROWS,0) NUM_ROWS
          ,NVL(T.AVG_ROW_LEN,0) AVG_ROW_LEN
          ,ROUND(NVL(TM.INSERTS,0) / TRUNC(SYSDATE - (T.LAST_ANALYZED - 1)),2) AVG_INSERT_DAY
          ,ROUND(NVL(TM.INSERTS,0) / TRUNC(SYSDATE - (T.LAST_ANALYZED - 1)) * 30,2) AVG_INSERT_MONTH
          ,ROUND(NVL(TM.INSERTS,0) / TRUNC(SYSDATE - (T.LAST_ANALYZED - 1)) * 365,2) AVG_INSERT_YEAR
    FROM DBA_TABLES T
    LEFT JOIN DBA_TAB_MODIFICATIONS TM  
    ON T.OWNER = TM.TABLE_OWNER 
    AND T.TABLE_NAME = TM.TABLE_NAME 
    WHERE T.OWNER = P_OWNER
    AND T.TABLE_NAME = P_TABLE_NAME
    AND TM.PARTITION_NAME IS NULL
    ORDER BY T.OWNER
            ,T.TABLE_NAME;  
    
BEGIN 

    DBMS_OUTPUT.PUT_LINE('********************************************************************************');      
    DBMS_OUTPUT.PUT_LINE('* CÁLCULO DE ESTIMATIVA DE CRESCIMENTO: '|| sys_context ( 'USERENV', 'DB_NAME' ) );      	
    DBMS_OUTPUT.PUT_LINE('* DATA: '|| TO_CHAR(TO_DATE(SYSDATE, 'dd/MM/yyyy hh24:mi:ss')));
    DBMS_OUTPUT.PUT_LINE('********************************************************************************');      


    DBMS_OUTPUT.PUT_LINE(' ');      
    DBMS_OUTPUT.PUT_LINE(' ');      
    DBMS_OUTPUT.PUT_LINE(' ');      
    DBMS_OUTPUT.PUT_LINE(' ');      

    FOR R_TABLES IN C_TABLES LOOP
	
	  DBMS_OUTPUT.PUT_LINE('TABELA: '|| R_TABLES.TABLE_NAME);    
      DBMS_OUTPUT.PUT_LINE(' ');   
      DBMS_OUTPUT.PUT_LINE(RPAD('COLUNA',(50-LENGTH('COLUNA')+LENGTH('COLUNA')),' ')||RPAD('DATATYPE',(50-LENGTH('DATATYPE')+LENGTH('DATATYPE')),' ')||RPAD('AVG SIZE BYTES',50-(LENGTH('AVG SIZE BYTES')+LENGTH('AVG SIZE BYTES')),' '));		
		
	  FOR R_COLUMNS IN C_COLUMNS(R_TABLES.OWNER,R_TABLES.TABLE_NAME) LOOP
        
		DBMS_OUTPUT.PUT_LINE(RPAD(R_COLUMNS.COLUMN_NAME,(50-LENGTH(R_COLUMNS.COLUMN_NAME)+LENGTH(R_COLUMNS.COLUMN_NAME)),' ')||RPAD(R_COLUMNS.DATA_TYPE,(50-LENGTH(R_COLUMNS.COLUMN_NAME)+LENGTH(R_COLUMNS.COLUMN_NAME)),' ')||RPAD(R_COLUMNS.AVG_COL_LEN,(50-LENGTH(R_COLUMNS.AVG_COL_LEN)+LENGTH(R_COLUMNS.AVG_COL_LEN)),' ')); 
	  
	  END LOOP;

      DBMS_OUTPUT.PUT_LINE(' ');      
      DBMS_OUTPUT.PUT_LINE(' ');    
      
      FOR R_MODIF IN C_MODIF(R_TABLES.OWNER,R_TABLES.TABLE_NAME) LOOP
        DBMS_OUTPUT.PUT_LINE('TAMANHO MÉDIO DO REGISTRO: '||TO_CHAR(R_MODIF.AVG_ROW_LEN));            
        DBMS_OUTPUT.PUT_LINE('QTDE. REGISTROS DIA: '||TO_CHAR(R_MODIF.AVG_INSERT_DAY,'FM999,999,999,999,990.99999'));      
        DBMS_OUTPUT.PUT_LINE('QTDE. REGISTROS MÊS: '||TO_CHAR(R_MODIF.AVG_INSERT_MONTH));      
        DBMS_OUTPUT.PUT_LINE('QTDE. REGISTROS ANO: '||TO_CHAR(R_MODIF.AVG_INSERT_YEAR));            
        DBMS_OUTPUT.PUT_LINE(' ');              

        DBMS_OUTPUT.PUT_LINE('CRESCIMENTO GB DIA: '||TO_CHAR(ROUND((R_MODIF.AVG_INSERT_DAY * R_MODIF.AVG_ROW_LEN)/1024/1024/1024,2)));      
        DBMS_OUTPUT.PUT_LINE('CRESCIMENTO GB MÊS: '||TO_CHAR(ROUND((R_MODIF.AVG_INSERT_MONTH * R_MODIF.AVG_ROW_LEN)/1024/1024/1024,2)));      
        DBMS_OUTPUT.PUT_LINE('CRESCIMENTO GB ANO: '||TO_CHAR(ROUND((R_MODIF.AVG_INSERT_YEAR * R_MODIF.AVG_ROW_LEN)/1024/1024/1024,2)));            
        
      END LOOP;

      DBMS_OUTPUT.PUT_LINE(' ');    
      DBMS_OUTPUT.PUT_LINE(' ');      
      DBMS_OUTPUT.PUT_LINE(' ');    
	
	END LOOP;

END;
/
  



