    SELECT TP.TABLE_OWNER	
		  ,TP.TABLE_NAME
		  ,TP.PARTITION_NAME
          ,TP.HIGH_VALUE
          ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
          ,ROUND(S.BYTES/1024/1024/1024,2) SIZE_GB		
          ,ROUND(S.BYTES/1024/1024/1024/1024,2) SIZE_TB	
          ,'ALTER TABLE '|| TP.TABLE_OWNER||'.'||TP.TABLE_NAME||' TRUNCATE PARTITION '||TP.PARTITION_NAME||' UPDATE INDEXES;' SCRIPT
	FROM DBA_TAB_PARTITIONS TP	    
    INNER JOIN DBA_SEGMENTS S		
    ON S.OWNER = TP.TABLE_OWNER 		
    AND S.SEGMENT_NAME = TP.TABLE_NAME		
    AND S.PARTITION_NAME = TP.PARTITION_NAME		
	WHERE TP.TABLE_OWNER = 'RECEIVABLES_ADM'	
	AND TP.TABLE_NAME = 'RECEIVABLE_UNIT_OUTBOX' -- 7 dias de retenção
    AND ROUND(S.BYTES/1024/1024/1024/1024,2) <> 0
    ORDER BY TP.PARTITION_POSITION DESC;
	
	SELECT TP.TABLE_OWNER	
		  ,TP.TABLE_NAME
		  ,TP.PARTITION_NAME
          ,TP.HIGH_VALUE
          ,ROUND(S.BYTES/1024/1024,2) SIZE_MB		
          ,ROUND(S.BYTES/1024/1024/1024,2) SIZE_GB		
          ,ROUND(S.BYTES/1024/1024/1024/1024,2) SIZE_TB	
          ,'ALTER TABLE '|| TP.TABLE_OWNER||'.'||TP.TABLE_NAME||' TRUNCATE PARTITION '||TP.PARTITION_NAME||' UPDATE INDEXES;' SCRIPT
	FROM DBA_TAB_PARTITIONS TP	    
    INNER JOIN DBA_SEGMENTS S		
    ON S.OWNER = TP.TABLE_OWNER 		
    AND S.SEGMENT_NAME = TP.TABLE_NAME		
    AND S.PARTITION_NAME = TP.PARTITION_NAME		
	WHERE TP.TABLE_OWNER = 'SETTLEMENTCONTRACT_ADM'	-- 30 dias de retenção
	AND TP.TABLE_NAME = 'TTO_RECORD'
    AND ROUND(S.BYTES/1024/1024/1024/1024,2) <> 0
    ORDER BY TP.PARTITION_POSITION DESC;