COLUMN OWNER FORMAT A30
COLUMN TABLE_NAME FORMAT A50
COLUMN STATUS FORMAT A20
COLUMN INDEX_NAME FORMAT A50
COLUMN CONSTRAINT_NAME FORMAT A50
COLUMN TABLESPACE_NAME FORMAT A30

---- RFC DE EXPURGO ---- 

-- VALIDA PARTICOES EXCLUIDAS
SELECT COUNT(1) QTDE_PARTICOES
FROM DBA_TAB_PARTITIONS
WHERE TABLE_OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND TABLE_NAME = 'CONTRACTUAL_EFFECT'
AND PARTITION_NAME IN ('SYS_P3848227','SYS_P3848267','SYS_P3848307');

-- VALIDA O TAMANHO DA TABELA
SELECT SEGMENT_NAME AS TABLE_NAME
,ROUND(SUM(BYTES)/1024/1024/1024,2) TAM_GB
,ROUND(SUM(BYTES)/1024/1024/1024/1024,2) TAM_TB
FROM DBA_SEGMENTS
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND SEGMENT_NAME = 'CONTRACTUAL_EFFECT'
GROUP BY SEGMENT_NAME;

---- RFC DESFRAGMENTACAO

SELECT TABLESPACE_NAME
,SEGMENT_NAME AS TABLE_NAME
,COUNT(1) QTDE_PARTICOES
,ROUND(SUM(BYTES)/1024/1024/1024,2) TAM_GB
,ROUND(SUM(BYTES)/1024/1024/1024/1024,2) TAM_TB
FROM DBA_SEGMENTS
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND SEGMENT_NAME = 'CONTRACTUAL_EFFECT'
GROUP BY TABLESPACE_NAME
,SEGMENT_NAME;

SELECT TABLESPACE_NAME
,SEGMENT_NAME AS TABLE_NAME
,COUNT(1) QTDE_PARTICOES
,ROUND(SUM(BYTES)/1024/1024/1024,2) TAM_GB
,ROUND(SUM(BYTES)/1024/1024/1024/1024,2) TAM_TB
FROM DBA_SEGMENTS
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND TABLESPACE_NAME = 'TSDRECEIVABLES01'
GROUP BY TABLESPACE_NAME
,SEGMENT_NAME;

---- GERAL ----


-- VALIDA STATUS DAS TABELAS
SELECT OWNER
,TABLE_NAME
,TABLESPACE_NAME
,STATUS
,DEGREE
FROM DBA_TABLES
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
ORDER BY 2
;

SELECT OWNER
,TABLE_NAME
,STATUS
FROM DBA_PART_TABLES
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
--AND TABLE_NAME = 'CONTRACTUAL_EFFECT'
ORDER BY 2
;

-- VALIDA INDICES

SELECT OWNER
,INDEX_NAME
,STATUS
,DEGREE
FROM DBA_INDEXES
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
ORDER BY 4 DESC,3;

SELECT 
INDEX_NAME
,STATUS
,COUNT(1) QTDE_INDEX_STATUS
FROM DBA_IND_PARTITIONS
WHERE INDEX_OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
AND INDEX_NAME IN ( SELECT INDEX_NAME
                    FROM DBA_PART_INDEXES
                    WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
--                    AND TABLE_NAME = 'CONTRACTUAL_EFFECT'
					)
GROUP BY INDEX_NAME
,STATUS
UNION ALL
SELECT
INDEX_NAME
,STATUS
,COUNT(1) 
FROM DBA_INDEXES
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
--AND TABLE_NAME = 'CONTRACTUAL_EFFECT'
AND PARTITIONED = 'NO'
GROUP BY INDEX_NAME
,STATUS
ORDER BY 2
;

-- VALIDA FKs
SELECT CONSTRAINT_NAME
,STATUS
FROM DBA_CONSTRAINTS
WHERE OWNER = SUBSTR(SYS_CONTEXT('USERENV','DB_NAME'),4,50)||'_ADM'
--AND TABLE_NAME = 'CONTRACTUAL_EFFECT'
AND CONSTRAINT_TYPE = 'R'
ORDER BY 2;

-- VALIDA TABLESPACES
SELECT TABLESPACE_NAME,STATUS,AUTOEXTENSIBLE
FROM DBA_DATA_FILES
WHERE TABLESPACE_NAME LIKE 'TS%'
AND TABLESPACE_NAME != 'TSTOOLS';
