   SELECT T2.USERNAME
        , T1.MODULE
        , T1.DISK_READS
        , ROUND(T1.ELAPSED_TIME/1000000,2) AS ELAPSED_SEC
        , T1.EXECUTIONS
        , ROUND(T1.ELAPSED_TIME/1000000 / DECODE(T1.EXECUTIONS, 0, 1, T1.EXECUTIONS),2)  AS AVG_TIME_PER_EXEC
        , ROUND(T1.DISK_READS / DECODE(T1.EXECUTIONS, 0, 1, T1.EXECUTIONS),2) AS EXEC_RATIO
        , T1.SQL_ID
        , T1.SQL_FULLTEXT
   FROM GV$SQLAREA T1
   INNER JOIN DBA_USERS T2
   ON T1.PARSING_USER_ID = T2.USER_ID
-- INNER JOIN GV$SESSION T3
-- ON T1.SQL_ID = T3.SQL_ID  
   WHERE T2.USERNAME LIKE '%UBR%'
   AND T2.USERNAME NOT LIKE '%REDASH_%UBR%'
-- AND T3.STATUS = 'ACTIVE'   
   AND UPPER(T1.SQL_FULLTEXT) LIKE 'INSERT%'
   ORDER BY ROUND(T1.ELAPSED_TIME/1000000,2) DESC
          , T1.DISK_READS ;