--DROP 
DROP TABLE  AD.AMOUNT_SUMMARY CASCADE CONSTRAINTS;

DROP TABLE  AD.ADVANCE_COST_HISTORY CASCADE CONSTRAINTS;

DROP TABLE  AD.ACCOUNTING_PROCESS CASCADE CONSTRAINTS;

DROP TABLE  AD.FEE CASCADE CONSTRAINTS;

DROP TABLE AD.RECEIVABLE_STATUS CASCADE CONSTRAINTS;

DROP TABLE  AD.RECEIVABLE CASCADE CONSTRAINTS;

DROP TABLE  AD.RECEIVABLE_UNIT_STATUS CASCADE CONSTRAINTS;

DROP TABLE AD.PAYMENT_GROUP CASCADE CONSTRAINTS;

DROP TABLE  AD.PAYMENT CASCADE CONSTRAINTS;

DROP TABLE  AD.RECEIVABLE_UNIT CASCADE CONSTRAINTS;

--TRUNCATE
/*
TRUNCATE TABLE AD.AMOUNT_SUMMARY CASCADE;
TRUNCATE TABLE AD.ADVANCE_COST_HISTORY CASCADE;
TRUNCATE TABLE AD.ACCOUNTING_PROCESS CASCADE;
TRUNCATE TABLE AD.FEE CASCADE;
TRUNCATE TABLE AD.RECEIVABLE_STATUS CASCADE;
TRUNCATE TABLE AD.RECEIVABLE CASCADE;
TRUNCATE TABLE AD.RECEIVABLE_UNIT_STATUS CASCADE;
TRUNCATE TABLE AD.PAYMENT_GROUP CASCADE;
TRUNCATE TABLE AD.PAYMENT CASCADE;
TRUNCATE TABLE AD.RECEIVABLE_UNIT CASCADE; */