INSERT INTO AD.PAYMENT_GROUP (IDT_PAYMENT_GROUP, IND_PAYMENT_GROUP) VALUES(59, 'PIX');
INSERT INTO AD.PAYMENT_GROUP (IDT_PAYMENT_GROUP, IND_PAYMENT_GROUP) VALUES(60, 'ETF');
INSERT INTO AD.PAYMENT_GROUP (IDT_PAYMENT_GROUP, IND_PAYMENT_GROUP) VALUES(61, 'DEPOSIT');
INSERT INTO AD.PAYMENT_GROUP (IDT_PAYMENT_GROUP, IND_PAYMENT_GROUP) VALUES(62, 'AUTOMATIC_DEBIT');
INSERT INTO AD.PAYMENT_GROUP (IDT_PAYMENT_GROUP, IND_PAYMENT_GROUP) VALUES(63, 'BALANCE');
COMMIT;