INSERT INTO AD.RECEIVABLE_UNIT_STATUS (IDT_RECEIVABLE_UNIT_STATUS, DES_RECEIVABLE_UNIT_STATUS) VALUES(5, 'ANTICIPATION_SCHEDULED');
INSERT INTO AD.RECEIVABLE_UNIT_STATUS (IDT_RECEIVABLE_UNIT_STATUS, DES_RECEIVABLE_UNIT_STATUS) VALUES(6, 'PARTIALLY_COMPLETED');
COMMIT;