ALTER TABLE AD.PAYMENT ADD DAT_CREATION_PS TIMESTAMP NOT NULL;
COMMENT ON COLUMN AD.PAYMENT.DAT_CREATION_PS IS 'Data em que o pagamento foi criado';

ALTER TABLE AD.PAYMENT ADD NUM_TOTAL_INSTALLMENTS NUMBER(2) NOT NULL;
COMMENT ON COLUMN AD.PAYMENT.NUM_TOTAL_INSTALLMENTS IS 'Quantidade de parcelas do pagamento';