ALTER TABLE AD.FEE DROP CONSTRAINT FEE_UK01;
ALTER TABLE AD.FEE RENAME COLUMN IND_FEE_TYPE TO IND_FEE;
ALTER TABLE AD.FEE ADD CONSTRAINT FEE_UK01 UNIQUE (IDT_PAYMENT, IND_FEE, IND_CUSTOMER_TYPE)
USING INDEX TABLESPACE TSIRECTRANSITORYMOVEMENT01 INITRANS 12;

COMMENT ON COLUMN AD.FEE.IND_FEE                    IS 'Indicador da taxa';