-- ADVANCE_COST_HISTORY
COMMENT ON COLUMN AD.ADVANCE_COST_HISTORY.IDT_ADVANCE_COST_HISTORY IS '[NOT SECURITY APPLY] Chave primária da tabela';
COMMENT ON COLUMN AD.ADVANCE_COST_HISTORY.IDT_SAFEPAY_USER IS '[NOT SECURITY APPLY] IDT do usuário';
COMMENT ON COLUMN AD.ADVANCE_COST_HISTORY.NUM_ADVANCE_COST IS '[NOT SECURITY APPLY] Valor da taxa de antecipação';
COMMENT ON COLUMN AD.ADVANCE_COST_HISTORY.NAM_CHANGE_AGENT IS '[NOT SECURITY APPLY] Agente da alteração';
COMMENT ON COLUMN AD.ADVANCE_COST_HISTORY.DAT_CREATION IS '[NOT SECURITY APPLY] Data de criação do registro';
COMMENT ON COLUMN AD.ADVANCE_COST_HISTORY.DAT_START IS '[NOT SECURITY APPLY] Data de inicio de vigencia da taxa';
COMMENT ON COLUMN AD.ADVANCE_COST_HISTORY.DAT_END IS '[NOT SECURITY APPLY] Data de fim de vigencia da taxa';


-- AMOUNT_SUMMARY
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.IDT_AMOUNT_SUMMARY IS '[NOT SECURITY APPLY] Código do sumario do recebivel, identificador da tabela';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.IDT_RECEIVABLE IS '[NOT SECURITY APPLY] Código da unidade do recebivel, integração com a tabela de recebiveis';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_TOTAL IS '[NOT SECURITY APPLY] Valor total do recebivel';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_SETTLE IS '[NOT SECURITY APPLY] Valor a liquidar do recebivel';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_SETTLED IS '[NOT SECURITY APPLY] Valor liquidado do recebivel';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_SUSPENDED IS '[NOT SECURITY APPLY] Valor suspenso do recebivel';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_CANCELED IS '[NOT SECURITY APPLY] Valor cancelado do recebivel';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_ANTICIPATED IS '[NOT SECURITY APPLY] Valor antecipado do recebivel';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_COMMITTED IS '[NOT SECURITY APPLY] Valor intermediado no caso external, valor reservado no caso internal';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_IN_PERSON IS '[NOT SECURITY APPLY] Valor total da dos recebiveis presencial';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_ONLINE IS '[NOT SECURITY APPLY] Valor total da dos recebiveis online';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.NUM_VERSION IS '[NOT SECURITY APPLY] Versao corrente do recebivel';
COMMENT ON COLUMN AD.AMOUNT_SUMMARY.DAT_SETTLE IS '[NOT SECURITY APPLY] Data de liquidacao do recebivel';

-- FEE
COMMENT ON COLUMN AD.FEE.IDT_FEE IS '[NOT SECURITY APPLY] Identificador da taxa';
COMMENT ON COLUMN AD.FEE.IND_FEE IS '[NOT SECURITY APPLY] Indicador da taxa';
COMMENT ON COLUMN AD.FEE.NUM_AMOUNT IS '[NOT SECURITY APPLY] Valor da taxa';
COMMENT ON COLUMN AD.FEE.IDT_PAYMENT IS '[NOT SECURITY APPLY] Identificador do pagamento';
COMMENT ON COLUMN AD.FEE.IND_CUSTOMER_TYPE IS '[NOT SECURITY APPLY] Tipo do usuario do qual a taxa foi cobrada, pode ser BUYER ou SELLER';
 
-- PAYMENT
COMMENT ON COLUMN AD.PAYMENT.IDT_PAYMENT IS '[NOT SECURITY APPLY] Identificador do pagamento';
COMMENT ON COLUMN AD.PAYMENT.COD_PAYMENT IS '[NOT SECURITY APPLY] Código do pagamento';
COMMENT ON COLUMN AD.PAYMENT.NUM_TOTAL_AMOUNT IS '[NOT SECURITY APPLY] Valor total do pagamento';
COMMENT ON COLUMN AD.PAYMENT.NUM_NET_AMOUNT IS '[NOT SECURITY APPLY] Valor Liquido do pagamento';
COMMENT ON COLUMN AD.PAYMENT.DAT_CREATED IS '[NOT SECURITY APPLY] Data de criação do pagamento';
COMMENT ON COLUMN AD.PAYMENT.DAT_UPDATED IS '[NOT SECURITY APPLY] Data ultima atualização do pagamento';
COMMENT ON COLUMN AD.PAYMENT.IND_ESCROW_TYPE IS '[NOT SECURITY APPLY] Indicador de condições de pagamento para o cliente. M - MULTIPLE, U - UNIQUE';
COMMENT ON COLUMN AD.PAYMENT.NUM_ESCROW_VALUE IS '[NOT SECURITY APPLY] Valor de condições de pagamento para o cliente. Range de 1-18 para escrow MULTIPLE e de 1-30 UNIQUE';
COMMENT ON COLUMN AD.PAYMENT.COD_CUSTOMER_SELLER IS '[NOT SECURITY APPLY] Identificador do usuário vendedor do PagSeguro';
COMMENT ON COLUMN AD.PAYMENT.COD_CUSTOMER_BUYER IS '[NOT SECURITY APPLY] Identificador do usuário comprador do PagSeguro';
COMMENT ON COLUMN AD.PAYMENT.DAT_CREATION_PS IS '[NOT SECURITY APPLY] Data em que o pagamento foi criado';
COMMENT ON COLUMN AD.PAYMENT.NUM_TOTAL_INSTALLMENTS IS '[NOT SECURITY APPLY] Quantidade de parcelas do pagamento';


-- PAYMENT_GROUP
COMMENT ON COLUMN AD.PAYMENT_GROUP.IDT_PAYMENT_GROUP IS '[NOT SECURITY APPLY] Identificador do grupo de pagamento';
COMMENT ON COLUMN AD.PAYMENT_GROUP.IND_PAYMENT_GROUP IS '[NOT SECURITY APPLY] Indicador do grupo de pagamento';
COMMENT ON COLUMN AD.PAYMENT_GROUP.DAT_CREATED IS '[NOT SECURITY APPLY] Data de criação';
COMMENT ON COLUMN AD.PAYMENT_GROUP.DAT_UPDATED IS '[NOT SECURITY APPLY] Data da ultima atualização';

-- RECEIVABLE
COMMENT ON COLUMN AD.RECEIVABLE.IDT_RECEIVABLE IS '[NOT SECURITY APPLY] Identificador do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.COD_RECEIVABLE IS '[NOT SECURITY APPLY] Código do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.IDT_RECEIVABLE_STATUS IS '[NOT SECURITY APPLY] Status do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.DAT_SETTLED IS '[NOT SECURITY APPLY] Data que o recebivel foi liquidado';
COMMENT ON COLUMN AD.RECEIVABLE.DAT_SETTLE IS '[NOT SECURITY APPLY] Data de liquidacao do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.DAT_CREATED IS '[NOT SECURITY APPLY] Data de criação do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.DAT_UPDATED IS '[NOT SECURITY APPLY] Data ultima atualização do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.IDT_RECEIVABLE_UNIT IS '[NOT SECURITY APPLY] identificador da unidade de recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.IDT_PAYMENT IS '[NOT SECURITY APPLY] identificador do pagamento';

-- RECEIVABLE_STATUS
COMMENT ON COLUMN AD.RECEIVABLE_STATUS.IDT_RECEIVABLE_STATUS IS '[NOT SECURITY APPLY] Identificador do status do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_STATUS.DES_RECEIVABLE_STATUS IS '[NOT SECURITY APPLY] Descrição do status';
COMMENT ON COLUMN AD.RECEIVABLE_STATUS.DAT_CREATED IS '[NOT SECURITY APPLY] Data de criação';
COMMENT ON COLUMN AD.RECEIVABLE_STATUS.DAT_UPDATED IS '[NOT SECURITY APPLY] Data da ultima atualização';

-- RECEIVABLE_UNIT
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.IDT_RECEIVABLE_UNIT IS '[NOT SECURITY APPLY] Identificador da unidade do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.COD_RECEIVABLE_UNIT IS '[NOT SECURITY APPLY] Código da unidade do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.DAT_SETTLE IS '[NOT SECURITY APPLY] Data a ser liquidada da unidade de recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.IDT_PAYMENT_GROUP IS '[NOT SECURITY APPLY] Informa o payment group, a informacao de meio de pagamento e a bandeira';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.IND_UNIT_TYPE IS '[NOT SECURITY APPLY] Tipo de unidade, pode ser: I - INTERNAL, E - EXTERNAL';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.IDT_RECEIVABLE_UNIT_STATUS IS '[NOT SECURITY APPLY] Status da unidade de recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.COD_CUSTOMER_HOLDER IS '[NOT SECURITY APPLY] Identificador do usuário titular da unidade';
   
-- RECEIVABLE_UNIT_STATUS
COMMENT ON COLUMN AD.RECEIVABLE_UNIT_STATUS.IDT_RECEIVABLE_UNIT_STATUS IS '[NOT SECURITY APPLY] Identificador do status da unidade do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT_STATUS.DES_RECEIVABLE_UNIT_STATUS IS '[NOT SECURITY APPLY] Descrição do status';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT_STATUS.DAT_CREATED IS '[NOT SECURITY APPLY] Data de criação';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT_STATUS.DAT_UPDATED IS '[NOT SECURITY APPLY] Data da ultima atualização';