create TABLE AD.RECEIVABLE_UNIT (
    IDT_RECEIVABLE_UNIT                     NUMBER(20)                       NOT NULL,
    COD_RECEIVABLE_UNIT                     VARCHAR(50)                     NOT NULL,
    DAT_SETTLE                              DATE                            NOT NULL,
    IDT_PAYMENT_GROUP                       NUMBER(20)                      NOT NULL,
    IND_UNIT_TYPE                           VARCHAR(1)                      NOT NULL,
    IDT_RECEIVABLE_UNIT_STATUS              NUMBER(20)                      NOT NULL,
    COD_CUSTOMER_HOLDER                     VARCHAR(50)                     NOT NULL,
    CONSTRAINT RECEIVABLE_UNIT_PK PRIMARY KEY (IDT_RECEIVABLE_UNIT)
    USING INDEX TABLESPACE TSIRECTRANSITORYMOVEMENT01 INITRANS 10
) PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_2020_09_10 VALUES LESS THAN (TO_DATE('2020-09-10','YYYY-MM-DD'))
) TABLESPACE TSDRECTRANSITORYMOVEMENT01 INITRANS 10;

COMMENT ON TABLE  AD.RECEIVABLE_UNIT                                         IS 'Tabela com informações da unidade dos recebiveis';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.IDT_RECEIVABLE_UNIT                     IS 'Identificador da unidade do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.COD_RECEIVABLE_UNIT                     IS 'Código da unidade do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.DAT_SETTLE                              IS 'Data a ser liquidada da unidade de recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.IDT_PAYMENT_GROUP                       IS 'Informa o payment group, a informacao de meio de pagamento e a bandeira';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.IND_UNIT_TYPE                           IS 'Tipo de unidade, pode ser: I - INTERNAL, E - EXTERNAL';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.IDT_RECEIVABLE_UNIT_STATUS              IS 'Status da unidade de recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_UNIT.COD_CUSTOMER_HOLDER                     IS 'Identificador do usuário titular da unidade';
ALTER TABLE AD.RECEIVABLE_UNIT ADD CONSTRAINT RECEIVABLE_UNIT_UK01 UNIQUE (COD_RECEIVABLE_UNIT);
ALTER TABLE AD.RECEIVABLE_UNIT ADD CONSTRAINT RECEIVABLE_UNIT_STATUS_FK FOREIGN KEY ( IDT_RECEIVABLE_UNIT_STATUS )
REFERENCES AD.RECEIVABLE_UNIT_STATUS ( IDT_RECEIVABLE_UNIT_STATUS );
ALTER TABLE AD.RECEIVABLE_UNIT ADD CONSTRAINT PAYMENT_GROUP_FK FOREIGN KEY ( IDT_PAYMENT_GROUP )
REFERENCES AD.PAYMENT_GROUP ( IDT_PAYMENT_GROUP );
GRANT SELECT,UPDATE,INSERT,DELETE ON AD.RECEIVABLE_UNIT TO RECTRANSITORYMOVEMENTUBR;
GRANT SELECT ON AD.RECEIVABLE_UNIT TO MANUT_RECTRANSITORYMOVEMENT;