CREATE TABLE AD.RECEIVABLE_STATUS (
    IDT_RECEIVABLE_STATUS                       NUMBER(20)                      NOT NULL,
    DES_RECEIVABLE_STATUS                       VARCHAR(50)                     NOT NULL,
    DAT_CREATED                                 TIMESTAMP DEFAULT SYSDATE       NOT NULL,
    DAT_UPDATED                                 TIMESTAMP DEFAULT SYSDATE       NOT NULL,
    CONSTRAINT RECEIVABLE_STATUS_PK PRIMARY KEY (IDT_RECEIVABLE_STATUS)
    USING INDEX TABLESPACE TSIRECTRANSITORYMOVEMENT01
) TABLESPACE TSDRECTRANSITORYMOVEMENT01;
COMMENT ON TABLE  AD.RECEIVABLE_STATUS                                 IS 'Tabela com os status do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_STATUS.IDT_RECEIVABLE_STATUS           IS 'Identificador do status do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE_STATUS.DES_RECEIVABLE_STATUS           IS 'Descrição do status';
COMMENT ON COLUMN AD.RECEIVABLE_STATUS.DAT_CREATED                     IS 'Data de criação';
COMMENT ON COLUMN AD.RECEIVABLE_STATUS.DAT_UPDATED                     IS 'Data da ultima atualização';
GRANT SELECT,UPDATE,INSERT,DELETE ON AD.RECEIVABLE_STATUS TO RECTRANSITORYMOVEMENTUBR;
GRANT SELECT ON AD.RECEIVABLE_STATUS TO MANUT_RECTRANSITORYMOVEMENT;
