CREATE TABLE AD.RECEIVABLE (
	IDT_RECEIVABLE 					NUMBER(20)  				     NOT NULL,
    COD_RECEIVABLE                  VARCHAR(50)                     NOT NULL,
    IDT_RECEIVABLE_STATUS           NUMBER(20)  				    NOT NULL,
    DAT_SETTLED                     TIMESTAMP                       ,
    DAT_SETTLE                      DATE                            NOT NULL,
    DAT_CREATED                     TIMESTAMP DEFAULT SYSDATE       NOT NULL,
    DAT_UPDATED                     TIMESTAMP DEFAULT SYSDATE       NOT NULL,
    IDT_RECEIVABLE_UNIT             NUMBER(20)                      NOT NULL,
    IDT_PAYMENT                     NUMBER(20)                      NOT NULL,
    CONSTRAINT RECEIVABLE_PK PRIMARY KEY (IDT_RECEIVABLE)
    USING INDEX TABLESPACE TSIRECTRANSITORYMOVEMENT01 INITRANS 10
) PARTITION BY
RANGE(DAT_SETTLE)
INTERVAL (NUMTODSINTERVAL(1,'DAY'))
(PARTITION P_2020_09_10 VALUES LESS THAN (TO_DATE('2020-09-10','YYYY-MM-DD'))
) TABLESPACE TSDRECTRANSITORYMOVEMENT01 INITRANS 10;

COMMENT ON TABLE  AD.RECEIVABLE                                      IS 'Tabela com informações do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.IDT_RECEIVABLE                       IS 'Identificador do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.COD_RECEIVABLE                       IS 'Código do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.IDT_RECEIVABLE_STATUS                IS 'Status do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.DAT_SETTLED                          IS 'Data que o recebivel foi liquidado';
COMMENT ON COLUMN AD.RECEIVABLE.DAT_SETTLE                           IS 'Data de liquidacao do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.DAT_CREATED                          IS 'Data de criação do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.DAT_UPDATED                          IS 'Data ultima atualização do recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.IDT_RECEIVABLE_UNIT                  IS 'identificador da unidade de recebivel';
COMMENT ON COLUMN AD.RECEIVABLE.IDT_PAYMENT                          IS 'identificador do pagamento';

ALTER TABLE AD.RECEIVABLE ADD CONSTRAINT RECEIVABLE_UK01 UNIQUE (COD_RECEIVABLE);

ALTER TABLE AD.RECEIVABLE ADD CONSTRAINT PAYMENT_FK FOREIGN KEY ( IDT_PAYMENT )
        REFERENCES AD.PAYMENT ( IDT_PAYMENT );

ALTER TABLE AD.RECEIVABLE ADD CONSTRAINT RECEIVABLE_UNIT_FK FOREIGN KEY ( IDT_RECEIVABLE_UNIT )
        REFERENCES AD.RECEIVABLE_UNIT ( IDT_RECEIVABLE_UNIT );

ALTER TABLE AD.RECEIVABLE ADD CONSTRAINT RECEIVABLE_STATUS_FK FOREIGN KEY ( IDT_RECEIVABLE_STATUS )
        REFERENCES AD.RECEIVABLE_STATUS ( IDT_RECEIVABLE_STATUS );

CREATE INDEX AD.RECEIVABLE_IDX01 ON AD.RECEIVABLE(IDT_RECEIVABLE_UNIT) INITRANS 10 TABLESPACE TSIRECTRANSITORYMOVEMENT01 ONLINE;

GRANT SELECT,UPDATE,INSERT,DELETE ON AD.RECEIVABLE TO RECTRANSITORYMOVEMENTUBR;
GRANT SELECT ON AD.RECEIVABLE TO MANUT_RECTRANSITORYMOVEMENT;