CREATE TABLE AD.FEE (
    IDT_FEE                         NUMBER(20)                       NOT NULL,
    IND_FEE_TYPE                    VARCHAR(30)                     NOT NULL,
    NUM_AMOUNT                      NUMBER(18, 2)                   NOT NULL,
    IDT_PAYMENT                     NUMBER(20)                      NOT NULL,
    CONSTRAINT FEE_PK PRIMARY KEY (IDT_FEE)
    USING INDEX TABLESPACE TSIRECTRANSITORYMOVEMENT01 INITRANS 10
) TABLESPACE TSDRECTRANSITORYMOVEMENT01 INITRANS 10;
COMMENT ON TABLE  AD.FEE                                 IS 'Tabela com as taxas do pagamento';
COMMENT ON COLUMN AD.FEE.IDT_FEE                         IS 'Identificador da taxa';
COMMENT ON COLUMN AD.FEE.IND_FEE_TYPE                    IS 'Indicador do tipo de taxa';
COMMENT ON COLUMN AD.FEE.NUM_AMOUNT                      IS 'Valor da taxa';
COMMENT ON COLUMN AD.FEE.IDT_PAYMENT                     IS 'Identificador do pagamento';
ALTER TABLE AD.FEE ADD CONSTRAINT FEE_UK01 UNIQUE (IDT_PAYMENT, IND_FEE_TYPE);
ALTER TABLE AD.FEE ADD CONSTRAINT FEE_IDT_PAYMENT_FK FOREIGN KEY ( IDT_PAYMENT )
        REFERENCES AD.PAYMENT ( IDT_PAYMENT );

CREATE INDEX AD.FEE_IDX01 ON AD.FEE ( IDT_PAYMENT ) INITRANS 10 TABLESPACE TSIRECTRANSITORYMOVEMENT01 ONLINE;
GRANT SELECT,UPDATE,INSERT,DELETE ON AD.FEE TO RECTRANSITORYMOVEMENTUBR;
GRANT SELECT ON AD.FEE TO MANUT_RECTRANSITORYMOVEMENT;