
ALTER TABLE AD.RECEIVABLE_UNIT DISABLE CONSTRAINT RECEIVABLE_UNIT_STATUS_FK;
ALTER TABLE AD.RECEIVABLE_UNIT DISABLE CONSTRAINT PAYMENT_GROUP_FK;
ALTER TABLE AD.RECEIVABLE DISABLE CONSTRAINT PAYMENT_FK;
ALTER TABLE AD.RECEIVABLE DISABLE CONSTRAINT RECEIVABLE_UNIT_FK;
ALTER TABLE AD.RECEIVABLE DISABLE CONSTRAINT RECEIVABLE_STATUS_FK;
ALTER TABLE AD.AMOUNT_SUMMARY DISABLE CONSTRAINT AMOUNT_SUMMARY_IDT_RECEIVABLE_FK;
ALTER TABLE AD.FEE DISABLE CONSTRAINT FEE_IDT_PAYMENT_FK;


