insert into AD.AMOUNT_SUMMARY
select * from RECTRANSITORYMOVEMENT_ADM.AMOUNT_SUMMARY;
commit;

insert into ADVANCE_COST_HISTORY
select * from RECTRANSITORYMOVEMENT_ADM.ADVANCE_COST_HISTORY;
commit;

insert into AD.ACCOUNTING_PROCESS
select * from RECTRANSITORYMOVEMENT_ADM.ACCOUNTING_PROCESS;
commit;

insert into AD.FEE
select * from RECTRANSITORYMOVEMENT_ADM.FEE;
commit;

TRUNCATE TABLE AD.RECEIVABLE_STATUS;
insert into AD.RECEIVABLE_STATUS
select * from RECTRANSITORYMOVEMENT_ADM.RECEIVABLE_STATUS;
commit;


insert into AD.RECEIVABLE 
select * from RECTRANSITORYMOVEMENT_ADM.RECEIVABLE ;
commit;

TRUNCATE TABLE AD.RECEIVABLE_UNIT_STATUS;
insert into AD.RECEIVABLE_UNIT_STATUS
select * from RECTRANSITORYMOVEMENT_ADM.RECEIVABLE_UNIT_STATUS;
commit;


TRUNCATE TABLE AD.PAYMENT_GROUP;
insert into AD.PAYMENT_GROUP
select * from RECTRANSITORYMOVEMENT_ADM.PAYMENT_GROUP;
commit;

insert into AD.PAYMENT
select * from RECTRANSITORYMOVEMENT_ADM.PAYMENT;
commit;

insert into AD.RECEIVABLE_UNIT
select * from RECTRANSITORYMOVEMENT_ADM.RECEIVABLE_UNIT;
commit;



