DROP TABLE SMOREIRA.TMP_ADVANCE_RECEIVABLE;
CREATE TABLE SMOREIRA.TMP_ADVANCE_RECEIVABLE AS
SELECT AR.IDT_ADVANCE_RECEIVABLE,
       AR.DAT_CREATION
FROM SAFEPAY_ADM.ADVANCE_RECEIVABLE AR
WHERE AR.DAT_CREATION BETWEEN TO_DATE('19/04/2021', 'DD/MM/YYYY') AND TO_DATE('26/04/2021', 'DD/MM/YYYY')
AND AR.IND_STATUS = 'P'
AND AR.NUM_ADVANCED_DAYS > 0
AND AR.NAM_CHANGE_AGENT <> 'PAGSEGURO-FIDC';
COMMIT;

DROP TABLE SMOREIRA.TMP_ADVANCE_RECEIVABLE_RELEASE;
CREATE TABLE SMOREIRA.TMP_ADVANCE_RECEIVABLE_RELEASE AS
SELECT AR.IDT_ADVANCE_RECEIVABLE,
AR.DAT_CREATION,
ARR.IDT_PAYMENT_RELEASE
FROM SAFEPAY_ADM.ADVANCE_RECEIVABLE_RELEASE ARR
INNER JOIN SMOREIRA.TMP_ADVANCE_RECEIVABLE AR
ON ARR.IDT_ADVANCE_RECEIVABLE = AR.IDT_ADVANCE_RECEIVABLE
AND ARR.IND_STATUS = 'P';
COMMIT;

ALTER TABLE SMOREIRA.TMP_ADVANCE_RECEIVABLE_RELEASE ADD CONSTRAINT TMP_ADVANCE_RECEIVABLE_RELEASE_PK PRIMARY KEY ( IDT_PAYMENT_RELEASE );

CREATE INDEX TMP_ADVANCE_RECEIVABLE_RELEASE_IDX01 ON SMOREIRA.TMP_ADVANCE_RECEIVABLE_RELEASE (IDT_ADVANCE_RECEIVABLE ) ONLINE;




SELECT COUNT(1) QTDE_ANTECIPACOES,
ROUND(AVG((FD.DURACAO_DIAS * 24 * 60)) + 0.5) MEDIA_TEMPO_MINUTOS,
ROUND(MAX(FD.DURACAO_DIAS * 24 * 60)) MAIS_DEMORADA_MINUTOS,
COUNT(CASE WHEN (FD.DURACAO_DIAS * 24) BETWEEN 1 AND 2 THEN 1 ELSE NULL END) QTDE_ANTECIP_ACIMA_1_HORA,
COUNT(CASE WHEN (FD.DURACAO_DIAS * 24) > 2 THEN 1 ELSE NULL END) QTDE_ANTECIP_ACIMA_2_HORAS
FROM
(
SELECT 
CD.IDT_ADVANCE_RECEIVABLE,
CD.DATA_CRIACAO_FT - CD.DATA_CRIACAO_AR AS DURACAO_DIAS
FROM 
(SELECT /*+ INDEX(PRT PAYRELETURN_IDX01) INDEX(FA FINAACCO_UK01) */
ARR.IDT_ADVANCE_RECEIVABLE,
ARR.DAT_CREATION AS DATA_CRIACAO_AR,
MAX(FT.DAT_CREATION) DATA_CRIACAO_FT
FROM SMOREIRA.TMP_ADVANCE_RECEIVABLE_RELEASE ARR -- 1.795.437

INNER JOIN SAFEPAY_ADM.ADVANCE_RECEIVABLE AR2 -- 2.769.526
ON AR2.IDT_ADVANCE_RECEIVABLE = ARR.IDT_ADVANCE_RECEIVABLE

INNER JOIN SAFEPAY_ADM.PAYMENT_RELEASE_TURNOVER PRT -- 5.258.508.211
ON PRT.IDT_PAYMENT_RELEASE = ARR.IDT_PAYMENT_RELEASE

INNER JOIN SAFEPAY_ADM.FINANCIAL_TURNOVER FT -- 26.808.664.926
ON FT.IDT_FINANCIAL_TURNOVER = PRT.IDT_FINANCIAL_TURNOVER

INNER JOIN SAFEPAY_ADM.FINANCIAL_ACCOUNT FA -- 1.504.946.688
ON FA.IDT_FINANCIAL_ACCOUNT = FT.IDT_FINANCIAL_ACCOUNT_CREDIT
AND FA.IDT_SAFEPAY_USER = AR2.IDT_SAFEPAY_USER
AND FA.IDT_FINANCIAL_ACCOUNT_TYPE = 2

GROUP BY ARR.IDT_ADVANCE_RECEIVABLE,
ARR.DAT_CREATION) CD) FD;
