SELECT COUNT(1) QTDE_ANTECIPACOES,
ROUND(AVG((FD.DURACAO_DIAS * 24 * 60)) + 0.5) MEDIA_TEMPO_MINUTOS,
ROUND(MAX(FD.DURACAO_DIAS * 24 * 60)) MAIS_DEMORADA_MINUTOS,
COUNT(CASE WHEN (FD.DURACAO_DIAS * 24) BETWEEN 1 AND 2 THEN 1 ELSE NULL END) QTDE_ANTECIP_ACIMA_1_HORA,
COUNT(CASE WHEN (FD.DURACAO_DIAS * 24) > 2 THEN 1 ELSE NULL END) QTDE_ANTECIP_ACIMA_2_HORAS
FROM
(SELECT CD.IDT_ADVANCE_RECEIVABLE,
CD.DATA_CRIACAO_FT - CD.DATA_CRIACAO_AR AS DURACAO_DIAS
FROM 
(SELECT AR.IDT_ADVANCE_RECEIVABLE,
AR.DAT_CREATION DATA_CRIACAO_AR,
MAX(FT.DAT_CREATION) DATA_CRIACAO_FT
FROM SAFEPAY_ADM.ADVANCE_RECEIVABLE_RELEASE ARR
INNER JOIN (SELECT AR.IDT_ADVANCE_RECEIVABLE,
                   AR.DAT_CREATION
            FROM SAFEPAY_ADM.ADVANCE_RECEIVABLE AR
            WHERE AR.DAT_CREATION BETWEEN TO_DATE('06/01/2020', 'DD/MM/YYYY') AND TO_DATE('13/01/2020', 'DD/MM/YYYY')
            AND AR.IND_STATUS = 'P'
            AND NUM_ADVANCED_DAYS > 0
            AND AR.NAM_CHANGE_AGENT <> 'PAGSEGURO-FIDC') AR
ON ARR.IDT_ADVANCE_RECEIVABLE = AR.IDT_ADVANCE_RECEIVABLE
AND ARR.IND_STATUS = 'P'

INNER JOIN SAFEPAY_ADM.PAYMENT_RELEASE_TURNOVER PRT
ON PRT.IDT_PAYMENT_RELEASE = ARR.IDT_PAYMENT_RELEASE

INNER JOIN SAFEPAY_ADM.FINANCIAL_TURNOVER FT
ON FT.IDT_FINANCIAL_TURNOVER = PRT.IDT_FINANCIAL_TURNOVER

INNER JOIN SAFEPAY_ADM.ADVANCE_RECEIVABLE AR2
ON AR2.IDT_ADVANCE_RECEIVABLE = AR.IDT_ADVANCE_RECEIVABLE

INNER JOIN SAFEPAY_ADM.FINANCIAL_ACCOUNT FA
ON FA.IDT_SAFEPAY_USER = AR2.IDT_SAFEPAY_USER
AND FA.IDT_FINANCIAL_ACCOUNT_TYPE = 2
AND FT.IDT_FINANCIAL_ACCOUNT_CREDIT = FA.IDT_FINANCIAL_ACCOUNT
GROUP BY AR.IDT_ADVANCE_RECEIVABLE,
AR.DAT_CREATION) CD) FD

