-- Unable to render TABLE DDL for object SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER with DBMS_METADATA attempting internal generator.
CREATE INDEX SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER_IDX01 ON SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER (IDT_PERCENTUAL_RECOVERY ASC) 
LOGGING 
TABLESPACE TSISAFEPAY02 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 1048576 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE INDEX SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER_IDX02 ON SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER (IDT_SAFEPAY_USER ASC) 
LOGGING 
TABLESPACE TSISAFEPAY06 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 1048576 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE INDEX SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER_IDX03 ON SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER (IDT_SAFEPAY_USER ASC, IDT_PERCENTUAL_RECOVERY ASC) 
LOGGING 
TABLESPACE TSISAFEPAY06 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE INDEX SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER_IDX04 ON SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER (COD_CUSTOMER ASC, IDT_PERCENTUAL_RECOVERY ASC) 
LOGGING 
TABLESPACE TSISAFEPAY04 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLEL
CREATE UNIQUE INDEX SAFEPAY_ADM.PERCRECOVERYUSER_PK ON SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER (IDT_PERCENTUAL_RECOVERY_USER ASC) 
LOGGING 
TABLESPACE TSISAFEPAY02 
PCTFREE 10 
INITRANS 2 
STORAGE 
( 
  INITIAL 1048576 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOPARALLELCREATE TABLE SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER 
(
  IDT_PERCENTUAL_RECOVERY_USER NUMBER(9, 0) NOT NULL 
, IDT_PERCENTUAL_RECOVERY NUMBER(9, 0) NOT NULL 
, IDT_SAFEPAY_USER NUMBER(9, 0) NOT NULL 
, DAT_CREATION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, DAT_UPDATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, COD_CUSTOMER VARCHAR2(36 BYTE) 
) 
LOGGING 
TABLESPACE TSDSAFEPAY01 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 1048576 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  PCTINCREASE 0 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NOPARALLELALTER TABLE SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER
ADD CONSTRAINT PERCRECOVERY_PERCRECOVUSER_FK FOREIGN KEY
(
  IDT_PERCENTUAL_RECOVERY 
)
REFERENCES SAFEPAY_ADM.PERCENTUAL_RECOVERY
(
  IDT_PERCENTUAL_RECOVERY 
)
ENABLE
ALTER TABLE SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER
ADD CONSTRAINT SAFEPAYUSER_PERCRECOVUSER_FK FOREIGN KEY
(
  IDT_SAFEPAY_USER 
)
REFERENCES SAFEPAY_ADM.SAFEPAY_USER
(
  IDT_SAFEPAY_USER 
)
ENABLECOMMENT ON COLUMN SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER.IDT_PERCENTUAL_RECOVERY_USER IS 'ID incremental gerada pelo BD';
COMMENT ON COLUMN SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER.IDT_PERCENTUAL_RECOVERY IS 'ID das informaçoes de recuperacao de credito';
COMMENT ON COLUMN SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER.IDT_SAFEPAY_USER IS 'ID do usuario que autorizou o debito na conta';
COMMENT ON COLUMN SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER.DAT_CREATION IS 'Data de gravação do registro';
COMMENT ON COLUMN SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER.DAT_UPDATE IS 'Data da última atualização do registro';
COMMENT ON COLUMN SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER.COD_CUSTOMER IS 'Customer_cod referente ao usuario da transacao';COMMENT ON TABLE SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER IS 'Registros dos usuarios que autorizam o debito em sua conta e ID da tabela que contem informacoes da recuperacao.'ALTER TABLE SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER
ADD CONSTRAINT PERCRECOVERYUSER_PK PRIMARY KEY 
(
  IDT_PERCENTUAL_RECOVERY_USER 
)
USING INDEX PERCRECOVERYUSER_PK
ENABLE
