CREATE TABLE DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY 
(
  IDT_PERCENTUAL_RECOVERY NUMBER(20, 0) NOT NULL 
, DAT_START_RECOVERY DATE NOT NULL 
, DAT_END_RECOVERY DATE NOT NULL 
, NUM_PERCENTAGE NUMBER(9, 0) NOT NULL 
, NUM_TOTAL_AMOUNT NUMBER(10, 2) NOT NULL 
, NUM_RECOVERED_AMOUNT NUMBER(10, 2) NOT NULL 
, DES_RECOVERY VARCHAR2(255 BYTE) NOT NULL 
, IDT_FINANCIAL_ACCOUNT_DEST NUMBER(20, 0) NOT NULL 
, IND_STATUS CHAR(1 BYTE) NOT NULL 
, DAT_CREATION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, DAT_UPDATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
, IDT_USER_DEST NUMBER(20, 0) 
, IDT_TRANSACTION NUMBER(20, 0) 
, IDT_TRANSACTION_STATUS_HISTORY NUMBER(20, 0) 
, COD_TRANSACTION VARCHAR2(32 BYTE) 
, IDT_TURNOVER_TAG NUMBER(20, 0) 
, COD_REFERENCE VARCHAR2(36 BYTE) 
, IND_REASON CHAR(1 BYTE) 
, COD_DEBT_SCHEDULE VARCHAR2(36 BYTE) 
, COD_CUSTOMER_DESTINATION VARCHAR2(36 BYTE) 
, COD_BALLAST VARCHAR2(36 BYTE) 
, DES_BALLAST VARCHAR2(20 BYTE) 
, IND_RECOVERY_TYPE NUMBER(10, 0)  DEFAULT 1 NOT NULL
, CONSTRAINT PERCENTUAL_RECOVERY_PK PRIMARY KEY (IDT_PERCENTUAL_RECOVERY) USING INDEX TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12
) INITRANS 24
TABLESPACE TSDDEBITSCHEDULE01; 

COMMENT ON TABLE DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY IS 'Registros sobre as informacoes da nova forma de recuperação de crédito';

COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IDT_PERCENTUAL_RECOVERY IS '[NOT_SECURITY_APPLY] ID incremental gerada pelo BD. Sequence: SQ_PERCRECOVERY_IDT';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.DAT_START_RECOVERY IS '[NOT_SECURITY_APPLY] Data inicial do contrato da recuperação de credito';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.DAT_END_RECOVERY IS '[NOT_SECURITY_APPLY] Data final do contrato da recuperação de credito';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.NUM_PERCENTAGE IS '[NOT_SECURITY_APPLY] O valor da porcentagem cobrada sobre a recuperação de credito';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.NUM_TOTAL_AMOUNT IS '[NOT_SECURITY_APPLY] Valor total a ser recuperado';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.NUM_RECOVERED_AMOUNT IS '[NOT_SECURITY_APPLY] Valor parcial recuperado';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.DES_RECOVERY IS '[NOT_SECURITY_APPLY] Descricao recuperação do emprestimo que vai no extrato do cliente.';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IDT_FINANCIAL_ACCOUNT_DEST IS '[NOT_SECURITY_APPLY] Conta destino: onde sera depositado o valor recuperado';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IND_STATUS IS '[NOT_SECURITY_APPLY] Possíveis status da recuperacao de credito*: C (Concluido), N (NAO CONCLUIDO), P (PARCIALMENTE CONCLUIDO)*';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de gravação do registro';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data da última atualização do registro';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IDT_USER_DEST IS '[NOT_SECURITY_APPLY] Id do usuário do PagSeguro para o qual deve ser enviado o valor recuperado na liberação do pagamento.';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IDT_TRANSACTION IS '[NOT_SECURITY_APPLY] ID da transação de origem do saldo a recuperar';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IDT_TRANSACTION_STATUS_HISTORY IS '[NOT_SECURITY_APPLY] PK da tabela TRANSACTION_STATUS_HISTORY.';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.COD_TRANSACTION IS '[NOT_SECURITY_APPLY] Codigo da transação da tabela Transaction.';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IDT_TURNOVER_TAG IS '[NOT_SECURITY_APPLY] PK da tabela FINANCIAL_TURNOVER_TAG_DESC.';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.COD_REFERENCE IS '[NOT_SECURITY_APPLY] Codigo de referencia do recuperacao, pode ser utilizado para acompanhamento da recuperacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IND_REASON IS '[NOT_SECURITY_APPLY] Razao da criacao do recuperacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.COD_DEBT_SCHEDULE IS '[NOT_SECURITY_APPLY] Código gerado no cadastro do recuperacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.COD_CUSTOMER_DESTINATION IS '[NOT_SECURITY_APPLY] custormer_cod para qual sera feito a recuperacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.COD_BALLAST IS '[NOT_SECURITY_APPLY] Código de identificacao da aplicacao requerente';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.DES_BALLAST IS '[NOT_SECURITY_APPLY] Tipo de criacao da recuperacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY.IND_RECOVERY_TYPE IS '[NOT_SECURITY_APPLY] Tipo de bloqueio de débito: 1 - ACQUIRER / 2 - LOAN';

CREATE INDEX DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_IDX01 ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY (IDT_FINANCIAL_ACCOUNT_DEST) 
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

CREATE INDEX DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_IDX02 ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY (COD_REFERENCE ) 
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

CREATE INDEX DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_IDX03 ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY (COD_DEBT_SCHEDULE) 
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

ALTER TABLE DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY ADD CONSTRAINT PER_REC_IND_REA_CK 
CHECK (IND_REASON IN ('C','R')) ENABLE NOVALIDATE;

ALTER TABLE DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY ADD CONSTRAINT PER_REC_IND_REC_TYPE_CK 
CHECK (IND_RECOVERY_TYPE IN (1,2)) ENABLE NOVALIDATE;

GRANT SELECT,UPDATE,INSERT,DELETE ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY TO DEBITSCHEDULEUBR;