CREATE TABLE DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER 
(
  IDT_PERCENTUAL_RECOVERY_USER NUMBER(20, 0) NOT NULL
, IDT_PERCENTUAL_RECOVERY NUMBER(20, 0) NOT NULL 
, IDT_SAFEPAY_USER NUMBER(20, 0) NOT NULL 
, DAT_CREATION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL
, DAT_UPDATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL 
, COD_CUSTOMER VARCHAR2(36 BYTE) 
, CONSTRAINT PERCENTUAL_RECOVERY_USER_PK PRIMARY KEY (IDT_PERCENTUAL_RECOVERY_USER) USING INDEX TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12
) INITRANS 24
TABLESPACE TSDDEBITSCHEDULE01; 

COMMENT ON TABLE DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER IS 'Registros dos usuarios que autorizam o debito em sua conta e ID da tabela que contem informacoes da recuperacao.';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER.IDT_PERCENTUAL_RECOVERY_USER IS '[NOT_SECURITY_APPLY] ID incremental gerada pelo BD. Sequence: SQ_PERCRECOVERY_USER_IDT';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER.IDT_PERCENTUAL_RECOVERY IS '[NOT_SECURITY_APPLY] ID das informaçoes de recuperacao de credito';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER.IDT_SAFEPAY_USER IS '[NOT_SECURITY_APPLY] ID do usuario que autorizou o debito na conta';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de gravação do registro';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER.DAT_UPDATE IS '[NOT_SECURITY_APPLY] Data da última atualização do registro';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER.COD_CUSTOMER IS '[NOT_SECURITY_APPLY] Customer_cod referente ao usuario da transacao';

ALTER TABLE DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER ADD CONSTRAINT PERCRECOVERY_PERCRECOVUSER_FK FOREIGN KEY (IDT_PERCENTUAL_RECOVERY)
REFERENCES DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY( IDT_PERCENTUAL_RECOVERY ) ENABLE NOVALIDATE;

CREATE INDEX DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER_IDX01 ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER (IDT_PERCENTUAL_RECOVERY) 
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

CREATE INDEX DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER_IDX02 ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER (IDT_SAFEPAY_USER) 
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

CREATE INDEX DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER_IDX03 ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER (IDT_SAFEPAY_USER , IDT_PERCENTUAL_RECOVERY ) 
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

CREATE INDEX DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER_IDX04 ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY_USER (COD_CUSTOMER , IDT_PERCENTUAL_RECOVERY ) 
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

GRANT SELECT,UPDATE,INSERT,DELETE ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY TO DEBITSCHEDULEUBR;