CREATE TABLE DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT
(
    IDT_RECOVERY_FINANCIAL_MOVEMENT NUMBER(20, 0) GENERATED ALWAYS AS IDENTITY INCREMENT BY 1 MAXVALUE 9999999999999999999999999999 MINVALUE 1 CACHE 100 NOCYCLE NOORDER NOT NULL,
	COD_RECOVERY_FINANCIAL_MOVEMENT VARCHAR2(36 BYTE)  NOT NULL, 
    COD_REFERENCE VARCHAR2(36 BYTE)  NOT NULL,
    IDT_PERCENTUAL_RECOVERY NUMBER(20, 0),
    IDT_CHARGEBACK_RECOVERY NUMBER(20, 0),
    NUM_RECOVERED_AMOUNT NUMERIC(10,2) NOT NULL,
    DAT_CREATION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL,
    DAT_UPDATE TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, 
    IDT_SAFEPAY_DEBTOR NUMBER(20, 0) NOT NULL,
    IDT_FINANCIAL_ACCOUNT_DEBT_TYPE NUMBER(20, 0) NOT NULL,
    JSN_PAYLOAD VARCHAR2(4000 BYTE),
    IND_STATUS VARCHAR2(20 BYTE),
    CONSTRAINT RECOVERY_FINANCIAL_MOVEMENT_PK PRIMARY KEY (IDT_RECOVERY_FINANCIAL_MOVEMENT) USING INDEX TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12,
    CONSTRAINT JSN_PAYLOAD_CK CHECK ( JSN_PAYLOAD IS JSON )
) INITRANS 24
TABLESPACE TSDDEBITSCHEDULE01; 

COMMENT ON TABLE DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT IS 'Registros dos usuarios que autorizam o debito em sua conta e ID da tabela que contem informacoes da recuperacao.';

COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.COD_RECOVERY_FINANCIAL_MOVEMENT  IS '[NOT_SECURITY_APPLY] [PK] Identificador de recuperacao de movimentacao financeira';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.IDT_RECOVERY_FINANCIAL_MOVEMENT  IS '[NOT_SECURITY_APPLY] [UK] Codigo de recuperacao de movimentacao financeira';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.COD_REFERENCE  IS '[NOT_SECURITY_APPLY] Codigo de referencia da transação cod_safepay_transaction';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.IDT_PERCENTUAL_RECOVERY IS '[NOT_SECURITY_APPLY] Identificador do percentual de recuperacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.IDT_CHARGEBACK_RECOVERY  IS '[NOT_SECURITY_APPLY] Identificador do chargeback de recuperacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.NUM_RECOVERED_AMOUNT  IS '[NOT_SECURITY_APPLY] Valor recuperado';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.DAT_CREATION  IS '[NOT_SECURITY_APPLY] Data de Criacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.DAT_UPDATE  IS '[NOT_SECURITY_APPLY] Data de Atualizacao';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.IDT_SAFEPAY_DEBTOR  IS '[NOT_SECURITY_APPLY] Identificador do usuario devedor';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.IDT_FINANCIAL_ACCOUNT_DEBT_TYPE  IS '[NOT_SECURITY_APPLY] Identificador do tipo de conta de debito';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.JSN_PAYLOAD IS '[NOT_SECURITY_APPLY] JSON do Payload';
COMMENT ON COLUMN DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT.IND_STATUS IS '[NOT_SECURITY_APPLY] Indicador de Status da movimentacao';

ALTER TABLE DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT ADD CONSTRAINT RECY_FIN_MOV_PERCRECOVUSER_FK FOREIGN KEY (IDT_PERCENTUAL_RECOVERY)
REFERENCES DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY( IDT_PERCENTUAL_RECOVERY ) ENABLE NOVALIDATE;

ALTER TABLE DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT ADD CONSTRAINT RECOVERY_FINANCIAL_MOVEMENT_UK01 UNIQUE ( COD_RECOVERY_FINANCIAL_MOVEMENT ) USING INDEX TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ENABLE NOVALIDATE;

CREATE INDEX RECOVERY_FIN_MOVEMENT_IDX01 ON DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT (COD_REFERENCE)
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

CREATE INDEX RECOVERY_FIN_MOVEMENT_IDX02 ON DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT (DAT_CREATION)
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

CREATE INDEX RECOVERY_FIN_MOVEMENT_IDX03 ON DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT (DAT_UPDATE)
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

CREATE INDEX RECOVERY_FIN_MOVEMENT_IDX04 ON DEBITSCHEDULE_ADM.RECOVERY_FINANCIAL_MOVEMENT (IDT_PERCENTUAL_RECOVERY)
TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12 ONLINE; 

GRANT SELECT,UPDATE,INSERT,DELETE ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY TO DEBITSCHEDULEUBR;
GRANT SELECT ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY TO MANUT_DEBITSCHEDULE;
