CREATE TABLE DEBITSCHEDULE_ADM.NONEXIST_RECOVERY_IDEMPOTENCY
(
    COD_NONEXIST_RECOVERY_IDEMPOTENCY VARCHAR2(36 BYTE)  NOT NULL,
    DAT_CREATION TIMESTAMP(6) DEFAULT SYSTIMESTAMP NOT NULL, 
    NUM_VERSION NUMBER(20, 0) NOT NULL,
    CONSTRAINT COD_NONEXIST_RECOVERY_IDEMPOTENCY_PK PRIMARY KEY (COD_NONEXIST_RECOVERY_IDEMPOTENCY) USING INDEX TABLESPACE TSIDEBITSCHEDULE01 INITRANS 12
) PARTITION BY
RANGE(DAT_CREATION)
INTERVAL(NUMTOYMINTERVAL(1, 'MONTH'))
(PARTITION P_1 VALUES LESS THAN (TO_DATE('2021-03-01','YYYY-MM-DD'))
) TABLESPACE TSDDEBITSCHEDULE01 INITRANS 24 PCTFREE 20
;

COMMENT ON TABLE DEBITSCHEDULE_ADM.NONEXIST_RECOVERY_IDEMPOTENCY IS 'TABELA DE CONTROLE DE IDEMPOTENCIA PARA NAO PROCESSAMENTO DE RECUPERACOES';

COMMENT ON COLUMN DEBITSCHEDULE_ADM.NONEXIST_RECOVERY_IDEMPOTENCY.COD_NONEXIST_RECOVERY_IDEMPOTENCY IS '[NOT_SECURITY_APPLY] [PK] Codigo de de idempotencia para processamento recuperacoes';

COMMENT ON COLUMN DEBITSCHEDULE_ADM.NONEXIST_RECOVERY_IDEMPOTENCY.DAT_CREATION IS '[NOT_SECURITY_APPLY] Data de Criacao';

COMMENT ON COLUMN DEBITSCHEDULE_ADM.NONEXIST_RECOVERY_IDEMPOTENCY.NUM_VERSION IS '[NOT_SECURITY_APPLY] Numero de Versao';

GRANT SELECT,UPDATE,INSERT,DELETE ON DEBITSCHEDULE_ADM.PERCENTUAL_RECOVERY TO DEBITSCHEDULEUBR;