-- COM USUARIO DBA CONECTADO NA BASE PHO

-- TABLESPACES
-- @system
CREATE TABLESPACE TSDDEBITSCHEDULE
  DATAFILE 	'+DATA' SIZE 500M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1024K SEGMENT SPACE MANAGEMENT AUTO;

CREATE TABLESPACE TSIDEBITSCHEDULE
  DATAFILE 	'+DATA' SIZE 500M
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1024K SEGMENT SPACE MANAGEMENT AUTO;


-----------------------------------------------------------------------------------------------------
-- PROFILE / SCHEMA / USER
-- @system
CREATE PROFILE PR_DEBITSCHEDULE
      LIMIT
         COMPOSITE_LIMIT DEFAULT
         SESSIONS_PER_USER 250
         CPU_PER_SESSION DEFAULT
         CPU_PER_CALL DEFAULT
         LOGICAL_READS_PER_SESSION DEFAULT
         LOGICAL_READS_PER_CALL DEFAULT
         IDLE_TIME DEFAULT
         CONNECT_TIME DEFAULT
         PRIVATE_SGA DEFAULT
         FAILED_LOGIN_ATTEMPTS UNLIMITED
         PASSWORD_LIFE_TIME UNLIMITED
         PASSWORD_REUSE_TIME UNLIMITED
         PASSWORD_REUSE_MAX UNLIMITED
         PASSWORD_VERIFY_FUNCTION NULL
         PASSWORD_LOCK_TIME UNLIMITED
         PASSWORD_GRACE_TIME UNLIMITED;
		 
-- QA		 
CREATE USER DEBITSCHEDULEUBR IDENTIFIED BY "LVhS9ZZyDnMhY2k2" 
DEFAULT TABLESPACE TSDDEBITSCHEDULE
TEMPORARY TABLESPACE TEMP 
PROFILE PR_DEBITSCHEDULE;

-- PROD
/*
CREATE USER DEBITSCHEDULEUBR IDENTIFIED BY "vPNKCKjVj3QPNsFd" 
DEFAULT TABLESPACE TSDDEBITSCHEDULE
TEMPORARY TABLESPACE TEMP 
PROFILE PR_DEBITSCHEDULE;
*/

GRANT CREATE SESSION TO DEBITSCHEDULEUBR;
GRANT CONNECT, RESOURCE TO DEBITSCHEDULEUBR;
GRANT CREATE TABLE TO DEBITSCHEDULEUBR;
GRANT CREATE SYNONYM TO DEBITSCHEDULEUBR;
GRANT CREATE PUBLIC SYNONYM TO DEBITSCHEDULEUBR;
GRANT CREATE SEQUENCE TO DEBITSCHEDULEUBR;

ALTER USER DEBITSCHEDULEUBR QUOTA UNLIMITED ON TSDDEBITSCHEDULE;
ALTER USER DEBITSCHEDULEUBR QUOTA UNLIMITED ON TSIDEBITSCHEDULE;

GRANT SELECT, INSERT, UPDATE ON SAFEPAY_ADM.PERCENTUAL_RECOVERY TO DEBITSCHEDULEUBR;
GRANT SELECT, INSERT, UPDATE ON SAFEPAY_ADM.CHARGEBACK_RECOVERY TO DEBITSCHEDULEUBR;
GRANT SELECT, INSERT, UPDATE ON SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER TO DEBITSCHEDULEUBR;

GRANT SELECT ON SAFEPAY_ADM.SQ_PERCRECOVERY_IDT TO DEBITSCHEDULEUBR;
GRANT SELECT ON SAFEPAY_ADM.SQ_PERCRECOVERY_USER_IDT TO DEBITSCHEDULEUBR;
GRANT SELECT ON SAFEPAY_ADM.SQ_CHARRECO_IDT TO DEBITSCHEDULEUBR;

create or replace synonym DEBITSCHEDULEUBR.PERCENTUAL_RECOVERY for SAFEPAY_ADM.PERCENTUAL_RECOVERY;
create or replace synonym DEBITSCHEDULEUBR.CHARGEBACK_RECOVERY for SAFEPAY_ADM.CHARGEBACK_RECOVERY;
create or replace synonym DEBITSCHEDULEUBR.PERCENTUAL_RECOVERY_USER for SAFEPAY_ADM.PERCENTUAL_RECOVERY_USER;

create or replace synonym DEBITSCHEDULEUBR.SQ_PERCRECOVERY_IDT for SAFEPAY_ADM.SQ_PERCRECOVERY_IDT;
create or replace synonym DEBITSCHEDULEUBR.SQ_PERCRECOVERY_USER_IDT for SAFEPAY_ADM.SQ_PERCRECOVERY_USER_IDT;
create or replace synonym DEBITSCHEDULEUBR.SQ_CHARRECO_IDT for SAFEPAY_ADM.SQ_CHARRECO_IDT;